/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
#ifndef __EJE_SWRB_TEST_SNSETTINGDLG_H
#define __EJE_SWRB_TEST_SNSETTINGDLG_H

#include "DIALOG.h"
#include "ff.h"
#include "stm32f4xx.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSettingDLG
*/
WM_HWIN CreateSNSettingDLG(void);

FRESULT SWRB_TestDataFileOpen(u8 fileOpenMode);
void SWRB_TestDataSaveToFile(void dataSaveProc(void));
void SWRB_TestDataFileWriteSN(void);
void SWRB_TestDUTWriteSN(void);
void SWRB_ListWheelRTCDateUpdate(WM_HWIN hWin, int idYear, int idMonth, int idDay);
void SWRB_ListWheelLastItemPosGet(void);
void SWRB_ListWheelSNInc(WM_HWIN hWin);

#endif
/*************************** End of file ****************************/
