#ifndef __EJE_SWRB_TEST_MANULDLG_H
#define __EJE_SWRB_TEST_MANULDLG_H

#include "Dialog.h"

enum SWRB_MANUL_TEST_LISTVIEW_COLUMN{
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_NAME,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_L,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_FL,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_M,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_FR,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_R,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_BL,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_BFL,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_BFR,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_BR,
    SWRB_MANUL_TEST_LISTVIEW_COLUMN_BOUND,
};

enum SWRB_MANUL_TEST_LISTVIEW_ROW{  
    SWRB_MANUL_TEST_LISTVIEW_ROW_WHEEL,
    SWRB_MANUL_TEST_LISTVIEW_ROW_BRUSH,
    SWRB_MANUL_TEST_LISTVIEW_ROW_FAN,
    SWRB_MANUL_TEST_LISTVIEW_ROW_IFRD,
    SWRB_MANUL_TEST_LISTVIEW_ROW_COLLISION,
    SWRB_MANUL_TEST_LISTVIEW_ROW_WHEEL_FLOAT,
    SWRB_MANUL_TEST_LISTVIEW_ROW_ASH_TRAY,
    SWRB_MANUL_TEST_LISTVIEW_ROW_UNIWHEEL,
    SWRB_MANUL_TEST_LISTVIEW_ROW_KEY,
    SWRB_MANUL_TEST_LISTVIEW_ROW_IRDA,
    SWRB_MANUL_TEST_LISTVIEW_ROW_BUZZER,
    SWRB_MANUL_TEST_LISTVIEW_ROW_RGB_LED,
    SWRB_MANUL_TEST_LISTVIEW_ROW_CHARGE,
    SWRB_MANUL_TEST_LISTVIEW_ROW_INT_VREF,
    SWRB_MANUL_TEST_LISTVIEW_ROW_SNUM,
    SWRB_MANUL_TEST_LISTVIEW_ROW_BOUND,
};

extern WM_HWIN CreateManulTestDLG(void);

#endif
