/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_SET_FRAMEWIN_0 (ID_MAIN_BOUND + 0x00)
#define ID_SET_LISTWHEEL_0 (ID_MAIN_BOUND + 0x01)
#define ID_SET_BUTTON_0 (ID_MAIN_BOUND + 0x02)
#define ID_SET_BUTTON_1 (ID_MAIN_BOUND + 0x03)
#define ID_SET_LISTWHEEL_1 (ID_MAIN_BOUND + 0x04)
#define ID_SET_LISTWHEEL_2 (ID_MAIN_BOUND + 0x05)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

extern WM_HWIN hWinEJE_SWRB_TEST_SETTING;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSettingDLG
*/
WM_HWIN CreateSettingDLG(void);

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
