/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "sweeprobot_testing.h"
#include "eje_logo_char.h"

extern GUI_CONST_STORAGE GUI_FONT GUI_FontmySongti33;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_START;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static GUI_CONST_STORAGE GUI_COLOR _aColorsCHNText[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalCHNText = {
  2,	/* number of entries */
  1, 	/* No transparency */
  &_aColorsCHNText[0]
};

static GUI_CONST_STORAGE unsigned char acPCBTestStr[] = { /* code PCB Test */
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ______X_,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,____XX__,________,________,	  ______XX,X_______,________,XXX_____,	  ____XX__,__X_____,__X_____,___XX___,	  ________,________,_____XX_,XX______,
  ________,_____XXX,________,________,	  ______XX,________,______XX,XXXX____,	  _____XX_,__XXXXXX,XXXX____,___XX___,	  ____XX__,________,_____XXX,_XX_____,
  ________,______XX,X_______,________,	  ______XX,______X_,__XXXXX_,________,	  ______XX,__XX____,__XX____,___XX___,	  _____XX_,________,_____XX_,__XX____,
  ________,_______X,XX______,________,	  ______XX,______XX,XX______,________,	  ______XX,__XX____,__XX____,___XX___,	  _____XXX,________,_____XX_,__XX____,
  ________,_______X,XX______,________,	  ______XX,______XX,________,________,	  ______X_,__XX____,__XX__XX,___XX___,	  ______XX,________,_____XX_,___X____,
  ________,________,X_______,__X_____,	  ______XX,___X__XX,________,________,	  ________,__XX__X_,__XX__XX,X__XX___,	  ______XX,________,_____XX_,____X___,
  ________,________,________,_XXX____,	  _XXXXXXX,XXXXX_XX,________,________,	  ________,__XX__XX,X_XX__XX,___XX___,	  ______XX,________,_____XX_,___XXX__,
  ____XXXX,XXXXXXXX,XXXXXXXX,X_______,	  ______XX,______XX,________,________,	  __XX____,__XX__XX,__XX__XX,___XX___,	  ________,___XXXXX,XXXXXXXX,XXX_____,
  ________,_______X,X_______,________,	  ______XX,______XX,________,_XX_____,	  ___XX___,X_XX__XX,__XX__XX,___XX___,	  ________,________,_____XX_,________,
  ________,_______X,X_______,________,	  ______XX,______XX,XXXXXXXX,XXXX____,	  ___XXX__,X_XX__XX,__XX__XX,___XX___,	  ________,________,_____XX_,________,
  ________,_______X,X_______,________,	  ______XX,______XX,_X______,_XX_____,	  ____XX__,X_XX__XX,__XX__XX,___XX___,	  _______X,________,_____XX_,________,
  ________,_______X,X_______,________,	  _____XXX,XX____XX,_X______,XX______,	  ____X__X,__XX__XX,__XX__XX,___XX___,	  _XXXXXXX,X_______,___X_XX_,________,
  ________,_______X,X_______,________,	  _____XXX,_XX___XX,__X_____,XX______,	  _______X,__XX__XX,__XX__XX,___XX___,	  ______XX,________,__XXXXX_,________,
  ________,_______X,X_______,________,	  _____XXX,__XX__XX,__X_____,XX______,	  _______X,__XX__X_,__XX__XX,___XX___,	  ______XX,____XXXX,XX____X_,________,
  ________,_______X,X_______,X_______,	  ____XXXX,__XX__XX,__X____X,X_______,	  _______X,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____X_,________,
  ________,_______X,XXXXXXXX,XX______,	  ____X_XX,___X__XX,___X___X,X_______,	  ______X_,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____XX,________,
  ______XX,XXXXXXXX,X_______,________,	  ____X_XX,______X_,___X___X,________,	  ______X_,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____XX,________,
  ________,_______X,X_______,________,	  ___X__XX,______X_,___XX_XX,________,	  _____XX_,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____XX,________,
  ________,_______X,X_______,________,	  ___X__XX,______X_,____X_X_,________,	  _XXXXXX_,__XX_XX_,__X___XX,___XX___,	  ______XX,_______X,X______X,X_______,
  ________,_______X,X_______,________,	  __X___XX,_____XX_,____XXX_,________,	  ___XXX__,__X__XX_,______XX,___XX___,	  ______XX,___X___X,X______X,X_______,
  ________,_______X,X_______,________,	  _X____XX,_____XX_,____XXX_,________,	  ____XX__,_____X_X,______XX,___XX___,	  ______XX,___X___X,X_______,X____X__,
  ________,_______X,X_______,________,	  ______XX,_____X__,___XXXX_,________,	  ____XX__,____XX__,X_______,___XX___,	  ______XX,__X____X,X_XXXX__,XX___X__,
  ________,_______X,X_______,________,	  ______XX,____XX__,__XX__XX,________,	  ____XX__,____X___,_X______,___XX___,	  ______XX,_X_____X,XX______,_XX__X__,
  ________,_______X,X_______,___X____,	  ______XX,____X___,_XX____X,XX______,	  ____XX__,___XX___,_XXX____,___XX___,	  ______XX,XX_XXXXX,________,_XX__X__,
  ________,_______X,X_______,__XXX___,	  ______XX,___XX___,XX______,XXX_____,	  ____XX__,__XX____,__XX____,___XX___,	  ______XX,X__XXX__,________,__XX_X__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,	  ______XX,___X__XX,________,_XXXXX__,	  ____XX__,_XX_____,__XX___X,XXXX____,	  ______XX,X___X___,________,___XXX__,
  __X_____,________,________,________,	  ______XX,__X_XX__,________,__XXX___,	  ________,X_______,___X____,_XXX____,	  _______X,________,________,____XX__,
  ________,________,________,________,	  ______XX,_X_X____,________,___X____,	  _______X,________,________,__X_____,	  ________,________,________,_____X__,
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE unsigned char acPSTestStr[] = {
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,______X_,________,________,	  ________,______XX,________,________,	  ________,_______X,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,______XX,________,________,	  ________,______XX,X_______,________,	  ________,________,XX______,________,	  ____XX__,__X_____,__X_____,___XX___,	  ________,________,_____XX_,XX______,
  ________,_______X,X_______,________,	  ________,______XX,________,________,	  ________,________,XXX_____,________,	  _____XX_,__XXXXXX,XXXX____,___XX___,	  ____XX__,________,_____XXX,_XX_____,
  ________,_______X,X_______,__XX____,	  ________,______XX,________,________,	  ________,________,_X______,__XX____,	  ______XX,__XX____,__XX____,___XX___,	  _____XX_,________,_____XX_,__XX____,
  ________,_______X,X_______,_XXXX___,	  ________,______XX,________,________,	  _____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,	  ______XX,__XX____,__XX____,___XX___,	  _____XXX,________,_____XX_,__XX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,	  ________,______XX,________,________,	  _____XX_,________,________,________,	  ______X_,__XX____,__XX__XX,___XX___,	  ______XX,________,_____XX_,___X____,
  ________,_____XX_,________,________,	  _____XXX,XXXXXXXX,XXXXXXXX,XX______,	  _____XX_,________,________,________,	  ________,__XX__X_,__XX__XX,X__XX___,	  ______XX,________,_____XX_,____X___,
  ________,____XXXX,________,________,	  _____XX_,______XX,________,XX______,	  _____XX_,________,_XX_____,________,	  ________,__XX__XX,X_XX__XX,___XX___,	  ______XX,________,_____XX_,___XXX__,
  ________,___XXX__,________,________,	  _____XX_,______XX,________,XX______,	  _____XX_,___X____,_XX_____,X_______,	  __XX____,__XX__XX,__XX__XX,___XX___,	  ________,___XXXXX,XXXXXXXX,XXX_____,
  ________,__XXX___,___XX___,________,	  _____XX_,______XX,________,XX______,	  _____XX_,___XXX__,_XX_____,XX______,	  ___XX___,X_XX__XX,__XX__XX,___XX___,	  ________,________,_____XX_,________,
  ________,_XX_____,_____XX_,________,	  _____XX_,______XX,________,XX______,	  _____XX_,___XX___,_XX____X,XX______,	  ___XXX__,X_XX__XX,__XX__XX,___XX___,	  ________,________,_____XX_,________,
  ________,XX______,______XX,________,	  _____XX_,______XX,________,XX______,	  _____XX_,___X____,_XX____X,X_______,	  ____XX__,X_XX__XX,__XX__XX,___XX___,	  _______X,________,_____XX_,________,
  _______X,X_______,_______X,XX______,	  _____XX_,______XX,________,XX______,	  _____XX_,__XX____,_XX____X,X_______,	  ____X__X,__XX__XX,__XX__XX,___XX___,	  _XXXXXXX,X_______,___X_XX_,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,	  _____XXX,XXXXXXXX,XXXXXXXX,XX______,	  _____XX_,__XXX___,_XX___XX,_X______,	  _______X,__XX__XX,__XX__XX,___XX___,	  ______XX,________,__XXXXX_,________,
  ______XX,XX_XX___,__X_____,XXX_____,	  _____XX_,______XX,________,XX______,	  _____XX_,_XX_XX__,_XX___XX,__XX____,	  _______X,__XX__X_,__XX__XX,___XX___,	  ______XX,____XXXX,XX____X_,________,
  ________,___XX___,__X_____,_XX_____,	  _____XX_,______XX,________,XX______,	  _____XX_,_X___XX_,_XX___X_,__XXX___,	  _______X,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____X_,________,
  ________,___XX___,__X_____,________,	  _____XX_,______XX,________,XX______,	  _____XX_,_X____XX,_XX__X__,___XX___,	  ______X_,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____XX,________,
  ________,___XX___,__X_____,________,	  _____XX_,______XX,________,XX______,	  _____X__,X_____X_,_XX_X___,____X___,	  ______X_,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____XX,________,
  ________,___XX___,__X_____,________,	  _____XX_,______XX,________,XX______,	  _____X_X,________,_XX_X___,_X______,	  _____XX_,__XX__X_,__XX__XX,___XX___,	  ______XX,_______X,X_____XX,________,
  ________,__XX____,__X_____,________,	  _____XXX,XXXXXXXX,XXXXXXXX,XX______,	  _____X__,________,_XX_____,XXX_____,	  _XXXXXX_,__XX_XX_,__X___XX,___XX___,	  ______XX,_______X,X______X,X_______,
  ________,__XX____,__X_____,________,	  _____XX_,______XX,________,X_______,	  ____XX__,__XXXXXX,XXXXXXXX,XXXX____,	  ___XXX__,__X__XX_,______XX,___XX___,	  ______XX,___X___X,X______X,X_______,
  ________,__XX____,__X_____,___X____,	  _____XX_,______XX,________,________,	  ____XX__,________,_XX_____,________,	  ____XX__,_____X_X,______XX,___XX___,	  ______XX,___X___X,X_______,X____X__,
  ________,_XX_____,__X_____,____X___,	  ________,______XX,________,___X____,	  ____X___,________,_XX_____,________,	  ____XX__,____XX__,X_______,___XX___,	  ______XX,__X____X,X_XXXX__,XX___X__,
  ________,_XX_____,__X_____,____X___,	  ________,______XX,________,____X___,	  ____X___,________,_XX_____,________,	  ____XX__,____X___,_X______,___XX___,	  ______XX,_X_____X,XX______,_XX__X__,
  ________,XX______,__X_____,____X___,	  ________,______XX,________,____X___,	  ___XX___,________,_XX_____,________,	  ____XX__,___XX___,_XXX____,___XX___,	  ______XX,XX_XXXXX,________,_XX__X__,
  _______X,X_______,__X_____,___XX___,	  ________,______XX,________,___XX___,	  ___X____,________,_XX_____,___XX___,	  ____XX__,__XX____,__XX____,___XX___,	  ______XX,X__XXX__,________,__XX_X__,
  ______XX,________,__XXXXXX,XXXXXX__,	  ________,______XX,X_______,___XXX__,	  __X_____,________,_XX_____,__XXXX__,	  ____XX__,_XX_____,__XX___X,XXXX____,	  ______XX,X___X___,________,___XXX__,
  ____XX__,________,__XXXXXX,XXXXX___,	  ________,_______X,XXXXXXXX,XXXXX___,	  __X____X,XXXXXXXX,XXXXXXXX,XXXXXXX_,	  ________,X_______,___X____,_XXX____,	  _______X,________,________,____XX__,
  __XX____,________,________,________,	  ________,________,________,________,	  _X______,________,________,________,	  _______X,________,________,__X_____,	  ________,________,________,_____X__,
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________,	  ________,________,________,________

};

static GUI_CONST_STORAGE GUI_BITMAP _bmPCBTestCHN = {
  128,                  /* XSize */
  33,                   /* YSize */
  16,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acPCBTestStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmPSTestCHN = {
  160,              /* XSize */
  33,               /* YSize */
  20,                /* BytesPerLine */
  1,                /* BitsPerPixel */
  acPSTestStr,     /* Pointer to picture data (indices) */
  &_PalCHNText      /* Pointer to palette */
};

/*********************************************************************
*
*       _aDialogStart
*/
static const GUI_WIDGET_CREATE_INFO _aDialogStart[] = {
    { WINDOW_CreateIndirect, "Window", ID_START_WINDOW_START, 0, 0, 800, 480, 0, 0x0, 0 },
    { IMAGE_CreateIndirect, "Image", ID_START_IMAGE_LOGO, 272, 32, 255, 62, 0, 0, 0 },
    { TEXT_CreateIndirect, "Title", ID_START_TEXT_TITLE, 225, 100, 350, 35, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "PCB TEST", ID_START_BUTTON_PCB_TEST, 100, 205, 200, 180, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "POWER STATION", ID_START_BUTTON_POWER_STATION, 500, 203, 200, 180, 0, 0x0, 0 },
//    { BUTTON_CreateIndirect, "Decrypto", ID_START_BUTTON_DECRYPTO, 500, 203, 200, 180, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_START_TEXT_VERSION, 600, 430, 200, 50, 0, 0x64, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
static const void * _GetImageById(U32 Id, U32 * pSize)
{
    switch (Id) {
        case ID_START_IMAGE_0_IMAGE_0:
            *pSize = sizeof(_acImage_eje_logo);
            return (const void *)_acImage_eje_logo;
    }
    return NULL;
}

static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    BUTTON_SetSkinClassic(hItem);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_Simple);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    const void * pData;
    WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;

    switch (pMsg->MsgId) {
        case WM_INIT_DIALOG:
            //
            // Initialization of 'Image'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_START_IMAGE_LOGO);
            pData = _GetImageById(ID_START_IMAGE_0_IMAGE_0, &FileSize);
            IMAGE_SetBMP(hItem, pData, FileSize);
            //
            // Initialization of 'PCB TEST'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_START_BUTTON_PCB_TEST);
            BUTTON_SetText(hItem, " ");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_START_BUTTON_PCB_TEST, &_bmPCBTestCHN, 36, 74);
            Button_Init(hItem);
            //
            // Initialization of 'POWER STATION'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_START_BUTTON_POWER_STATION);
            BUTTON_SetText(hItem, " ");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_START_BUTTON_POWER_STATION, &_bmPSTestCHN, 20, 74);
            Button_Init(hItem);
            //
            // Initialization of 'DECRYPTO'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_START_BUTTON_DECRYPTO);
            BUTTON_SetText(hItem, "Decrypto");
            Button_Init(hItem);
            //
            // Initialization of 'Title'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_START_TEXT_TITLE);
            TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
            TEXT_SetTextColor(hItem, GUI_BLUE);
            TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            TEXT_SetText(hItem, "SweepRobot Test System");
            WM_BringToTop(hItem);
            //
            // Initialization of 'Text'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_START_TEXT_VERSION);
            TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
            TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            TEXT_SetText(hItem, "SWRB Fixture Ver:1.0");
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
                case ID_START_BUTTON_PCB_TEST: // Notifications sent by 'PCB TEST'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            SweepRobot_StartDlgPCBBtnClickProc();
                            break;
                    }
                    break;
                case ID_START_BUTTON_POWER_STATION: // Notifications sent by 'POWER STATION'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            SweepRobot_StartDlgPowerStationBtnClickPorc();
                            break;
                    }
                    break;
                case ID_START_BUTTON_DECRYPTO: // Notifications sent by 'Decrypto'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
//                            SweepRobot_StartDlgDecryptoBtnClickPorc();
                            break;
                    }
                    break;
            }
            break;
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateEJE_SWRB_TEST_StartDLG(void) {
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogStart, GUI_COUNTOF(_aDialogStart), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
