/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "sweeprobot_testing.h"
#include "sweeprobot_testing_rgb_led.h"
#include "sweeprobot_testing_buzzer.h"

#include "usart.h"
#include "led.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_IMAGE_0_IMAGE_0 0x00

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_MAIN;
WM_HWIN hWin_SWRB_RGB_LED;
WM_HWIN hWin_SWRB_BUZZER;

static u8 gMainDLGIndicateFlag = 0;

static GUI_CONST_STORAGE GUI_COLOR _aColorsCHNText[] = {
  0xFFFFFF, 0x000000
};

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalCHNText = {
  2,	/* number of entries */
  1, 	/* No transparency */
  &_aColorsCHNText[0]
};

static GUI_CONST_STORAGE unsigned char acStartBtnStr[] = {
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  _______X,________,____X___,________,
  ________,________,________,__X_____,	  _______X,XX______,____XXX_,________,
  ________,________,________,_XXX____,	  _______X,X_______,___XXX__,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,	  _______X,X_______,___XX___,________,
  ________,__XX____,____XX__,________,	  _______X,________,___X____,________,
  ________,__XX____,____XX__,________,	  ______XX,________,__XX____,________,
  ________,__XX____,____XX__,________,	  ______XX,________,__X_____,XX______,
  ________,__XX____,____XX__,________,	  ______XX,____XX__,_XX_____,_XX_____,
  ________,__XX____,____XX__,________,	  __XXXXX_,XXXXXX__,_X______,__XX____,
  ________,__XX____,____XX__,________,	  _____XX_,___XX___,X_______,___XX___,
  ________,__XX____,____XX__,________,	  _____XX_,___XX__X,X_______,___XXX__,
  ________,__XX____,____XX__,___XX___,	  _____XX_,___XX__X,XXXXXXXX,XXX_XX__,
  ________,__XX____,____XX__,__XXXX__,	  _____X__,___XX__X,XX______,____XX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,	  ____XX__,___X____,________,________,
  ________,__XX____,____XX__,________,	  ____XX__,__XX____,________,________,
  ________,__XX____,____XX__,________,	  ____X___,__XX____,X_______,___X____,
  ________,__XX____,____XX__,________,	  ____X___,__XX____,XXXXXXXX,XXXXX___,
  ________,__XX____,____XX__,________,	  ___XX___,__X_____,XX______,__XX____,
  ________,__XX____,____XX__,________,	  ___XX___,_XX_____,XX______,__XX____,
  ________,__X_____,____XX__,________,	  _____XX_,_XX_____,XX______,__XX____,
  ________,_XX_____,____XX__,________,	  _______X,XX______,XX______,__XX____,
  ________,_X______,____XX__,________,	  ________,XXXX____,XX______,__XX____,
  ________,XX______,____XX__,________,	  _______X,X_XXX___,XX______,__XX____,
  ________,X_______,____XX__,________,	  _______X,___XXX__,XX______,__XX____,
  _______X,________,____XX__,________,	  ______XX,____XX__,XX______,__XX____,
  ______X_,________,____XX__,________,	  _____XX_,________,XXXXXXXX,XXXX____,
  _____X__,________,____XX__,________,	  ____XX__,________,XX______,__XX____,
  ____X___,________,____XX__,________,	  ___X____,________,XX______,__XX____,
  __XX____,________,____X___,________,	  __X_____,________,X_______,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE unsigned char acPauseBtnStr[] = {
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,_X______,________,________,	  _______X,________,_X______,________,
  ________,XXX_____,________,_XXX____,	  _______X,XX______,__XX____,________,
  ________,XX_____X,__X___XX,XXXXX___,	  _______X,X_______,__XXX___,________,
  ________,X_____XX,X_XXXX__,________,	  _______X,________,___X____,__XX____,
  ___XXXXX,XXXXXXXX,XXXX____,________,	  ______XX,__XXXXXX,XXXXXXXX,XXXXX___,
  _______X,__X_____,__XX____,________,	  ______XX,________,________,________,
  ______XX,__XXX___,__XX____,____X___,	  ______X_,_____X__,________,X_______,
  ______X_,__XX___X,__XXXXXX,XXXXXX__,	  _____XX_,______XX,XXXXXXXX,XX______,
  _____XX_,__XX__XX,X_XX____,XX______,	  _____XXX,______X_,_______X,X_______,
  _____XXX,XXXXXXXX,XXXX____,XX______,	  ____XXX_,______X_,_______X,X_______,
  ________,__XX____,__XX____,XX______,	  ____XXX_,______X_,_______X,X_______,
  ________,__XX__XX,X_XX____,XX______,	  ___XXXX_,______XX,XXXXXXXX,X_______,
  _______X,XXXXXX__,__X_____,XX______,	  ___X_XX_,______X_,_______X,________,
  ___XXXXX,X_XX____,_XX_____,XX______,	  __X__XX_,__X_____,________,____X___,
  ___XX___,__XX____,XX______,XX______,	  __X__XX_,__XXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XX___X,X_______,XX______,	  _____XX_,__X_____,________,___XX___,
  ________,__X___X_,________,X_______,	  _____XX_,_XX_____,________,__X_____,
  ________,X_______,_______X,XX______,	  _____XX_,_XX_____,________,_XX_____,
  ________,XXXXXXXX,XXXXXXXX,XX______,	  _____XX_,____XXXX,XXXXXXXX,XXX_____,
  ________,XX______,_______X,X_______,	  _____XX_,________,___XX___,________,
  ________,XX______,_______X,X_______,	  _____XX_,________,___XX___,________,
  ________,XX______,_______X,X_______,	  _____XX_,________,___XX___,________,
  ________,XXXXXXXX,XXXXXXXX,X_______,	  _____XX_,________,___XX___,________,
  ________,XX______,_______X,X_______,	  _____XX_,________,___XX___,________,
  ________,XX______,_______X,X_______,	  _____XX_,________,___XX___,________,
  ________,XX______,_______X,X_______,	  _____XX_,________,___XX___,________,
  ________,XXXXXXXX,XXXXXXXX,X_______,	  _____XX_,_______X,X_XXX___,________,
  ________,XX______,_______X,X_______,	  _____XX_,________,_XXX____,________,
  ________,X_______,_______X,________,	  _____XX_,________,__X_____,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE unsigned char acResumeBtnStr[] = {
  ________,________,________,________,	________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ______X_,________,_X______,________,	  ________,__X_____,________,________,
  ______XX,________,_XX_____,________,	  ________,_XXXX___,________,________,
  ______XX,________,XX______,________,	  ________,_XX_____,________,__XX____,
  ______XX,________,XX______,________,	  ________,XXXXXXXX,XXXXXXXX,XXXXX___,
  ______XX,________,XX______,___XX___,	  ________,XX______,________,________,
  ______XX,__XXXXXX,XXXXXXXX,XXXXXX__,	  _______X,X_______,________,________,
  ______XX,X_______,XX______,________,	  ______XX,_X______,_______X,X_______,
  ______XX,XX______,X___X___,________,	  _____XX_,_XXXXXXX,XXXXXXXX,XX______,
  ___X__XX,_XX____X,X___XXX_,________,	  ____XX__,_XX_____,_______X,X_______,
  ___X__XX,__XX___X,X___XX__,________,	  ___X____,_XX_____,_______X,X_______,
  ___X__XX,__X____X,X___XX__,________,	  __X_____,_XX_____,_______X,X_______,
  __XX__XX,______XX,____XX__,________,	  ________,_XXXXXXX,XXXXXXXX,X_______,
  __XX__XX,______XX,____XX__,___X____,	  ________,_XX_____,_______X,X_______,
  __X___XX,______X_,_X__XX__,__XXX___,	  ________,_XX_____,_______X,X_______,
  ______XX,_____XX_,_X__XX__,_XXX____,	  ________,_XXXXXXX,XXXXXXXX,X_______,
  ______XX,_____XX_,XX__XXX_,_X______,	  ________,_XXX____,_______X,________,
  ______XX,_____X__,XX__XXX_,X_______,	  ________,___XXX__,______X_,________,
  ______XX,____XX_X,X__XX_XX,________,	  ________,__XX____,______XX,________,
  ______XX,____X___,___XX__X,________,	  ________,__XXXXXX,XXXXXXXX,X_______,
  ______XX,___X____,___XX__X,________,	  ________,_XX_X___,_____XX_,________,
  ______XX,___X____,__XX___X,________,	  ________,XX___X__,____XX__,________,
  ______XX,__X_____,__XX____,X_______,	  _______X,X_____X_,___XX___,________,
  ______XX,_X______,_XX_____,XX______,	  ______XX,______XX,_XXX____,________,
  ______XX,X_______,_X______,XX______,	  _____X__,_______X,XXX_____,________,
  ______XX,________,X_______,_XXX____,	  ____X___,______XX,XXX_____,________,
  ______XX,_______X,________,__XXX___,	  ________,____XXXX,__XXXX__,________,
  ______XX,_____XX_,________,__XXXXX_,	  ________,__XXX___,____XXXX,XX______,
  ______XX,____X___,________,___X____,	  _______X,XXX_____,______XX,XXXXXX__,
  ______X_,__XX____,________,________,	  ___XXXX_,________,________,__XX____,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE unsigned char acSetBtnStr[] = {
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  _____X__,________,________,________,	  ________,________,________,________,
  ______X_,_______X,______XX,________,	  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ______XX,_______X,XXXXXXXX,X_______,	  _____XX_,____XX__,__XX____,_XX_____,
  _______X,X______X,X_____XX,________,	  _____XX_,____XX__,__XX____,_XX_____,
  _______X,X______X,X_____XX,________,	  _____XX_,____XX__,__XX____,_XX_____,
  _______X,X______X,X_____XX,________,	  _____XX_,____XX__,__XX____,_XX_____,
  ________,_______X,X_____XX,________,	  _____XXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_______X,______XX,________,	  _____XX_,______X_,________,_XX_____,
  ________,______XX,______XX,________,	  ________,_______X,X_______,_X______,
  _______X,______XX,______XX,XXXXXX__,	  ________,_______X,________,_XX_____,
  __XXXXXX,X____XX_,_______X,XXXXXX__,	  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _______X,X___XX__,________,________,	  ________,______XX,________,________,
  _______X,X__XX___,________,XX______,	  _______X,______XX,______XX,________,
  _______X,X_X__XXX,XXXXXXXX,XXX_____,	  ________,XXXXXXXX,XXXXXXXX,X_______,
  _______X,X______X,________,XX______,	  ________,XX______,______XX,________,
  _______X,X_______,X______X,X_______,	  ________,XX______,______XX,________,
  _______X,X_______,X______X,X_______,	  ________,XXXXXXXX,XXXXXXXX,________,
  _______X,X_______,XX_____X,X_______,	  ________,XX______,______XX,________,
  _______X,X_______,_X____XX,________,	  ________,XX______,______XX,________,
  _______X,X___X___,_XX__XXX,________,	  ________,XX______,______XX,________,
  _______X,X__X____,__X__XX_,________,	  ________,XXXXXXXX,XXXXXXXX,________,
  _______X,X_XX____,__XXXX__,________,	  ________,XX______,______XX,________,
  _______X,XXX_____,___XXX__,________,	  ________,XX______,______XX,________,
  _______X,XX______,__XXXX__,________,	  ________,XXXXXXXX,XXXXXXXX,________,
  ______XX,X_______,_XX__XXX,________,	  ________,XX______,______XX,________,
  _______X,X______X,XX____XX,XXX_____,	  ________,XX______,______XX,____X___,
  ________,_____XXX,________,XXXXXXX_,	  ________,XX______,______XX,___XXX__,
  ________,___XXX__,________,__XX____,	  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,XXX_____,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE unsigned char acStopBtnStr[] = {
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  _______X,________,_X______,________,	  ________,________,X_______,________,
  _______X,XX______,__XX____,________,	  ________,________,XXX_____,________,
  _______X,X_______,__XXX___,________,	  ________,________,XX______,________,
  _______X,________,___X____,__XX____,	  ________,________,XX______,________,
  ______XX,__XXXXXX,XXXXXXXX,XXXXX___,	  ________,________,XX______,________,
  ______XX,________,________,________,	  ________,________,XX______,________,
  ______X_,_____X__,________,X_______,	  ________,________,XX______,________,
  _____XX_,______XX,XXXXXXXX,XX______,	  _______X,________,XX______,________,
  _____XXX,______X_,_______X,X_______,	  ________,XX______,XX______,________,
  ____XXX_,______X_,_______X,X_______,	  ________,XX______,XX______,__X_____,
  ____XXX_,______X_,_______X,X_______,	  ________,X_______,XX______,_XXX____,
  ___XXXX_,______XX,XXXXXXXX,X_______,	  ________,X_______,XXXXXXXX,X_______,
  ___X_XX_,______X_,_______X,________,	  ________,X_______,XX______,________,
  __X__XX_,__X_____,________,____X___,	  ________,X_______,XX______,________,
  __X__XX_,__XXXXXX,XXXXXXXX,XXXXXX__,	  ________,X_______,XX______,________,
  _____XX_,__X_____,________,___XX___,	  ________,X_______,XX______,________,
  _____XX_,_XX_____,________,__X_____,	  ________,X_______,XX______,________,
  _____XX_,_XX_____,________,_XX_____,	  ________,X_______,XX______,________,
  _____XX_,____XXXX,XXXXXXXX,XXX_____,	  ________,X_______,XX______,________,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,________,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,________,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,________,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,________,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,________,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,___XX___,
  _____XX_,________,___XX___,________,	  ________,X_______,XX______,__XXXX__,
  _____XX_,_______X,X_XXX___,________,	  __XXXXXX,_XXXXXXX,__XXXXXX,XX______,
  _____XX_,________,_XXX____,________,	  ________,________,________,________,
  _____XX_,________,__X_____,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE unsigned char acExitBtnStr[] = {
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________,
  ____X___,________,________,________,	  ________,_______X,X_______,________,
  _____X__,_____X__,________,XX______,	  ________,_______X,X_______,________,
  _____XXX,_____XXX,XXXXXXXX,XX______,	  ________,_______X,X_______,________,
  ______XX,_____XX_,________,XX______,	  ______X_,_______X,X_______,X_______,
  ______XX,_____XX_,________,XX______,	  ______XX,X______X,X_______,XXX_____,
  ________,_____XX_,________,XX______,	  ______XX,_______X,X_______,XX______,
  ________,_____XXX,XXXXXXXX,XX______,	  ______XX,_______X,X_______,XX______,
  ________,_____XX_,________,XX______,	  ______XX,_______X,X_______,XX______,
  ________,_____XX_,________,XX______,	  ______XX,_______X,X_______,XX______,
  _______X,_____XX_,________,XX______,	  ______XX,_______X,X_______,XX______,
  __XXXXXX,X____XX_,________,XX______,	  ______XX,_______X,X_______,XX______,
  ______XX,_____XXX,XXXXXXXX,XX______,	  ______XX,_______X,X_______,XX______,
  ______XX,_____XX_,________,X_X_____,	  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,_____XX_,________,__XX____,	  ________,_______X,X_______,XX______,
  ______XX,_____XX_,_X______,XXX_____,	  ________,_______X,X_______,________,
  ______XX,_____XX_,__XX___X,X_______,	  ________,_______X,X_______,________,
  ______XX,_____XX_,____XXX_,________,	  _____XX_,_______X,X_______,_XX_____,
  ______XX,_____XX_,_____XXX,________,	  _____XX_,_______X,X_______,_XXX____,
  ______XX,_____XX_,____X__X,XX______,	  _____XX_,_______X,X_______,_XX_____,
  ______XX,_____XX_,_XXX____,XXX_____,	  _____XX_,_______X,X_______,_XX_____,
  ______XX,_____XXX,XX______,_XXX____,	  _____XX_,_______X,X_______,_XX_____,
  _____XXX,X____XXX,________,__XX____,	  _____XX_,_______X,X_______,_XX_____,
  ___XXX__,_X____X_,________,___X____,	  _____XX_,_______X,X_______,_XX_____,
  __XXX___,__XX_X__,________,________,	  _____XX_,_______X,X_______,_XX_____,
  __XX____,___XXXX_,________,____XXX_,	  _____XX_,_______X,X_______,_XX_____,
  ________,____XXXX,XXXXXXXX,XXXXX___,	  ____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,________,_XXXXXXX,XXXX____,	  ________,________,________,_XX_____,
  ________,________,________,________,	  ________,________,________,_X______,
  ________,________,________,________,	  ________,________,________,________,
  ________,________,________,________,	  ________,________,________,________
};

static GUI_CONST_STORAGE GUI_BITMAP _bmStartCHN = {
  64,                   /* XSize */
  33,                   /* YSize */
  8,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acStartBtnStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmPauseCHN = {
  64,                   /* XSize */
  33,                   /* YSize */
  8,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acPauseBtnStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmResumeCHN = {
  64,                   /* XSize */
  33,                   /* YSize */
  8,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acResumeBtnStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmSetCHN = {
  64,                   /* XSize */
  33,                   /* YSize */
  8,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acSetBtnStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmStopCHN = {
  64,                   /* XSize */
  33,                   /* YSize */
  8,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acStopBtnStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

static GUI_CONST_STORAGE GUI_BITMAP _bmExitCHN = {
  64,                   /* XSize */
  33,                   /* YSize */
  8,                   /* BytesPerLine */
  1,                    /* BitsPerPixel */
  acExitBtnStr,          /* Pointer to picture data (indices) */
  &_PalCHNText          /* Pointer to palette */
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//    { FRAMEWIN_CreateIndirect, "EJE_SweepRobot_test_System", ID_FRAMEWIN_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
    { WINDOW_CreateIndirect, "EJE_SWRB_TEST_SYSTEM", ID_MAIN_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
//    { MULTIPAGE_CreateIndirect, "Multipage_Main", ID_MAIN_MULTIPAGE_0, 0, 0, 800, 460, 0, 0x0, 0 },
    { MULTIEDIT_CreateIndirect, "Msg Multiedit",  ID_MAIN_MULTIEDIT_MAIN, 10, 77, 440, 330, 0, 0x0, 0 },
    { PROGBAR_CreateIndirect,   "Progbar",        ID_MAIN_PROGBAR_MAIN, 10, 442, 440, 20, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "START", ID_MAIN_BUTTON_START, 700, 0, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SET",   ID_MAIN_BUTTON_SET,  700, 120, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SET SN",  ID_MAIN_BUTTON_SET_SN, 500, 120, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SET TIME",  ID_MAIN_BUTTON_SET_TIME, 600, 180, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "STOP",  ID_MAIN_BUTTON_STOP, 700, 240, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "EXIT",  ID_MAIN_BUTTON_EXIT, 700, 360, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, " ",  ID_MAIN_BUTTON_INDICATE, 420, 407, 30, 30, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxWheel",       ID_MAIN_CHECKBOX_WHEEL, 460, 17, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxBrush",       ID_MAIN_CHECKBOX_BRUSH, 460, 52, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxFan",         ID_MAIN_CHECKBOX_FAN, 460, 87, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxIFRD",        ID_MAIN_CHECKBOX_IFRD, 460, 122, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxCollision",   ID_MAIN_CHECKBOX_COLLISION, 460, 157, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxWheelFloat",  ID_MAIN_CHECKBOX_WHEEL_FLOAT, 460, 192, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxAshTray",     ID_MAIN_CHECKBOX_ASH_TRAY, 460, 227, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxUniWheel",    ID_MAIN_CHECKBOX_UNIWHEEL, 460, 262, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxKey",         ID_MAIN_CHECKBOX_KEY, 460, 297, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxIRDA",        ID_MAIN_CHECKBOX_IRDA, 460, 332, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxBuzzer",      ID_MAIN_CHECKBOX_BUZZER, 460, 367, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxRgbLed",      ID_MAIN_CHECKBOX_RGB_LED, 460, 402, 210, 25, 0, 0x0, 0 },
    { CHECKBOX_CreateIndirect,  "cbxCharge",      ID_MAIN_CHECKBOX_CHARGE, 460, 437, 210, 25, 0, 0x0, 0 },
//    { GRAPH_CreateIndirect, "Graph", ID_MAIN_GRAPH_0, 10, 310, 440, 100, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "EditU1", ID_MAIN_EDIT_U1, 10, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU2", ID_MAIN_EDIT_U2, 65, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU3", ID_MAIN_EDIT_U3, 120, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU4", ID_MAIN_EDIT_U4, 175, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU5", ID_MAIN_EDIT_U5, 230, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU6", ID_MAIN_EDIT_U6, 285, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU7", ID_MAIN_EDIT_U7, 340, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditU8", ID_MAIN_EDIT_U8, 395, 17, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD1", ID_MAIN_EDIT_D1, 10, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD2", ID_MAIN_EDIT_D2, 65, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD3", ID_MAIN_EDIT_D3, 120, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD4", ID_MAIN_EDIT_D4, 175, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD5", ID_MAIN_EDIT_D5, 230, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD6", ID_MAIN_EDIT_D6, 285, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD7", ID_MAIN_EDIT_D7, 340, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditD8", ID_MAIN_EDIT_D8, 395, 47, 55, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditSN", ID_MAIN_EDIT_SN, 190, 407, 230, 30, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "EditDate", ID_MAIN_EDIT_DATE, 10, 407, 180, 30, 0, 0x64, 0 },
};

static const GUI_WIDGET_CREATE_INFO _RgbLEDTestDialogCreate[] = {
    { FRAMEWIN_CreateIndirect, "RGB LED TEST", ID_MAIN_FRAMEWIN_RGB_LED, 0, 0, 440, 210, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "OK", ID_MAIN_BUTTON_RGB_LED_OK, 60, 100, 120, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "ERROR",   ID_MAIN_BUTTON_RGB_LED_ERR,  260, 100, 120, 60, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "RGB LED TEST", ID_MAIN_TEXT_RGB_LED, 68, 17, 308, 65, 0, 0x64, 0 },
};

static const GUI_WIDGET_CREATE_INFO _BuzzerTestDialogCreate[] = {
    { FRAMEWIN_CreateIndirect, "BUZZER TEST", ID_MAIN_FRAMEWIN_BUZZER, 0, 0, 440, 210, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "OK", ID_MAIN_BUTTON_BUZZER_OK, 60, 100, 120, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "ERROR",   ID_MAIN_BUTTON_BUZZER_ERR,  260, 100, 120, 60, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "BUZZER TEST", ID_MAIN_TEXT_BUZZER, 68, 17, 308, 65, 0, 0x64, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetFocussable(hItem, DISABLE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
}

static void Checkbox_Init(WM_HWIN hItem)
{
    CHECKBOX_SetFont(hItem, GUI_FONT_20B_ASCII);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_Simple);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    u32     i;

    switch (pMsg->MsgId) {
        case WM_INIT_DIALOG:
            //
            // Initialization of 'START'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_START);
            Button_Init(hItem);
            BUTTON_SetText(hItem, " ");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_MAIN_BUTTON_START, &_bmStartCHN, 18, 43);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTBLUE);
            BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTBLUE);
            //
            // Initialization of 'SET'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_SET);
            Button_Init(hItem);
            BUTTON_SetText(hItem, " ");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_MAIN_BUTTON_SET, &_bmSetCHN, 18, 43);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTCYAN);
            //
            // Initialization of 'SET SN'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_SET_SN);
            Button_Init(hItem);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTCYAN);
            WM_HideWin(hItem);
            //
            // Initialization of 'SET TIME'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_SET_TIME);
            Button_Init(hItem);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTCYAN);
            BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTCYAN);
            WM_HideWin(hItem);
            //
            // Initialization of 'STOP'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_STOP);
            Button_Init(hItem);
            BUTTON_SetText(hItem, " ");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_MAIN_BUTTON_STOP, &_bmStopCHN, 18, 43);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTRED);
            BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTRED);
            //
            // Initialization of 'EXIT'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_EXIT);
            Button_Init(hItem);
            BUTTON_SetText(hItem, " ");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_MAIN_BUTTON_EXIT, &_bmExitCHN, 18, 43);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTGREEN);
            BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTGREEN);
            //
            // Initialization of 'Indicate'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_INDICATE);
            WM_BringToTop(hItem);
            BUTTON_SetSkinClassic(hItem);
            WIDGET_SetEffect(hItem, &WIDGET_Effect_Simple);
            Button_Set_unPressedBkColor(hWin_SWRB_MAIN,ID_MAIN_BUTTON_INDICATE, GUI_LIGHTGRAY);
            Button_Set_Text(hWin_SWRB_MAIN, ID_MAIN_BUTTON_INDICATE, " ");
            BUTTON_SetFocussable(hItem, 0);
            //
            // Initialization of 'Msg Multiedit'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_MULTIEDIT_MAIN);
            MULTIEDIT_SetText(hItem, "Waiting for Start");
            MULTIEDIT_SetFont(hItem, GUI_FONT_16_ASCII);
            MULTIEDIT_SetAutoScrollV(hItem,1);
            MULTIEDIT_SetWrapWord(hItem);
            MULTIEDIT_SetBufferSize(hItem, 2048);
            WM_DisableWindow(hItem);
            //
            // Initialization of 'cbxWheel Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_WHEEL);
            CHECKBOX_SetText(hItem, "WHEEL");
            CHECKBOX_SetDefaultSkinClassic();
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxSBrush Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_BRUSH);
            CHECKBOX_SetText(hItem, "BRUSH");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxFan Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_FAN);
            CHECKBOX_SetText(hItem, "FAN");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxIFRD Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_IFRD);
            CHECKBOX_SetText(hItem, "IFRD");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxCollision Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_COLLISION);
            CHECKBOX_SetText(hItem, "COLLISION");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxWheelFloat Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_WHEEL_FLOAT);
            CHECKBOX_SetText(hItem, "WHEEL FLOAT");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxAshTray Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_ASH_TRAY);
            CHECKBOX_SetText(hItem, "ASH TRAY");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxUniWheel Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_UNIWHEEL);
            CHECKBOX_SetText(hItem, "UNIWHEEL");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxKey Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_KEY);
            CHECKBOX_SetText(hItem, "KEY");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxIRDA Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_IRDA);
            CHECKBOX_SetText(hItem, "IRDA");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxBuzzer Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_BUZZER);
            CHECKBOX_SetText(hItem, "BUZZER");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxRgbLED Test'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_RGB_LED);
            CHECKBOX_SetText(hItem, "RGB LED");
            Checkbox_Init(hItem);
            //
            // Initialization of 'cbxCharge'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_CHECKBOX_CHARGE);
            CHECKBOX_SetText(hItem, "CHARGE");
            Checkbox_Init(hItem);
            //
            // Initialization of 'Edit'
            //
            for(i=ID_MAIN_EDIT_U1;i<=ID_MAIN_EDIT_D8;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                EDIT_SetFont(hItem, &GUI_Font20_ASCII);
                EDIT_SetDecMode(hItem, 0, 0, 65536, 0, GUI_EDIT_NORMAL);
                EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            //
            // Initialization of 'EditDate'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_EDIT_DATE);
            EDIT_SetFont(hItem, &GUI_Font20_ASCII);
            EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            //
            // Initialization of 'EditSN'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_EDIT_SN);
            EDIT_SetFont(hItem, &GUI_Font20_ASCII);
            EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            //
            // Initialization of 'PROGBAR'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_PROGBAR_MAIN);
            PROGBAR_SetSkinClassic(hItem);
            WIDGET_SetEffect(hItem, &WIDGET_Effect_None);

            WM_HideWin(pMsg->hWin);
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
            case ID_MAIN_BUTTON_START: // Notifications sent by 'START'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        SweepRobot_PCBTestStartProc();
                        break;
                }
                break;
            case ID_MAIN_BUTTON_SET: // Notifications sent by 'SET'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        SweepRobot_PCBTestSetProc();
                        break;
                }
                break;
            case ID_MAIN_BUTTON_SET_SN:
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
//                        SweepRobot_PCBTestSetProc();
                        break;
                }
                break;
            case ID_MAIN_BUTTON_STOP: // Notifications sent by 'STOP'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        SweepRobot_PCBTestStopProc();
                        break;
                }
                break;
            case ID_MAIN_BUTTON_EXIT: // Notifications sent by 'EXIT'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        SweepRobot_PCBTestExitProc();
                        break;
                }
                break;
            case ID_MAIN_MULTIEDIT_MAIN: // Notifications sent by 'Msg Multiedit'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_WHEEL: // Notifications sent by 'cbxWheel Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_WHEEL, SWRB_WHEEL_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_BRUSH: // Notifications sent by 'cbxBrush Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_BRUSH, SWRB_BRUSH_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_FAN: // Notifications sent by 'cbxFan Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_FAN, SWRB_FAN_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_IFRD: // Notifications sent by 'cbxIFRD Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_IFRD, SWRB_IFRD_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_COLLISION: // Notifications sent by 'cbxCollision Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_COLLISION, SWRB_COLLISION_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_WHEEL_FLOAT: // Notifications sent by 'cbxWheelFloat Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                            break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_WHEEL_FLOAT, SWRB_WHEEL_FLOAT_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_ASH_TRAY: // Notifications sent by 'cbxAshTray Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_ASH_TRAY, SWRB_ASH_TRAY_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_UNIWHEEL: // Notifications sent by 'cbxUniWheel Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_UNIWHEEL, SWRB_UNIWHEEL_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_KEY: // Notifications sent by 'cbxKey Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_KEY, SWRB_KEY_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_IRDA: // Notifications sent by 'cbxIRDA Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_IRDA, SWRB_IRDA_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_BUZZER: // Notifications sent by 'cbxBuzzer Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_BUZZER, SWRB_BUZZER_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_RGB_LED: // Notifications sent by 'cbxRgbLed Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_RGB_LED, SWRB_RGB_LED_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_CHECKBOX_CHARGE: // Notifications sent by 'cbxCharge Test'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        SWRB_TestCheckboxStateGet(pMsg->hWin, ID_MAIN_CHECKBOX_CHARGE, SWRB_CHARGE_TEST_TASK_PRIO);
                        break;
                }
                break;
            case ID_MAIN_EDIT_SN:
                switch(NCode){
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        break;
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        break;
                }
                break;
            case ID_MAIN_PROGBAR_MAIN:
                switch(NCode) {
                    case WM_NOTIFICATION_VALUE_CHANGED:
                        break;
                }
                break;
            }
            break;
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

static void _cbRgbLedDialog(WM_MESSAGE * pMsg){
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    u8      state;
    
    switch(pMsg->MsgId){
        case WM_INIT_DIALOG:
            
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_RGB_LED_OK);
            BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);

            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_RGB_LED_ERR);
            BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
        
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_TEXT_RGB_LED);
            TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
            TEXT_SetText(hItem, "RGB LED TEST");
            TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            TEXT_SetTextColor(hItem, GUI_RED);
            
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
                case ID_MAIN_BUTTON_RGB_LED_OK: // Notifications sent by 'RGB LED OK'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            state = RGB_LED_TestValidCntGet();
                            RGB_LED_TestRgbStateSet(state, 1);
                            if(state == 3)
                                WM_HideWin(pMsg->hWin);
                            OSTaskResume(gSwrbTestRuningTaskPrio);
                            break;
                    }
                    break;
                case ID_MAIN_BUTTON_RGB_LED_ERR: // Notifications sent by 'RGB LED ERR'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            state = RGB_LED_TestValidCntGet();
                            RGB_LED_TestRgbStateSet(state, 0);
                            if(state == 3)
                                WM_HideWin(pMsg->hWin);
                            OSTaskResume(gSwrbTestRuningTaskPrio);
                            break;
                    }
                    break;
            }
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

static void _cbBuzzerDialog(WM_MESSAGE * pMsg){
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    
    switch(pMsg->MsgId){
        case WM_INIT_DIALOG:

            hItem = WM_GetDialogItem(pMsg->hWin,ID_MAIN_FRAMEWIN_BUZZER);
            WM_AttachWindowAt(hItem, hWin_SWRB_MAIN, 10, 77);
        
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_BUZZER_OK);
            BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);

            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_BUTTON_BUZZER_ERR);
            BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
        
            hItem = WM_GetDialogItem(pMsg->hWin, ID_MAIN_TEXT_BUZZER);
            TEXT_SetFont(hItem, GUI_FONT_32_ASCII);
            TEXT_SetText(hItem, "BUZZER TEST");
            TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            TEXT_SetTextColor(hItem, GUI_BLACK);
        
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
                case ID_MAIN_BUTTON_BUZZER_OK: // Notifications sent by 'BUZZER OK'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:

                            break;
                        case WM_NOTIFICATION_RELEASED:
                            BUZZER_TestStateSet(1);
                            BUZZER_TestValidFlagSet(1);
                            WM_HideWin(hWin_SWRB_BUZZER);
                            break;
                    }
                    break;
                case ID_MAIN_BUTTON_BUZZER_ERR: // Notifications sent by 'BUZZER ERROR'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:

                            break;
                        case WM_NOTIFICATION_RELEASED:
                            BUZZER_TestStateSet(0);
                            BUZZER_TestValidFlagSet(1);
                            WM_HideWin(hWin_SWRB_BUZZER);
                            break;
                    }
                    break;
            }
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateEJE_SWRB_TEST_MainDLG
*/
WM_HWIN CreateEJE_SWRB_TEST_MainDLG(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

WM_HWIN CreateRGB_LED_TestDLG(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_RgbLEDTestDialogCreate, GUI_COUNTOF(_RgbLEDTestDialogCreate), _cbRgbLedDialog, hWin_SWRB_MAIN, 180, 135);
    return hWin;
}

WM_HWIN CreateBUZZER_TestDLG(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_BuzzerTestDialogCreate, GUI_COUNTOF(_BuzzerTestDialogCreate), _cbBuzzerDialog, hWin_SWRB_MAIN, 180, 135);
    return hWin;
}


void Button_Set_Text(WM_HWIN hWin, int buttonId, char *str)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, buttonId);
    BUTTON_SetText(hItem, str);
}

void Button_Set_unPressedBkColor(WM_HWIN hWin, int buttonId, GUI_COLOR color)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, buttonId);
    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, color);
}

void Button_SetEnable(WM_HWIN hWin, int buttonId)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, buttonId);
    WM_EnableWindow(hItem);
}

void Button_SetDisable(WM_HWIN hWin, int buttonId)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, buttonId);
    WM_DisableWindow(hItem);
}

void BUTTON_Set_Bitmap_Ex(WM_HWIN hWin, int buttonId, const GUI_BITMAP *pBitmap, int x, int y)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, buttonId);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_DISABLED, pBitmap, x, y);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_PRESSED, pBitmap, x, y);
    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED, pBitmap, x, y);
}

void BUTTON_Disp_Start_CHNStr(WM_HWIN hWin, int buttonId, int x, int y)
{
    BUTTON_Set_Bitmap_Ex(hWin, buttonId, &_bmStartCHN, x, y);
}

void BUTTON_Disp_Pause_CHNStr(WM_HWIN hWin, int buttonId, int x, int y)
{
    BUTTON_Set_Bitmap_Ex(hWin, buttonId, &_bmPauseCHN, x, y);
}

void BUTTON_Disp_Resume_CHNStr(WM_HWIN hWin, int buttonId, int x, int y)
{
    BUTTON_Set_Bitmap_Ex(hWin, buttonId, &_bmResumeCHN, x, y);
}

void BUTTON_Disp_Set_CHNStr(WM_HWIN hWin, int buttonId, int x, int y)
{
    BUTTON_Set_Bitmap_Ex(hWin, buttonId, &_bmSetCHN, x, y);
}

void BUTTON_Disp_Stop_CHNStr(WM_HWIN hWin, int buttonId, int x, int y)
{
    BUTTON_Set_Bitmap_Ex(hWin, buttonId, &_bmStopCHN, x, y);
}

void BUTTON_Disp_Exit_CHNStr(WM_HWIN hWin, int buttonId, int x, int y)
{
    BUTTON_Set_Bitmap_Ex(hWin, buttonId, &_bmExitCHN, x, y);
}

void Progbar_Set_Value(int progbarValue)
{
	WM_HWIN hItem;
	hItem = WM_GetDialogItem(hWin_SWRB_MAIN, ID_MAIN_PROGBAR_0);
	PROGBAR_SetValue(hItem, progbarValue);
}

void Progbar_Set_Percent(void)
{
    Progbar_Set_Value( (float)(gSwrbTestValidTaskCntTotal-gSwrbTestValidTaskCnt) / (float)(gSwrbTestValidTaskCntTotal)*100 );
}

void Edit_Set_Value(int editId, long editValue)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, editId);
    EDIT_SetValue(hItem, editValue);
}

void Edit_Set_Text(WM_HWIN hWin, int editId, char *str)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, editId);
    EDIT_SetText(hItem, str);
}

void Edit_Clear(void)
{
    int i;
    
    for(i=ID_MAIN_EDIT_1;i<ID_MAIN_EDIT_SN;i++){
        Edit_Set_Value(i, 0);
    }
}

void Text_Set_Text(WM_HWIN hWin, int textId, char *str)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, textId);
    TEXT_SetText(hItem, str);
}
void Text_Set_Color(WM_HWIN hWin, int textId, GUI_COLOR color)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, textId);
    TEXT_SetTextColor(hItem, color);
}

void Checkbox_Set_Text(WM_HWIN hWin, int checkboxId, char *string)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, checkboxId);
    CHECKBOX_SetText(hItem, string);
}

int Checkbox_Get_State(int checkboxId)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, checkboxId);
    return(CHECKBOX_GetState(hItem));
}

void Checkbox_Set_State(WM_HWIN hWin, int checkboxId, unsigned int checkboxState)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, checkboxId);
    CHECKBOX_SetState(hItem, checkboxState);
}

void SWRB_TestCheckboxStateSet(u8 stateNum)
{
    int i;
    WM_HWIN hItem;
    
    for(i=ID_MAIN_CHECKBOX_WHEEL;i<ID_MAIN_CHECKBOX_BOUND;i++){
        hItem = WM_GetDialogItem(hWin_SWRB_MAIN, i);
        CHECKBOX_SetState(hItem, stateNum);
    }
}

void SWRB_TestCheckboxEnable(void)
{
    int i;
    WM_HWIN hItem;
    
    for(i=ID_MAIN_CHECKBOX_WHEEL;i<ID_MAIN_CHECKBOX_BOUND;i++){
        hItem = WM_GetDialogItem(hWin_SWRB_MAIN, i);
        WM_EnableWindow(hItem);
    }
}

void SWRB_TestCheckboxDisable(void)
{
    int i;
    WM_HWIN hItem;
    
    for(i=ID_MAIN_CHECKBOX_WHEEL;i<ID_MAIN_CHECKBOX_BOUND;i++){
        hItem = WM_GetDialogItem(hWin_SWRB_MAIN, i);
        WM_DisableWindow(hItem);
    }
}

void SWRB_TestCheckboxStateGet(WM_HWIN hWin, int id, int taskPrio){
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, id);
    if(gSwrbTestMode == SWRB_TEST_MODE_IDLE){
        if(CHECKBOX_GetState(hItem)){
            gSwrbTestValidTaskCnt++;
            gSwrbTestValidTaskCntTotal++;
        }else{
            gSwrbTestValidTaskCnt--;
            gSwrbTestValidTaskCntTotal--;
        }
    }
}

void Checkbox_Set_Text_Color(int checkboxId, GUI_COLOR checkboxtextcolor)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, checkboxId);
    CHECKBOX_SetTextColor(hItem, checkboxtextcolor);
}

void Checkbox_Set_TextAlign(int checkboxId, int align)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, checkboxId);
    CHECKBOX_SetTextAlign(hItem, align);
}

void Checkbox_Set_Back_Color(int checkboxId, GUI_COLOR checkboxbkcolor)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, checkboxId);
    CHECKBOX_SetBkColor(hItem, checkboxbkcolor);
}

void Checkbox_Set_Box_Back_Color(WM_HWIN hWin, int checkboxId, GUI_COLOR boxBkColor, int Index)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin, checkboxId);
    CHECKBOX_SetBoxBkColor(hItem, boxBkColor, Index);
}

void MULTIEDIT_Set_Buffer_Size(int size)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, ID_MAIN_MULTIEDIT_MAIN);
    MULTIEDIT_SetBufferSize(hItem, size);
}

void MultiEdit_Set_Text(WM_HWIN hWin, int multiEditId, char *s)
{
	WM_HWIN hItem;
    
	hItem = WM_GetDialogItem(hWin, multiEditId);
	MULTIEDIT_SetText(hItem, s);
}

void MultiEdit_Add_Text(WM_HWIN hWin, int multiEditId, char *s)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(hWin, multiEditId);
    MULTIEDIT_AddText(hItem, s);
}

void MultiEdit_Set_Text_Color(GUI_COLOR multieditTextColor)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(hWin_SWRB_MAIN, ID_MAIN_MULTIEDIT_0);
    MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_EDIT, multieditTextColor);
}

GRAPH_DATA_Handle Graph_Data_YT_Create(GUI_COLOR color, u32 maxNumItems, int16_t *pData, u32 numItems)
{
    GRAPH_DATA_Handle hGraphData;
    hGraphData = GRAPH_DATA_YT_Create(color, maxNumItems, pData, numItems);
    return hGraphData;
}

void SweepRobot_MainTestIndicateBtnToggle(void)
{
    if(++gMainDLGIndicateFlag%2){
        Button_Set_unPressedBkColor(hWin_SWRB_MAIN, ID_MAIN_BUTTON_INDICATE, GUI_DARKGREEN);
    }else{
        Button_Set_unPressedBkColor(hWin_SWRB_MAIN, ID_MAIN_BUTTON_INDICATE, GUI_LIGHTGRAY);
    }
}

void SWRB_WM_EnableWindow(WM_HWIN hWin, int id)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(hWin, id);
    WM_EnableWindow(hItem);
}

void SWRB_WM_DisableWindow(WM_HWIN hWin, int id)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(hWin, id);
    WM_DisableWindow(hItem);
}

/*************************** End of file ****************************/
