/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"

#include "sweeprobot_testing.h"
#include "malloc.h"
#include <stdio.h>

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define IS_NUMPAD_BUTTON_ID_NUM(ID)       ( ( ID == ID_NUMPAD_BUTTON_NUM0 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM1 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM2 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM3 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM4 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM5 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM6 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM7 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM8 ) ||\
                                            ( ID == ID_NUMPAD_BUTTON_NUM9 ) )

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "NumPad", ID_NUMPAD_FRAMEWIN_MAIN, 0, 0, 400, 300, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_NUMPAD_EDIT_MAIN, 35, 15, 330, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "btn0", ID_NUMPAD_BUTTON_NUM0, 305, 210, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn1", ID_NUMPAD_BUTTON_NUM1, 35, 70, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn2", ID_NUMPAD_BUTTON_NUM2, 125, 70, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn3", ID_NUMPAD_BUTTON_NUM3, 215, 70, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn4", ID_NUMPAD_BUTTON_NUM4, 35, 140, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn5", ID_NUMPAD_BUTTON_NUM5, 125, 140, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn6", ID_NUMPAD_BUTTON_NUM6, 215, 140, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn7", ID_NUMPAD_BUTTON_NUM7, 35, 210, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn8", ID_NUMPAD_BUTTON_NUM8, 125, 210, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btn9", ID_NUMPAD_BUTTON_NUM9, 215, 210, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnDel", ID_NUMPAD_BUTTON_DEL, 305, 140, 60, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnOK", ID_NUMPAD_BUTTON_OK, 305, 70, 60, 50, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    int     i;
    char    *str;

    switch (pMsg->MsgId) {
        case WM_INIT_DIALOG:
            //
            // Initialization of 'Edit'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_NUMPAD_EDIT_MAIN);
            EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
            EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            EDIT_SetInsertMode(hItem, ENABLE);
            EDIT_SetMaxLen(hItem, 10);
            //
            // Initialization of 'Button'
            //
            for(i=ID_NUMPAD_BUTTON_NUM0;i<ID_NUMPAD_BUTTON_BOUND;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
                if(i == ID_NUMPAD_BUTTON_OK){
                    BUTTON_SetText(hItem, "OK");
                }else if (i == ID_NUMPAD_BUTTON_DEL){
                    BUTTON_SetText(hItem, "Del");
                }else{
                    str = mymalloc(SRAMIN, sizeof(char)*2);
                    sprintf(str, "%d", i-ID_NUMPAD_BUTTON_NUM0);
                    BUTTON_SetText(hItem, str);
                    myfree(SRAMIN, str);
                }
            }
            /* Hide Dialog when create */
            WM_HideWin(pMsg->hWin);
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;

            if(IS_NUMPAD_BUTTON_ID_NUM(Id)){
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                        break;
                    case WM_NOTIFICATION_RELEASED:
                        hItem = WM_GetDialogItem(pMsg->hWin, ID_NUMPAD_EDIT_MAIN);
                        EDIT_AddKey(hItem, '0' + (Id-ID_NUMPAD_BUTTON_NUM0) );
                        break;
                    }
                    break;
            }else{
                switch(Id) {
                    case ID_NUMPAD_BUTTON_OK: // Notifications sent by 'btnOK'
                        switch(NCode) {
                            case WM_NOTIFICATION_CLICKED:
                                break;
                            case WM_NOTIFICATION_RELEASED:
                                SweepRobot_PCBTestNumPadOKProc();
                                break;
                        }
                        break;
                    case ID_NUMPAD_BUTTON_DEL: // Notifications sent by 'btnDel'
                        switch(NCode) {
                            case WM_NOTIFICATION_CLICKED:
                                break;
                            case WM_NOTIFICATION_RELEASED:
                                hItem = WM_GetDialogItem(pMsg->hWin, ID_NUMPAD_EDIT_MAIN);
                                EDIT_AddKey(hItem, '\b');
                                break;
                        }
                        break;
                    case ID_NUMPAD_EDIT_MAIN: // Notifications sent by 'Edit'
                        switch(NCode) {
                            case WM_NOTIFICATION_CLICKED:

                                break;
                            case WM_NOTIFICATION_RELEASED:

                                break;
                            case WM_NOTIFICATION_VALUE_CHANGED:

                                break;
                        }
                        break;
                }
            }
            break;
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_NUMPAD;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateNumPadDLG
*/

WM_HWIN CreateNumPadDLG(void) {
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_SWRB_MAIN, 300, 90);
    return hWin;
}

void SWRB_NumpadInputNumGet(char *numStr)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(hWin_SWRB_NUMPAD, ID_NUMPAD_EDIT_MAIN);
    EDIT_GetText(hItem, numStr, EDIT_GetNumChars(hItem)+1);
}

/*************************** End of file ****************************/
