/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_SLAMDLG.h"

#include "EJE_SWRB_TEST_DLG_Conf.h"
#include "GUI.h"

#include "sweeprobot_testing.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

typedef void (*SLAMCbFunc_t)(void);

static SLAMCbFunc_t SLAMWMPaintCb;

#define SWRB_SLAM_WM_PAINT_CB_REG(f)    do{SLAMWMPaintCb=f;}while(0)
#define SWRB_SLAM_WM_PAINT_CB_DEREG()   do{SLAMWMPaintCb=NULL;}while(0)

#define SWRB_SLAM_START_X_POS   350
#define SWRB_SLAM_START_Y_POS   240
#define SWRB_SLAM_START_ANGLE   0

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static GUI_POINT pPolygonRobot[] = {
                                     {0,30},
                                     {10,30},
                                     {5,0}
                                   };
static int gTraceNum = 0;
static GUI_POINT pPolygonTrace[100] = { 
                                        {0,0} 
                                       };
static GUI_POINT pPolygonTraceBuf[] = { 
                                        {0,0} 
                                      };

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "winSLAM", ID_SLAM_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SLAM Monitor", ID_SLAM_TEXT_TITLE, 0, 0, 150, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "btnStart", ID_SLAM_BUTTON_START, 700, 0, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnSet", ID_SLAM_BUTTON_SET, 700, 120, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnStop", ID_SLAM_BUTTON_STOP, 700, 240, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnExit", ID_SLAM_BUTTON_EXIT, 700, 360, 100, 120, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_SLAM_PROGBAR_MAIN, 100, 450, 500, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "editXpos", ID_SLAM_EDIT_XPOS, 150, 415, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "textXpos", ID_SLAM_TEXT_XPOS, 100, 415, 50, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "editYpos", ID_SLAM_EDIT_YPOS, 300, 415, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "textYpos", ID_SLAM_TEXT_YPOS, 250, 415, 50, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_SLAM_EDIT_RVALUE, 450, 415, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "textRValue", ID_SLAM_TEXT_RVALUE, 400, 415, 50, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    BUTTON_SetSkinClassic(hItem);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_Simple);
}

static void SLAM_WMPaint(void)
{
    int i;
    
    // Initialization of user widget
    GUI_SetColor(GUI_BLUE);
    GUI_DrawRect(100, 50, 600, 400);
    GUI_SetColor(GUI_RED);
    
    /* move the robot polygon */
    if(pPolygonRobot[0].y < 400-SWRB_SLAM_START_Y_POS){
        for(i=0;i<3;i++){
            pPolygonRobot[i].y += 2;
        }
    }else{
        for(i=0;i<3;i++){
            pPolygonRobot[i].x -= 2;
        }
    }
    GUI_FillPolygon(pPolygonRobot, 3, SWRB_SLAM_START_X_POS, SWRB_SLAM_START_Y_POS);

    pPolygonTrace[gTraceNum].x = pPolygonRobot[0].x;
    pPolygonTrace[gTraceNum].y = pPolygonRobot[0].y;
    gTraceNum++;
    GUI_SetColor(GUI_GRAY);
    GUI_DrawPolyLine(pPolygonTrace, gTraceNum, SWRB_SLAM_START_X_POS, SWRB_SLAM_START_Y_POS);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_TEXT_TITLE);
    TEXT_SetFont(hItem, GUI_FONT_24_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "SLAM Monitor");
    //
    // Initialization of 'btnStart'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_BUTTON_START);
    Button_Init(hItem);
    BUTTON_SetText(hItem, "Start");
    //
    // Initialization of 'btnSet'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_BUTTON_SET);
    Button_Init(hItem);
    BUTTON_SetText(hItem, "Set");
    //
    // Initialization of 'btnStop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_BUTTON_STOP);
    Button_Init(hItem);
    BUTTON_SetText(hItem, "Stop");
    //
    // Initialization of 'btnExit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_BUTTON_EXIT);
    Button_Init(hItem);
    BUTTON_SetText(hItem, "Exit");
    //
    // Initialization of 'editXpos'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_EDIT_XPOS);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'textXpos'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_TEXT_XPOS);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Xpos");
    //
    // Initialization of 'editYpos'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_EDIT_YPOS);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'textYpos'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_TEXT_YPOS);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "Ypos");
    //
    // Initialization of 'editRvalue'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_EDIT_RVALUE);
    EDIT_SetText(hItem, "123");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'textRValue'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLAM_TEXT_RVALUE);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "RValue");

    /* Hide Window when created */
    WM_HideWin(pMsg->hWin);
    
    break;
  case WM_PAINT:
        if(SLAMWMPaintCb != NULL)
            SLAMWMPaintCb();
        return;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SLAM_BUTTON_START: // Notifications sent by 'btnStart'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_SLAMStartProc();
        break;
      }
      break;
    case ID_SLAM_BUTTON_SET: // Notifications sent by 'btnSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_SLAMSetProc();
        break;
      }
      break;
    case ID_SLAM_BUTTON_STOP: // Notifications sent by 'btnStop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_SLAMStopProc();
        break;
      }
      break;
    case ID_SLAM_BUTTON_EXIT: // Notifications sent by 'btnExit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_SLAMExitProc();
        break;
      }
      break;
      
    }
    break;

  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_SLAM;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSLAMDLG
*/
WM_HWIN CreateEJE_SWRB_TEST_SLAMDLG(void)
{
  WM_HWIN hWin;

  SWRB_SLAM_WM_PAINT_CB_REG(SLAM_WMPaint);
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

void SWRB_ROTATE_Robot(float angle)
{
    GUI_RotatePolygon(pPolygonRobot, pPolygonRobot, 3, angle);
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
