/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "sweeprobot_testing.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
WM_HWIN hWinEJE_SWRB_TEST_SETTING;
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//    { FRAMEWIN_CreateIndirect, "SettingDLG", ID_SET_FRAMEWIN, 0, 0, 800, 480, 0, 0x0, 0 },
    { WINDOW_CreateIndirect, "TEST SETTING", ID_SET_WINDOW, 0, 0, 800, 480, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Set Serial Number", ID_SET_TEXT_0, 20, 50, 680, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "confirm", ID_SET_BUTTON_CONFIRM, 700, 0, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "check", ID_SET_BUTTON_CHECK, 700, 120, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "reset", ID_SET_BUTTON_RESET, 700, 240, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "cancel", ID_SET_BUTTON_CANCEL, 700, 360, 100, 120, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwYear", ID_SET_LISTWHEEL_YEAR, 20, 100, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwMonth", ID_SET_LISTWHEEL_MONTH, 130, 100, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwDay", ID_SET_LISTWHEEL_DAY, 240, 100, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN1", ID_SET_LISTWHEEL_SN1, 350, 100, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN2", ID_SET_LISTWHEEL_SN2, 460, 100, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN3", ID_SET_LISTWHEEL_SN3, 570, 100, 110, 230, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "editComb", ID_SET_EDIT_COMB, 20, 390, 660, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editYear", ID_SET_EDIT_YEAR, 20, 350, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editMonth", ID_SET_EDIT_MONTH, 130, 350, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editDay", ID_SET_EDIT_DAY, 240, 350, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN1", ID_SET_EDIT_SN1, 350, 350, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN2", ID_SET_EDIT_SN2, 460, 350, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN3", ID_SET_EDIT_SN3, 570, 350, 110, 40, 0 ,0x0, 0 },
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetFocussable(hItem, DISABLE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
}

static void ListWheel_Init(WM_HWIN hItem)
{
    LISTWHEEL_SetFont(hItem, GUI_FONT_32_ASCII);
    LISTWHEEL_SetDeceleration(hItem, 10);
    LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTWHEEL_SetSnapPosition(hItem, 115);
    LISTWHEEL_SetBkColor(hItem, LISTWHEEL_CI_SEL, GUI_LIGHTRED);
    LISTWHEEL_SetBkColor(hItem, LISTWHEEL_CI_UNSEL, GUI_BLACK);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, GUI_WHITE);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, GUI_GRAY);
}

static void ListWheel_GetText(WM_HWIN *hWin,int id, char *str)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *lwBuf;
   
    hItem = WM_GetDialogItem(*hWin, id);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    mymemcpy(str,lwBuf,1);
    myfree(SRAMIN, lwBuf);
}

static void SerialNum_Comb(WM_HWIN *hWin, int id, char *dest_SNumStr)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *lwBuf;
    
    hItem = WM_GetDialogItem(*hWin, id);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    dest_SNumStr = strcat(dest_SNumStr, lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void ListWheel_TestDataFilePathGen(WM_HWIN *hWin)
{
    WM_HWIN hItem;
    char    *lwBuf;
    FRESULT flErr;

    flErr = flErr;
    
    *gSwrbTestDataFilePath = 0;

    lwBuf = "0:/";
    gSwrbTestDataFilePath = strcat(gSwrbTestDataFilePath, lwBuf);

    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_YEAR, gSwrbTestDataFilePath);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_MONTH, gSwrbTestDataFilePath);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_DAY, gSwrbTestDataFilePath);
    
    flErr = f_mkdir(gSwrbTestDataFilePath);
    
    *gSwrbTestDataFilePath = 0;
    
    lwBuf = "0:/";
    gSwrbTestDataFilePath = strcat(gSwrbTestDataFilePath, lwBuf);
    
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_YEAR, gSwrbTestDataFilePath);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_MONTH, gSwrbTestDataFilePath);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_DAY, gSwrbTestDataFilePath);
    
    lwBuf = "/";
    gSwrbTestDataFilePath = strcat(gSwrbTestDataFilePath, lwBuf);
    
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_SN1, gSwrbTestDataFilePath);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_SN2, gSwrbTestDataFilePath);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_SN3, gSwrbTestDataFilePath);

    lwBuf = ".txt";
    gSwrbTestDataFilePath = strcat(gSwrbTestDataFilePath, lwBuf);

    hItem = WM_GetDialogItem(*hWin, ID_SET_EDIT_COMB);
    EDIT_SetText(hItem, gSwrbTestDataFilePath);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)
    int     lwItemIndex;
    char   *lwBuf;
    int     i;
    // USER END

    switch (pMsg->MsgId) {
        case WM_INIT_DIALOG:
            //
            // Initialization of 'SettingDLG'
            //
            hItem = pMsg->hWin;
            FRAMEWIN_SetTextColor(hItem, 0x00000000);
            //
            // Initialization of 'TEXT'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_TEXT_0);
            TEXT_SetFont(hItem, &GUI_Font32_ASCII);
            TEXT_SetTextColor(hItem, GUI_WHITE);
            //
            // Initialization of 'confirm'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_BUTTON_CONFIRM);
            BUTTON_SetText(hItem, "Confirm");
            Button_Init(hItem);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
            //
            // Initialization of 'check'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_BUTTON_CHECK);
            BUTTON_SetText(hItem, "Check");
            Button_Init(hItem);
            //
            // Initialization of 'reset'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_BUTTON_RESET);
            BUTTON_SetText(hItem, "Reset");
            Button_Init(hItem);
            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
            //
            // Initialization of 'cancel'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_BUTTON_CANCEL);
            BUTTON_SetText(hItem, "Cancel");
            Button_Init(hItem);
            //
            // Initialization of 'lwYear'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_YEAR);
            ListWheel_Init(hItem);
            LISTWHEEL_AddString(hItem, "2014");
            LISTWHEEL_AddString(hItem, "2015");
            LISTWHEEL_AddString(hItem, "2016");
            LISTWHEEL_AddString(hItem, "2017");
            LISTWHEEL_AddString(hItem, "2018");
            LISTWHEEL_AddString(hItem, "2019");
            LISTWHEEL_AddString(hItem, "2020");
            LISTWHEEL_AddString(hItem, "2021");
            LISTWHEEL_AddString(hItem, "2022");
            LISTWHEEL_AddString(hItem, "2023");
            LISTWHEEL_AddString(hItem, "2024");
            LISTWHEEL_AddString(hItem, "2025");
            //
            // Initialization of 'lwMonth'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_MONTH);
            ListWheel_Init(hItem);
            LISTWHEEL_AddString(hItem, "01");
            LISTWHEEL_AddString(hItem, "02");
            LISTWHEEL_AddString(hItem, "03");
            LISTWHEEL_AddString(hItem, "04");
            LISTWHEEL_AddString(hItem, "05");
            LISTWHEEL_AddString(hItem, "06");
            LISTWHEEL_AddString(hItem, "07");
            LISTWHEEL_AddString(hItem, "08");
            LISTWHEEL_AddString(hItem, "09");
            LISTWHEEL_AddString(hItem, "10");
            LISTWHEEL_AddString(hItem, "11");
            LISTWHEEL_AddString(hItem, "12");
            //
            // Initialization of 'lwDay'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_DAY);
            ListWheel_Init(hItem);
            LISTWHEEL_AddString(hItem, "01");
            LISTWHEEL_AddString(hItem, "02");
            LISTWHEEL_AddString(hItem, "03");
            LISTWHEEL_AddString(hItem, "04");
            LISTWHEEL_AddString(hItem, "05");
            LISTWHEEL_AddString(hItem, "06");
            LISTWHEEL_AddString(hItem, "07");
            LISTWHEEL_AddString(hItem, "08");
            LISTWHEEL_AddString(hItem, "09");
            LISTWHEEL_AddString(hItem, "10");
            LISTWHEEL_AddString(hItem, "11");
            LISTWHEEL_AddString(hItem, "12");
            LISTWHEEL_AddString(hItem, "13");
            LISTWHEEL_AddString(hItem, "14");
            LISTWHEEL_AddString(hItem, "15");
            LISTWHEEL_AddString(hItem, "16");
            LISTWHEEL_AddString(hItem, "17");
            LISTWHEEL_AddString(hItem, "18");
            LISTWHEEL_AddString(hItem, "19");
            LISTWHEEL_AddString(hItem, "20");
            LISTWHEEL_AddString(hItem, "21");
            LISTWHEEL_AddString(hItem, "22");
            LISTWHEEL_AddString(hItem, "23");
            LISTWHEEL_AddString(hItem, "24");
            LISTWHEEL_AddString(hItem, "25");
            LISTWHEEL_AddString(hItem, "26");
            LISTWHEEL_AddString(hItem, "27");
            LISTWHEEL_AddString(hItem, "28");
            LISTWHEEL_AddString(hItem, "29");
            LISTWHEEL_AddString(hItem, "30");
            LISTWHEEL_AddString(hItem, "31");
            //
            // Initialization of 'lwSN1,2,3'
            //
            for(i=ID_SET_LISTWHEEL_SN1;i<=ID_SET_LISTWHEEL_SN3;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                ListWheel_Init(hItem);
                LISTWHEEL_AddString(hItem, "0");
                LISTWHEEL_AddString(hItem, "1");
                LISTWHEEL_AddString(hItem, "2");
                LISTWHEEL_AddString(hItem, "3");
                LISTWHEEL_AddString(hItem, "4");
                LISTWHEEL_AddString(hItem, "5");
                LISTWHEEL_AddString(hItem, "6");
                LISTWHEEL_AddString(hItem, "7");
                LISTWHEEL_AddString(hItem, "8");
                LISTWHEEL_AddString(hItem, "9");
            }
            //
            // Initialization of 'edit'
            //
            
            for(i=ID_SET_EDIT_COMB;i<=ID_SET_EDIT_SN3;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
                EDIT_SetTextMode(hItem);
                EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_COMB);
            EDIT_SetMaxLen(hItem, 50);
            // USER START (Optionally insert additional code for further widget initialization)
            WM_HideWin(pMsg->hWin);
            // USER END
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
                case ID_SET_BUTTON_CONFIRM: // Notifications sent by 'Confirm'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            gSwrbTestMode = SWRB_TEST_MODE_IDLE;
                            WM_HideWin(pMsg->hWin);
                            WM_ShowWin(hWinEJE_SWRB_TEST_MAIN);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_BUTTON_CHECK: // Notifications sent by 'Check'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            ListWheel_TestDataFilePathGen(&pMsg->hWin);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_BUTTON_RESET: // Notifications sent by 'Reset'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            for(i=ID_SET_LISTWHEEL_0;i<=ID_SET_LISTWHEEL_5;i++){
                                hItem = WM_GetDialogItem(pMsg->hWin, i);
                                LISTWHEEL_MoveToPos(hItem, 0);
                            }
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_BUTTON_CANCEL: // Notifications sent by 'Cancel'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            for(i=ID_SET_LISTWHEEL_0;i<=ID_SET_LISTWHEEL_5;i++){
                                hItem = WM_GetDialogItem(pMsg->hWin, i);
                                LISTWHEEL_MoveToPos(hItem, 0);
                            }
                            WM_HideWin(pMsg->hWin);
                            WM_ShowWin(hWinEJE_SWRB_TEST_MAIN);
                            gSwrbTestMode = SWRB_TEST_MODE_IDLE;
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_LISTWHEEL_0: // Notifications sent by 'lwYear'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)

                            // USER END
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_YEAR);
                            lwItemIndex = LISTWHEEL_GetPos(hItem);
                            LISTWHEEL_SetSel(hItem, lwItemIndex);
                            lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
                            LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_YEAR);
                            EDIT_SetText(hItem, lwBuf);
                            myfree(SRAMIN, lwBuf);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_LISTWHEEL_1: // Notifications sent by 'lwMonth'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_MONTH);
                            lwItemIndex = LISTWHEEL_GetPos(hItem);
                            LISTWHEEL_SetSel(hItem, lwItemIndex);
                            lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
                            LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_MONTH);
                            EDIT_SetText(hItem, lwBuf);
                            myfree(SRAMIN, lwBuf);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_LISTWHEEL_2: // Notifications sent by 'lwDay'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_DAY);
                            lwItemIndex = LISTWHEEL_GetPos(hItem);
                            LISTWHEEL_SetSel(hItem, lwItemIndex);
                            lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
                            LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_DAY);
                            EDIT_SetText(hItem, lwBuf);
                            myfree(SRAMIN, lwBuf);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further notification handling)
                        // USER END
                    }
                    break;
                case ID_SET_LISTWHEEL_3: // Notifications sent by 'lwSN1'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_SN1);
                            lwItemIndex = LISTWHEEL_GetPos(hItem);
                            LISTWHEEL_SetSel(hItem, lwItemIndex);
                            lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
                            LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_SN1);
                            EDIT_SetText(hItem, lwBuf);
                            myfree(SRAMIN, lwBuf);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further Ids)
                        // USER END
                    }
                    break;
                case ID_SET_LISTWHEEL_4: // Notifications sent by 'lwSN2'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_SN2);
                            lwItemIndex = LISTWHEEL_GetPos(hItem);
                            LISTWHEEL_SetSel(hItem, lwItemIndex);
                            lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
                            LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_SN2);
                            EDIT_SetText(hItem, lwBuf);
                            myfree(SRAMIN, lwBuf);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further Ids)
                        // USER END
                    }
                    break;
                case ID_SET_LISTWHEEL_5: // Notifications sent by 'lwSN3'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            // USER START (Optionally insert code for reacting on notification message)
                            // USER END
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            // USER START (Optionally insert code for reacting on notification message)
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_LISTWHEEL_SN3);
                            lwItemIndex = LISTWHEEL_GetPos(hItem);
                            LISTWHEEL_SetSel(hItem, lwItemIndex);
                            lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
                            LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
                            hItem = WM_GetDialogItem(pMsg->hWin, ID_SET_EDIT_SN3);
                            EDIT_SetText(hItem, lwBuf);
                            myfree(SRAMIN, lwBuf);
                            // USER END
                            break;
                        // USER START (Optionally insert additional code for further Ids)
                        // USER END
                    }
                    break;
                }
        // USER START (Optionally insert additional message handling)
        // USER END
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSettingDLG
*/
WM_HWIN CreateSettingDLG(void) {
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
void SWRB_ListWheelSNInc(WM_HWIN *hWin)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *strSN1,*strSN2,*strSN3;
    char *str;
    
    strSN3 = mymalloc(SRAMIN, sizeof(char)*3);
    strSN2 = mymalloc(SRAMIN, sizeof(char)*3);
    strSN1 = mymalloc(SRAMIN, sizeof(char)*3);
    
    ListWheel_GetText(hWin, ID_SET_LISTWHEEL_SN3, strSN3);
    if(*strSN3 != '9'){
        hItem = WM_GetDialogItem(*hWin, ID_SET_LISTWHEEL_SN3);
        lwItemIndex = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetPos(hItem, lwItemIndex+1);
        LISTWHEEL_SetSel(hItem, lwItemIndex+1);
    }else{
        hItem = WM_GetDialogItem(*hWin, ID_SET_LISTWHEEL_SN3);
        LISTWHEEL_SetPos(hItem, 0);
        LISTWHEEL_SetSel(hItem, 0);
        
        ListWheel_GetText(hWin, ID_SET_LISTWHEEL_SN2, strSN2);
        if(*strSN2 != '9'){
            hItem = WM_GetDialogItem(*hWin, ID_SET_LISTWHEEL_SN2);
            lwItemIndex = LISTWHEEL_GetPos(hItem);
            LISTWHEEL_SetPos(hItem, lwItemIndex+1);
            LISTWHEEL_SetSel(hItem, lwItemIndex+1);
        }else{
            hItem = WM_GetDialogItem(*hWin, ID_SET_LISTWHEEL_SN2);
            LISTWHEEL_SetPos(hItem, 0);
            LISTWHEEL_SetSel(hItem, 0);
            
            ListWheel_GetText(hWin, ID_SET_LISTWHEEL_SN1, strSN1);
            if(*strSN1 != '9'){
                hItem = WM_GetDialogItem(*hWin, ID_SET_LISTWHEEL_SN1);
                lwItemIndex = LISTWHEEL_GetPos(hItem);
                LISTWHEEL_SetPos(hItem, lwItemIndex+1);
                LISTWHEEL_SetSel(hItem, lwItemIndex+1);
            }else{
                str = "SerialNumber is larger than 999, return to 0\r\n";
                SWRB_TestDataFileWriteString(str);
                MultiEdit_Add_Text(str);
                hItem = WM_GetDialogItem(*hWin, ID_SET_LISTWHEEL_SN1);
                LISTWHEEL_SetPos(hItem, 0);
                LISTWHEEL_SetSel(hItem, 0);
            }
        }
    }
    
    myfree(SRAMIN, strSN1);
    myfree(SRAMIN, strSN2);
    myfree(SRAMIN, strSN3);
}

FRESULT SWRB_TestDataFileOpen(void)
{
    FRESULT flErr;
    
    ListWheel_TestDataFilePathGen(&hWinEJE_SWRB_TEST_SETTING);
    flErr = f_open(file, gSwrbTestDataFilePath, FA_WRITE|FA_OPEN_ALWAYS);
    f_lseek(file, file->fsize);
    
    return flErr;
}

void SWRB_TestDataSaveToFile(void dataSaveProc(void))
{
    SWRB_TestDataFileOpen();
    dataSaveProc();
    f_close(file);
}

void SWRB_TestDataFileWriteSN(WM_HWIN *hWin)
{
    char *gSwrbTestSerialNum;
    char *cBuf;
    
    SWRB_TestDataFileOpen();

    gSwrbTestSerialNum = mymalloc(SRAMIN, sizeof(char)*50);
    mymemset(gSwrbTestSerialNum, 0, sizeof(char)*50);
    
    *gSwrbTestSerialNum = 0;
    
    cBuf = "\nSerialNumber:";
    
    gSwrbTestSerialNum = strcat(gSwrbTestSerialNum, cBuf);

    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_YEAR, gSwrbTestSerialNum);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_MONTH, gSwrbTestSerialNum);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_DAY, gSwrbTestSerialNum);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_SN1, gSwrbTestSerialNum);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_SN2, gSwrbTestSerialNum);
    SerialNum_Comb(&(*hWin), ID_SET_LISTWHEEL_SN3, gSwrbTestSerialNum);

    f_printf(file, "%s\r\n", gSwrbTestSerialNum);
//    f_puts(gSwrbTestSerialNum, file);
//    f_puts("\r\n", file);
    
    f_close(file);
    
    myfree(SRAMIN, gSwrbTestSerialNum);
}

void SWRB_SET_ListwheelSnapPosUpdate(void)
{
    int i,j;
    WM_HWIN hItem;
    
    for(i=ID_SET_LISTWHEEL_YEAR;i<=ID_SET_LISTWHEEL_SN3;i++){
        hItem = WM_GetDialogItem(hWinEJE_SWRB_TEST_SETTING, i);
        j = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetSel(hItem, j);
    }
}

void SWRB_SET_EditTextUpdate(void)
{
    int i,j;
    char *str;
    int lwItemIndex;
    LISTWHEEL_Handle hListWheel;
    WM_HWIN hItem;
    
    for(i=ID_SET_EDIT_YEAR,j=ID_SET_LISTWHEEL_YEAR;i<=ID_SET_EDIT_SN3;i++,j++){
        hListWheel = WM_GetDialogItem(hWinEJE_SWRB_TEST_SETTING, j);
        lwItemIndex = LISTWHEEL_GetPos(hListWheel);
        str = mymalloc(SRAMIN, sizeof(char)*10);
        if(str != NULL){
            *str = 0;
            LISTWHEEL_GetItemText(hListWheel, lwItemIndex, str, 10);
            hItem = WM_GetDialogItem(hWinEJE_SWRB_TEST_SETTING, i);
            EDIT_SetText(hItem, str);
            myfree(SRAMIN, str);
        }
    }
}

// USER END

/*************************** End of file ****************************/
