/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 20151209_CHN.c                                        *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x53D6 (21462)                                *
* Character enabled:   0x67E5 (26597)                                *
* Character enabled:   0x68C0 (26816)                                *
* Character enabled:   0x6D88 (28040)                                *
* Character enabled:   0x786E (30830)                                *
* Character enabled:   0x7F6E (32622)                                *
* Character enabled:   0x8BA4 (35748)                                *
* Character enabled:   0x91CD (37325)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font20151209_CHN;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_53D6[132] = { /* code 53D6 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,______XX,________,________,
  __XXXXXX,XXXXXXXX,X_______,________,
  _____XX_,____XX__,________,________,
  _____XX_,____XX__,________,__X_____,
  _____XX_,____XX_X,XXXXXXXX,XXXX____,
  _____XX_,____XX__,_X______,_XX_____,
  _____XX_,____XX__,__X_____,_XX_____,
  _____XXX,XXXXXX__,__X_____,_XX_____,
  _____XX_,____XX__,__X_____,_XX_____,
  _____XX_,____XX__,__X_____,XX______,
  _____XX_,____XX__,__X_____,XX______,
  _____XX_,____XX__,___X____,XX______,
  _____XX_,____XX__,___X___X,X_______,
  _____XXX,XXXXXX__,___X___X,X_______,
  _____XX_,____XX__,___XX__X,X_______,
  _____XX_,____XX__,____X_XX,________,
  _____XX_,____XX__,____XXXX,________,
  _____XX_,____XX__,XX__XXX_,________,
  _____XX_,___XXXXX,_____XX_,________,
  _____XXX,XXX_XX__,____XXX_,________,
  __XXXXXX,____XX__,____XXXX,________,
  __XXX___,____XX__,___XX__X,X_______,
  ________,____XX__,__XX____,XXX_____,
  ________,____XX__,__X_____,_XXX____,
  ________,____XX__,_X______,__XXXXX_,
  ________,____XX__,X_______,___XX___,
  ________,____XX_X,________,________,
  ________,____X_X_,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_67E5[132] = { /* code 67E5 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_______X,X_______,________,
  ________,_______X,XX______,________,
  ________,_______X,X_______,___X____,
  ________,_______X,X_______,__XXX___,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XXX,X_X_____,________,
  ________,_____XXX,X__X____,________,
  ________,____XX_X,X__XX___,________,
  ________,___XX__X,X___XX__,________,
  ________,__XX___X,X____XX_,________,
  ________,XXX____X,X_____XX,X_______,
  _______X,X______X,X______X,XXXX____,
  ______XX,X_____X_,_______X,_XXXXX__,
  ____XX__,XXXXXXXX,XXXXXXXX,X__X____,
  __XX____,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,X_______,________,__X_____,
  ________,________,________,_XXX____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_68C0[132] = { /* code 68C0 */
  ________,________,________,________,
  ________,________,________,________,
  ______XX,________,__XX____,________,
  ______XX,X_______,__XXX___,________,
  ______XX,________,__XXX___,________,
  ______XX,________,_XX_X___,________,
  ______XX,________,_XX__X__,________,
  ______XX,________,_X___XX_,________,
  ______XX,___X____,XX____XX,________,
  _XXXXXXX,XXXXX__X,X______X,X_______,
  ______XX,_______X,________,XXX_____,
  ______XX,______X_,________,_XXXX___,
  ______XX,_____X__,________,__XXXX__,
  ______XX,X___X___,_______X,X_______,
  _____XXX,_XXX__XX,XXXXXXXX,XX______,
  _____XXX,__XX____,________,________,
  _____XXX,__XX____,________,_X______,
  ____XXXX,___X____,__X_____,_XX_____,
  ____X_XX,_____X__,__XX____,XX______,
  ___XX_XX,_____X__,___X____,XX______,
  ___X__XX,______X_,___XX___,XX______,
  __X___XX,______XX,___XX___,X_______,
  __X___XX,______XX,___XX___,X_______,
  _X____XX,_______X,___XX__X,X_______,
  ______XX,_______X,X___X__X,________,
  ______XX,_______X,X______X,________,
  ______XX,_______X,______XX,________,
  ______XX,________,______X_,___XX___,
  ______XX,________,______X_,__XXXX__,
  ______XX,___XXXXX,XXXXXX_X,XX______,
  ______XX,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_6D88[132] = { /* code 6D88 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,___XX___,________,
  _____X__,________,___XXX__,________,
  ______X_,_____X__,___XX___,__XX____,
  ______XX,X____XXX,___XX___,__XX____,
  _______X,X_____XX,X__XX___,_XX_____,
  _______X,X______X,X__XX___,XX______,
  ________,___X___X,X__XX___,X_______,
  ________,___X____,___XX__X,________,
  __X_____,___X_X__,___XX___,__X_____,
  ___XX___,__X__XXX,XXXXXXXX,XXXX____,
  ___XXX__,__X__XX_,________,_XX_____,
  ____XX__,__X__XX_,________,_XX_____,
  ____XX__,__X__XX_,________,_XX_____,
  _____X__,_X___XX_,________,_XX_____,
  ________,_X___XXX,XXXXXXXX,XXX_____,
  ________,XX___XX_,________,_XX_____,
  ________,X____XX_,________,_XX_____,
  ________,X____XX_,________,_XX_____,
  _______X,X____XX_,________,_XX_____,
  ______XX,_____XXX,XXXXXXXX,XXX_____,
  __XXXXXX,_____XX_,________,_XX_____,
  _____XXX,_____XX_,________,_XX_____,
  ______XX,_____XX_,________,_XX_____,
  ______XX,_____XX_,________,_XX_____,
  ______XX,_____XX_,________,_XX_____,
  _____XXX,_____XX_,________,_XX_____,
  _____XXX,_____XX_,_____XXX,XXX_____,
  ______XX,_____XX_,________,XXX_____,
  ________,_____X__,________,XX______,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_786E[132] = { /* code 786E */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,__XX____,________,
  ________,________,__XXX___,________,
  ________,________,_XX_____,________,
  ________,___XX___,_XX_____,XX______,
  __XXXXXX,XXXXXX__,XXXXXXXX,XXX_____,
  ______XX,________,X______X,X_______,
  ______XX,_______X,X______X,________,
  ______XX,_______X,______X_,________,
  ______X_,______XX,_____X__,___X____,
  _____XX_,_____X_X,XXXXXXXX,XXXXX___,
  _____XX_,____X__X,X____XX_,___XX___,
  _____X__,__XX___X,X____XX_,___XX___,
  ____XXXX,XXXXX__X,X____XX_,___XX___,
  ____XX__,__XX___X,X____XX_,___XX___,
  ____XX__,__XX___X,XXXXXXXX,XXXXX___,
  ___X_X__,__XX___X,X____XX_,___XX___,
  ___X_X__,__XX___X,X____XX_,___XX___,
  __X__X__,__XX___X,X____XX_,___XX___,
  _X___X__,__XX___X,X____XX_,___XX___,
  _____X__,__XX___X,XXXXXXXX,XXXXX___,
  _____X__,__XX___X,X____XX_,___XX___,
  _____X__,__XX___X,_____XX_,___XX___,
  _____XXX,XXXX__XX,_____XX_,___XX___,
  _____X__,__XX__XX,_____XX_,___XX___,
  _____X__,______X_,_____XX_,___XX___,
  _____X__,_____XX_,_____XX_,___XX___,
  ________,_____X__,_____XXX,XXXXX___,
  ________,____X___,_____X__,__XX____,
  ________,___X____,________,__X_____,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_7F6E[132] = { /* code 7F6E */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XX_,______X_,________,_XX_____,
  ________,_______X,X_______,_X______,
  ________,_______X,________,_XX_____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,______XX,________,________,
  _______X,______XX,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,____X___,
  ________,XX______,______XX,___XXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_8BA4[132] = { /* code 8BA4 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,___X____,________,
  ______XX,________,___XX___,________,
  _______X,X_______,___XX___,________,
  _______X,XX______,___XX___,________,
  ________,XX______,__XXX___,________,
  ________,XX______,__XXX___,________,
  ________,X_______,__XXX___,________,
  ________,________,__XXX___,________,
  ________,________,__XXX___,________,
  _______X,________,__XXX___,________,
  ______XX,X_______,__XXX___,________,
  __XXXX_X,X_______,__XXX___,________,
  _______X,________,__XX_X__,________,
  _______X,________,__X__X__,________,
  _______X,________,__X__X__,________,
  _______X,________,_XX__X__,________,
  _______X,________,_XX__XX_,________,
  _______X,_____X__,_XX___X_,________,
  _______X,____X___,XX____XX,________,
  _______X,___X____,XX_____X,________,
  _______X,__X____X,X______X,X_______,
  _______X,_XX____X,_______X,X_______,
  _______X,XX____XX,________,XX______,
  ______XX,X____XX_,________,_XX_____,
  _______X,____X___,________,_XXXX___,
  ________,__XX____,________,__XXXX__,
  ________,_XX_____,________,___X____,
  ________,X_______,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20151209_CHN_91CD[132] = { /* code 91CD */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,_______X,________,
  ________,________,___XXXXX,X_______,
  ________,_____XXX,XXXXXX__,________,
  ______XX,XXXXX__X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,__XX____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  _______X,_______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,X______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,X______X,X______X,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,___XX___,
  ________,_______X,X_______,__XXXX__,
  __XXXXXX,XXXXXXX_,_XXXXXXX,XX______,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font20151209_CHN_CharInfo[8] = {
   {  32,  32,  4, acGUI_Font20151209_CHN_53D6 } /* code 53D6 */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_67E5 } /* code 67E5 */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_68C0 } /* code 68C0 */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_6D88 } /* code 6D88 */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_786E } /* code 786E */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_7F6E } /* code 7F6E */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_8BA4 } /* code 8BA4 */
  ,{  32,  32,  4, acGUI_Font20151209_CHN_91CD } /* code 91CD */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop8 = {
   0x91CD /* first character */
  ,0x91CD /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop7 = {
   0x8BA4 /* first character */
  ,0x8BA4 /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  6] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop6 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  5] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop5 = {
   0x786E /* first character */
  ,0x786E /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  4] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop4 = {
   0x6D88 /* first character */
  ,0x6D88 /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  3] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop3 = {
   0x68C0 /* first character */
  ,0x68C0 /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  2] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop2 = {
   0x67E5 /* first character */
  ,0x67E5 /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  1] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20151209_CHN_Prop1 = {
   0x53D6 /* first character */
  ,0x53D6 /* last character  */
  ,&GUI_Font20151209_CHN_CharInfo[  0] /* address of first character */
  ,&GUI_Font20151209_CHN_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font20151209_CHN = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font20151209_CHN_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

