/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: myCHN.c                                               *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Character disabled:  0x71 (113)                                    *
* Character enabled:   0x71 (113)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x4E3B (20027)                                *
* Character enabled:   0x677F (26495)                                *
* Character enabled:   0x8BD5 (35797)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5145 (20805)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x5EA7 (24231)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5F00 (24320)                                *
* Character enabled:   0x59CB (22987)                                *
* Character enabled:   0x8BBE (35774)                                *
* Character enabled:   0x7F6E (32622)                                *
* Character enabled:   0x505C (20572)                                *
* Character enabled:   0x6B62 (27490)                                *
* Character enabled:   0x6682 (26242)                                *
* Character enabled:   0x6062 (24674)                                *
* Character enabled:   0x590D (22797)                                *
* Character enabled:   0x9000 (36864)                                *
* Character disabled:  0x9000 (36864)                                *
* Character enabled:   0x51FA (20986)                                *
* Character enabled:   0x9000 (36864)                                *
* Character disabled:  0x9000 (36864)                                *
* Character enabled:   0x9000 (36864)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontmyCHN;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_505C[132] = { /* code 505C */
  ________,________,________,________,
  ________,________,________,________,
  _______X,________,_X______,________,
  _______X,XX______,__XX____,________,
  _______X,X_______,__XXX___,________,
  _______X,________,___X____,__XX____,
  ______XX,__XXXXXX,XXXXXXXX,XXXXX___,
  ______XX,________,________,________,
  ______X_,_____X__,________,X_______,
  _____XX_,______XX,XXXXXXXX,XX______,
  _____XXX,______X_,_______X,X_______,
  ____XXX_,______X_,_______X,X_______,
  ____XXX_,______X_,_______X,X_______,
  ___XXXX_,______XX,XXXXXXXX,X_______,
  ___X_XX_,______X_,_______X,________,
  __X__XX_,__X_____,________,____X___,
  __X__XX_,__XXXXXX,XXXXXXXX,XXXXXX__,
  _____XX_,__X_____,________,___XX___,
  _____XX_,_XX_____,________,__X_____,
  _____XX_,_XX_____,________,_XX_____,
  _____XX_,____XXXX,XXXXXXXX,XXX_____,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,________,___XX___,________,
  _____XX_,_______X,X_XXX___,________,
  _____XX_,________,_XXX____,________,
  _____XX_,________,__X_____,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_51FA[132] = { /* code 51FA */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ______X_,_______X,X_______,X_______,
  ______XX,X______X,X_______,XXX_____,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  ______XX,_______X,X_______,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_______X,X_______,XX______,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XXX____,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XX_____,
  _____XX_,_______X,X_______,_XX_____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,________,________,_XX_____,
  ________,________,________,_X______,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_590D[132] = { /* code 590D */
  ________,________,________,________,
  ________,________,________,________,
  ________,__X_____,________,________,
  ________,_XXXX___,________,________,
  ________,_XX_____,________,__XX____,
  ________,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,XX______,________,________,
  _______X,X_______,________,________,
  ______XX,_X______,_______X,X_______,
  _____XX_,_XXXXXXX,XXXXXXXX,XX______,
  ____XX__,_XX_____,_______X,X_______,
  ___X____,_XX_____,_______X,X_______,
  __X_____,_XX_____,_______X,X_______,
  ________,_XXXXXXX,XXXXXXXX,X_______,
  ________,_XX_____,_______X,X_______,
  ________,_XX_____,_______X,X_______,
  ________,_XXXXXXX,XXXXXXXX,X_______,
  ________,_XXX____,_______X,________,
  ________,___XXX__,______X_,________,
  ________,__XX____,______XX,________,
  ________,__XXXXXX,XXXXXXXX,X_______,
  ________,_XX_X___,_____XX_,________,
  ________,XX___X__,____XX__,________,
  _______X,X_____X_,___XX___,________,
  ______XX,______XX,_XXX____,________,
  _____X__,_______X,XXX_____,________,
  ____X___,______XX,XXX_____,________,
  ________,____XXXX,__XXXX__,________,
  ________,__XXX___,____XXXX,XX______,
  _______X,XXX_____,______XX,XXXXXX__,
  ___XXXX_,________,________,__XX____,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_59CB[132] = { /* code 59CB */
  ________,________,________,________,
  ________,________,________,________,
  _______X,________,____X___,________,
  _______X,XX______,____XXX_,________,
  _______X,X_______,___XXX__,________,
  _______X,X_______,___XX___,________,
  _______X,________,___X____,________,
  ______XX,________,__XX____,________,
  ______XX,________,__X_____,XX______,
  ______XX,____XX__,_XX_____,_XX_____,
  __XXXXX_,XXXXXX__,_X______,__XX____,
  _____XX_,___XX___,X_______,___XX___,
  _____XX_,___XX__X,X_______,___XXX__,
  _____XX_,___XX__X,XXXXXXXX,XXX_XX__,
  _____X__,___XX__X,XX______,____XX__,
  ____XX__,___X____,________,________,
  ____XX__,__XX____,________,________,
  ____X___,__XX____,X_______,___X____,
  ____X___,__XX____,XXXXXXXX,XXXXX___,
  ___XX___,__X_____,XX______,__XX____,
  ___XX___,_XX_____,XX______,__XX____,
  _____XX_,_XX_____,XX______,__XX____,
  _______X,XX______,XX______,__XX____,
  ________,XXXX____,XX______,__XX____,
  _______X,X_XXX___,XX______,__XX____,
  _______X,___XXX__,XX______,__XX____,
  ______XX,____XX__,XX______,__XX____,
  _____XX_,________,XXXXXXXX,XXXX____,
  ____XX__,________,XX______,__XX____,
  ___X____,________,XX______,__XX____,
  __X_____,________,X_______,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_5F00[132] = { /* code 5F00 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,__X_____,
  ________,________,________,_XXX____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,___XX___,
  ________,__XX____,____XX__,__XXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__X_____,____XX__,________,
  ________,_XX_____,____XX__,________,
  ________,_X______,____XX__,________,
  ________,XX______,____XX__,________,
  ________,X_______,____XX__,________,
  _______X,________,____XX__,________,
  ______X_,________,____XX__,________,
  _____X__,________,____XX__,________,
  ____X___,________,____XX__,________,
  __XX____,________,____X___,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_6062[132] = { /* code 6062 */
  ________,________,________,________,
  ________,________,________,________,
  ______X_,________,_X______,________,
  ______XX,________,_XX_____,________,
  ______XX,________,XX______,________,
  ______XX,________,XX______,________,
  ______XX,________,XX______,___XX___,
  ______XX,__XXXXXX,XXXXXXXX,XXXXXX__,
  ______XX,X_______,XX______,________,
  ______XX,XX______,X___X___,________,
  ___X__XX,_XX____X,X___XXX_,________,
  ___X__XX,__XX___X,X___XX__,________,
  ___X__XX,__X____X,X___XX__,________,
  __XX__XX,______XX,____XX__,________,
  __XX__XX,______XX,____XX__,___X____,
  __X___XX,______X_,_X__XX__,__XXX___,
  ______XX,_____XX_,_X__XX__,_XXX____,
  ______XX,_____XX_,XX__XXX_,_X______,
  ______XX,_____X__,XX__XXX_,X_______,
  ______XX,____XX_X,X__XX_XX,________,
  ______XX,____X___,___XX__X,________,
  ______XX,___X____,___XX__X,________,
  ______XX,___X____,__XX___X,________,
  ______XX,__X_____,__XX____,X_______,
  ______XX,_X______,_XX_____,XX______,
  ______XX,X_______,_X______,XX______,
  ______XX,________,X_______,_XXX____,
  ______XX,_______X,________,__XXX___,
  ______XX,_____XX_,________,__XXXXX_,
  ______XX,____X___,________,___X____,
  ______X_,__XX____,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_6682[132] = { /* code 6682 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_X______,________,________,
  ________,XXX_____,________,_XXX____,
  ________,XX_____X,__X___XX,XXXXX___,
  ________,X_____XX,X_XXXX__,________,
  ___XXXXX,XXXXXXXX,XXXX____,________,
  _______X,__X_____,__XX____,________,
  ______XX,__XXX___,__XX____,____X___,
  ______X_,__XX___X,__XXXXXX,XXXXXX__,
  _____XX_,__XX__XX,X_XX____,XX______,
  _____XXX,XXXXXXXX,XXXX____,XX______,
  ________,__XX____,__XX____,XX______,
  ________,__XX__XX,X_XX____,XX______,
  _______X,XXXXXX__,__X_____,XX______,
  ___XXXXX,X_XX____,_XX_____,XX______,
  ___XX___,__XX____,XX______,XX______,
  ________,__XX___X,X_______,XX______,
  ________,__X___X_,________,X_______,
  ________,X_______,_______X,XX______,
  ________,XXXXXXXX,XXXXXXXX,XX______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XX______,_______X,X_______,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,_______X,X_______,
  ________,X_______,_______X,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_6B62[132] = { /* code 6B62 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,X_______,________,
  ________,________,XXX_____,________,
  ________,________,XX______,________,
  ________,________,XX______,________,
  ________,________,XX______,________,
  ________,________,XX______,________,
  ________,________,XX______,________,
  _______X,________,XX______,________,
  ________,XX______,XX______,________,
  ________,XX______,XX______,__X_____,
  ________,X_______,XX______,_XXX____,
  ________,X_______,XXXXXXXX,X_______,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,________,
  ________,X_______,XX______,___XX___,
  ________,X_______,XX______,__XXXX__,
  __XXXXXX,_XXXXXXX,__XXXXXX,XX______,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_7F6E[132] = { /* code 7F6E */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XX_,____XX__,__XX____,_XX_____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XX_,______X_,________,_XX_____,
  ________,_______X,X_______,_X______,
  ________,_______X,________,_XX_____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,______XX,________,________,
  _______X,______XX,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,________,
  ________,XXXXXXXX,XXXXXXXX,________,
  ________,XX______,______XX,________,
  ________,XX______,______XX,____X___,
  ________,XX______,______XX,___XXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_8BBE[132] = { /* code 8BBE */
  ________,________,________,________,
  ________,________,________,________,
  _____X__,________,________,________,
  ______X_,_______X,______XX,________,
  ______XX,_______X,XXXXXXXX,X_______,
  _______X,X______X,X_____XX,________,
  _______X,X______X,X_____XX,________,
  _______X,X______X,X_____XX,________,
  ________,_______X,X_____XX,________,
  ________,_______X,______XX,________,
  ________,______XX,______XX,________,
  _______X,______XX,______XX,XXXXXX__,
  __XXXXXX,X____XX_,_______X,XXXXXX__,
  _______X,X___XX__,________,________,
  _______X,X__XX___,________,XX______,
  _______X,X_X__XXX,XXXXXXXX,XXX_____,
  _______X,X______X,________,XX______,
  _______X,X_______,X______X,X_______,
  _______X,X_______,X______X,X_______,
  _______X,X_______,XX_____X,X_______,
  _______X,X_______,_X____XX,________,
  _______X,X___X___,_XX__XXX,________,
  _______X,X__X____,__X__XX_,________,
  _______X,X_XX____,__XXXX__,________,
  _______X,XXX_____,___XXX__,________,
  _______X,XX______,__XXXX__,________,
  ______XX,X_______,_XX__XXX,________,
  _______X,X______X,XX____XX,XXX_____,
  ________,_____XXX,________,XXXXXXX_,
  ________,___XXX__,________,__XX____,
  ________,XXX_____,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmyCHN_9000[132] = { /* code 9000 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____X___,________,________,________,
  _____X__,_____X__,________,XX______,
  _____XXX,_____XXX,XXXXXXXX,XX______,
  ______XX,_____XX_,________,XX______,
  ______XX,_____XX_,________,XX______,
  ________,_____XX_,________,XX______,
  ________,_____XXX,XXXXXXXX,XX______,
  ________,_____XX_,________,XX______,
  ________,_____XX_,________,XX______,
  _______X,_____XX_,________,XX______,
  __XXXXXX,X____XX_,________,XX______,
  ______XX,_____XXX,XXXXXXXX,XX______,
  ______XX,_____XX_,________,X_X_____,
  ______XX,_____XX_,________,__XX____,
  ______XX,_____XX_,_X______,XXX_____,
  ______XX,_____XX_,__XX___X,X_______,
  ______XX,_____XX_,____XXX_,________,
  ______XX,_____XX_,_____XXX,________,
  ______XX,_____XX_,____X__X,XX______,
  ______XX,_____XX_,_XXX____,XXX_____,
  ______XX,_____XXX,XX______,_XXX____,
  _____XXX,X____XXX,________,__XX____,
  ___XXX__,_X____X_,________,___X____,
  __XXX___,__XX_X__,________,________,
  __XX____,___XXXX_,________,____XXX_,
  ________,____XXXX,XXXXXXXX,XXXXX___,
  ________,________,_XXXXXXX,XXXX____,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontmyCHN_CharInfo[11] = {
   {  32,  32,  4, acGUI_FontmyCHN_505C } /* code 505C */
  ,{  32,  32,  4, acGUI_FontmyCHN_51FA } /* code 51FA */
  ,{  32,  32,  4, acGUI_FontmyCHN_590D } /* code 590D */
  ,{  32,  32,  4, acGUI_FontmyCHN_59CB } /* code 59CB */
  ,{  32,  32,  4, acGUI_FontmyCHN_5F00 } /* code 5F00 */
  ,{  32,  32,  4, acGUI_FontmyCHN_6062 } /* code 6062 */
  ,{  32,  32,  4, acGUI_FontmyCHN_6682 } /* code 6682 */
  ,{  32,  32,  4, acGUI_FontmyCHN_6B62 } /* code 6B62 */
  ,{  32,  32,  4, acGUI_FontmyCHN_7F6E } /* code 7F6E */
  ,{  32,  32,  4, acGUI_FontmyCHN_8BBE } /* code 8BBE */
  ,{  32,  32,  4, acGUI_FontmyCHN_9000 } /* code 9000 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop11 = {
   0x9000 /* first character */
  ,0x9000 /* last character  */
  ,&GUI_FontmyCHN_CharInfo[ 10] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop10 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  9] /* address of first character */
  ,&GUI_FontmyCHN_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop9 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  8] /* address of first character */
  ,&GUI_FontmyCHN_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop8 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  7] /* address of first character */
  ,&GUI_FontmyCHN_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop7 = {
   0x6682 /* first character */
  ,0x6682 /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  6] /* address of first character */
  ,&GUI_FontmyCHN_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop6 = {
   0x6062 /* first character */
  ,0x6062 /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  5] /* address of first character */
  ,&GUI_FontmyCHN_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop5 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  4] /* address of first character */
  ,&GUI_FontmyCHN_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop4 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  3] /* address of first character */
  ,&GUI_FontmyCHN_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop3 = {
   0x590D /* first character */
  ,0x590D /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  2] /* address of first character */
  ,&GUI_FontmyCHN_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop2 = {
   0x51FA /* first character */
  ,0x51FA /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  1] /* address of first character */
  ,&GUI_FontmyCHN_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmyCHN_Prop1 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontmyCHN_CharInfo[  0] /* address of first character */
  ,&GUI_FontmyCHN_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontmyCHN = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontmyCHN_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

