/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: mySongti33_2.c                                        *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Character disabled:  0x71 (113)                                    *
* Character enabled:   0x71 (113)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x4E3B (20027)                                *
* Character enabled:   0x677F (26495)                                *
* Character enabled:   0x8BD5 (35797)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5145 (20805)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x5EA7 (24231)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontmySongti33_2;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontmySongti33_2_5145[132] = { /* code 5145 */
  ________,________,________,________,
  ________,________,________,________,
  ________,______X_,________,________,
  ________,______XX,________,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,__XX____,
  ________,_______X,X_______,_XXXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XX_,________,________,
  ________,____XXXX,________,________,
  ________,___XXX__,________,________,
  ________,__XXX___,___XX___,________,
  ________,_XX_____,_____XX_,________,
  ________,XX______,______XX,________,
  _______X,X_______,_______X,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XX_XX___,__X_____,XXX_____,
  ________,___XX___,__X_____,_XX_____,
  ________,___XX___,__X_____,________,
  ________,___XX___,__X_____,________,
  ________,___XX___,__X_____,________,
  ________,__XX____,__X_____,________,
  ________,__XX____,__X_____,________,
  ________,__XX____,__X_____,___X____,
  ________,_XX_____,__X_____,____X___,
  ________,_XX_____,__X_____,____X___,
  ________,XX______,__X_____,____X___,
  _______X,X_______,__X_____,___XX___,
  ______XX,________,__XXXXXX,XXXXXX__,
  ____XX__,________,__XXXXXX,XXXXX___,
  __XX____,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmySongti33_2_5EA7[132] = { /* code 5EA7 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_______X,________,________,
  ________,________,XX______,________,
  ________,________,XXX_____,________,
  ________,________,_X______,__XX____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,________,________,________,
  _____XX_,________,________,________,
  _____XX_,________,_XX_____,________,
  _____XX_,___X____,_XX_____,X_______,
  _____XX_,___XXX__,_XX_____,XX______,
  _____XX_,___XX___,_XX____X,XX______,
  _____XX_,___X____,_XX____X,X_______,
  _____XX_,__XX____,_XX____X,X_______,
  _____XX_,__XXX___,_XX___XX,_X______,
  _____XX_,_XX_XX__,_XX___XX,__XX____,
  _____XX_,_X___XX_,_XX___X_,__XXX___,
  _____XX_,_X____XX,_XX__X__,___XX___,
  _____X__,X_____X_,_XX_X___,____X___,
  _____X_X,________,_XX_X___,_X______,
  _____X__,________,_XX_____,XXX_____,
  ____XX__,__XXXXXX,XXXXXXXX,XXXX____,
  ____XX__,________,_XX_____,________,
  ____X___,________,_XX_____,________,
  ____X___,________,_XX_____,________,
  ___XX___,________,_XX_____,________,
  ___X____,________,_XX_____,___XX___,
  __X_____,________,_XX_____,__XXXX__,
  __X____X,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  _X______,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontmySongti33_2_7535[132] = { /* code 7535 */
  ________,________,________,________,
  ________,________,________,________,
  ________,______XX,________,________,
  ________,______XX,X_______,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,X_______,
  _____XX_,______XX,________,________,
  ________,______XX,________,___X____,
  ________,______XX,________,____X___,
  ________,______XX,________,____X___,
  ________,______XX,________,___XX___,
  ________,______XX,X_______,___XXX__,
  ________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontmySongti33_2_CharInfo[3] = {
   {  32,  32,  4, acGUI_FontmySongti33_2_5145 } /* code 5145 */
  ,{  32,  32,  4, acGUI_FontmySongti33_2_5EA7 } /* code 5EA7 */
  ,{  32,  32,  4, acGUI_FontmySongti33_2_7535 } /* code 7535 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmySongti33_2_Prop3 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontmySongti33_2_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmySongti33_2_Prop2 = {
   0x5EA7 /* first character */
  ,0x5EA7 /* last character  */
  ,&GUI_FontmySongti33_2_CharInfo[  1] /* address of first character */
  ,&GUI_FontmySongti33_2_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontmySongti33_2_Prop1 = {
   0x5145 /* first character */
  ,0x5145 /* last character  */
  ,&GUI_FontmySongti33_2_CharInfo[  0] /* address of first character */
  ,&GUI_FontmySongti33_2_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontmySongti33_2 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontmySongti33_2_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

