/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SDErrCHN.c                                            *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Character disabled:  0x71 (113)                                    *
* Character enabled:   0x71 (113)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x4E3B (20027)                                *
* Character enabled:   0x677F (26495)                                *
* Character enabled:   0x8BD5 (35797)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5145 (20805)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x5EA7 (24231)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5F00 (24320)                                *
* Character enabled:   0x59CB (22987)                                *
* Character enabled:   0x8BBE (35774)                                *
* Character enabled:   0x7F6E (32622)                                *
* Character enabled:   0x505C (20572)                                *
* Character enabled:   0x6B62 (27490)                                *
* Character enabled:   0x6682 (26242)                                *
* Character enabled:   0x6062 (24674)                                *
* Character enabled:   0x590D (22797)                                *
* Character enabled:   0x9000 (36864)                                *
* Character disabled:  0x9000 (36864)                                *
* Character enabled:   0x51FA (20986)                                *
* Character enabled:   0x9000 (36864)                                *
* Character disabled:  0x9000 (36864)                                *
* Character enabled:   0x9000 (36864)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x53 (83)                                     *
* Character enabled:   0x44 (68)                                     *
* Character enabled:   0x8BF7 (35831)                                *
* Character enabled:   0x63D2 (25554)                                *
* Character enabled:   0x5165 (20837)                                *
* Character enabled:   0x5361 (21345)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSDErrCHN;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSDErrCHN_0044[ 66] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  ___XX___,_XXX____,
  ___XX___,___XX___,
  ___XX___,____XX__,
  ___XX___,____XX__,
  ___XX___,____XX__,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,_____XX_,
  ___XX___,____XX__,
  ___XX___,____XX__,
  ___XX___,____X___,
  ___XX___,___XX___,
  ___XX___,_XXX____,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSDErrCHN_0053[ 66] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____XXX,XXX__X__,
  ____XX__,___XXX__,
  ___XX___,____XX__,
  __XX____,_____X__,
  __XX____,_____X__,
  __XX____,________,
  __XX____,________,
  ___XX___,________,
  ___XXXX_,________,
  _____XXX,XX______,
  _______X,XXXX____,
  ________,_XXXX___,
  ________,___XXX__,
  ________,____XXX_,
  ________,_____XX_,
  __X_____,_____XX_,
  __X_____,_____XX_,
  ___X____,_____XX_,
  ___XX___,____XX__,
  ___XXX__,___XX___,
  ___X__XX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSDErrCHN_5165[132] = { /* code 5165 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,__XX____,________,________,
  ________,__XXXX__,________,________,
  ________,_____XX_,________,________,
  ________,______XX,________,________,
  ________,_______X,________,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,______XX,X_______,________,
  ________,______XX,XX______,________,
  ________,______XX,_X______,________,
  ________,_____XX_,_X______,________,
  ________,_____XX_,_XX_____,________,
  ________,_____XX_,__X_____,________,
  ________,____XX__,__XX____,________,
  ________,____XX__,__XX____,________,
  ________,___XX___,___XX___,________,
  ________,__XX____,___XXX__,________,
  ________,__XX____,____XX__,________,
  ________,_XX_____,_____XX_,________,
  ________,XX______,_____XXX,________,
  ________,X_______,______XX,X_______,
  _______X,X_______,_______X,XX______,
  ______X_,________,________,XXXX____,
  _____X__,________,________,XXXXXX__,
  ____X___,________,________,__XXXX__,
  ___X____,________,________,___X____,
  _XX_____,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSDErrCHN_5361[132] = { /* code 5361 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_____XX_,________,________,
  ________,_____XXX,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,XX______,
  ________,_____XXX,XXXXXXXX,XXX_____,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,___X____,
  ________,_____XX_,________,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XXX,________,________,
  ________,_____XXX,________,________,
  ________,_____XX_,________,________,
  ________,_____XXX,X_______,________,
  ________,_____XX_,_XXXX___,________,
  ________,_____XX_,___XXXXX,________,
  ________,_____XX_,_____XXX,XX______,
  ________,_____XX_,_______X,XX______,
  ________,_____XX_,________,XX______,
  ________,_____XX_,________,_X______,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,_____XX_,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSDErrCHN_63D2[132] = { /* code 63D2 */
  ________,________,________,________,
  ________,________,________,________,
  ______X_,________,________,________,
  ______XX,X_______,________,XXX_____,
  ______XX,________,_____XXX,XXX_____,
  ______XX,_______X,XXXXXXX_,________,
  ______XX,______X_,____X___,________,
  ______XX,________,____X___,________,
  ______XX,__X_____,____X___,________,
  _XXXXXXX,XXXX____,____X___,____X___,
  ______XX,____XXXX,XXXXXXXX,XXXXXX__,
  ______XX,________,____X___,________,
  ______XX,________,____X___,________,
  ______XX,___X____,_X__X___,________,
  ______XX,_XX_____,XXX_X___,___X____,
  ______XX,XX__XXXX,____X__X,XXXXX___,
  ______XX,____XX__,____X___,___X____,
  ____XXXX,____XX__,____X___,___X____,
  __XXX_XX,____XX__,____X___,___X____,
  __XX__XX,____XX__,____X___,___X____,
  __X___XX,____XX__,XX__X___,___X____,
  ______XX,____XXXX,XXX_X__X,XXXX____,
  ______XX,____XX__,____X___,___X____,
  ______XX,____XX__,____X___,___X____,
  ______XX,____XX__,____X___,___X____,
  ______XX,____XX__,____X___,___X____,
  ______XX,____XX__,____X___,___X____,
  ______XX,____XXXX,XXXXXXXX,XXXX____,
  __XXXXXX,____XX__,________,___X____,
  ____XXXX,____XX__,________,___X____,
  _____XX_,____X___,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSDErrCHN_8BF7[132] = { /* code 8BF7 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,___XX___,________,
  _____X__,________,___XX___,________,
  _____XX_,________,___XX___,___X____,
  _____XXX,________,___XX___,__XXX___,
  ______XX,___XXXXX,XXXXXXXX,XXXXXX__,
  ______XX,________,___XX___,________,
  ______X_,________,___XX___,_XX_____,
  ________,_____XXX,XXXXXXXX,XXX_____,
  ________,________,___XX___,________,
  ______X_,________,___XX___,________,
  ______XX,________,___XX___,___XX___,
  __XXXXXX,__XXXXXX,XXXXXXXX,XXXXXX__,
  ______XX,________,________,________,
  ______XX,________,________,_X______,
  ______XX,______XX,XXXXXXXX,XXX_____,
  ______XX,______X_,________,_XX_____,
  ______XX,______X_,________,_XX_____,
  ______XX,______X_,________,_XX_____,
  ______XX,______XX,XXXXXXXX,XXX_____,
  ______XX,___X__X_,________,_XX_____,
  ______XX,__X___X_,________,_XX_____,
  ______XX,_XX___XX,XXXXXXXX,XXX_____,
  ______XX,XX____X_,________,_XX_____,
  ______XX,X_____X_,________,_XX_____,
  _____XXX,______X_,________,_XX_____,
  ______XX,______X_,________,_XX_____,
  ________,______X_,____XXXX,XX______,
  ________,______X_,_______X,XX______,
  ________,______X_,________,X_______,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSDErrCHN_CharInfo[6] = {
   {  16,  16,  2, acGUI_FontSDErrCHN_0044 } /* code 0044 */
  ,{  16,  16,  2, acGUI_FontSDErrCHN_0053 } /* code 0053 */
  ,{  32,  32,  4, acGUI_FontSDErrCHN_5165 } /* code 5165 */
  ,{  32,  32,  4, acGUI_FontSDErrCHN_5361 } /* code 5361 */
  ,{  32,  32,  4, acGUI_FontSDErrCHN_63D2 } /* code 63D2 */
  ,{  32,  32,  4, acGUI_FontSDErrCHN_8BF7 } /* code 8BF7 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSDErrCHN_Prop6 = {
   0x8BF7 /* first character */
  ,0x8BF7 /* last character  */
  ,&GUI_FontSDErrCHN_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSDErrCHN_Prop5 = {
   0x63D2 /* first character */
  ,0x63D2 /* last character  */
  ,&GUI_FontSDErrCHN_CharInfo[  4] /* address of first character */
  ,&GUI_FontSDErrCHN_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSDErrCHN_Prop4 = {
   0x5361 /* first character */
  ,0x5361 /* last character  */
  ,&GUI_FontSDErrCHN_CharInfo[  3] /* address of first character */
  ,&GUI_FontSDErrCHN_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSDErrCHN_Prop3 = {
   0x5165 /* first character */
  ,0x5165 /* last character  */
  ,&GUI_FontSDErrCHN_CharInfo[  2] /* address of first character */
  ,&GUI_FontSDErrCHN_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSDErrCHN_Prop2 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_FontSDErrCHN_CharInfo[  1] /* address of first character */
  ,&GUI_FontSDErrCHN_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSDErrCHN_Prop1 = {
   0x0044 /* first character */
  ,0x0044 /* last character  */
  ,&GUI_FontSDErrCHN_CharInfo[  0] /* address of first character */
  ,&GUI_FontSDErrCHN_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSDErrCHN = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSDErrCHN_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

