/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: START.c                                               *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Character disabled:  0x71 (113)                                    *
* Character enabled:   0x71 (113)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character disabled:  0x73 (115)                                    *
* Character enabled:   0x73 (115)                                    *
* Character enabled:   0x6D4B (27979)                                *
* Character enabled:   0x4E3B (20027)                                *
* Character enabled:   0x677F (26495)                                *
* Character enabled:   0x8BD5 (35797)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5145 (20805)                                *
* Character enabled:   0x7535 (30005)                                *
* Character enabled:   0x5EA7 (24231)                                *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5F00 (24320)                                *
* Character enabled:   0x59CB (22987)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSTART;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontSTART_59CB[132] = { /* code 59CB */
  ________,________,________,________,
  ________,________,________,________,
  _______X,________,____X___,________,
  _______X,XX______,____XXX_,________,
  _______X,X_______,___XXX__,________,
  _______X,X_______,___XX___,________,
  _______X,________,___X____,________,
  ______XX,________,__XX____,________,
  ______XX,________,__X_____,XX______,
  ______XX,____XX__,_XX_____,_XX_____,
  __XXXXX_,XXXXXX__,_X______,__XX____,
  _____XX_,___XX___,X_______,___XX___,
  _____XX_,___XX__X,X_______,___XXX__,
  _____XX_,___XX__X,XXXXXXXX,XXX_XX__,
  _____X__,___XX__X,XX______,____XX__,
  ____XX__,___X____,________,________,
  ____XX__,__XX____,________,________,
  ____X___,__XX____,X_______,___X____,
  ____X___,__XX____,XXXXXXXX,XXXXX___,
  ___XX___,__X_____,XX______,__XX____,
  ___XX___,_XX_____,XX______,__XX____,
  _____XX_,_XX_____,XX______,__XX____,
  _______X,XX______,XX______,__XX____,
  ________,XXXX____,XX______,__XX____,
  _______X,X_XXX___,XX______,__XX____,
  _______X,___XXX__,XX______,__XX____,
  ______XX,____XX__,XX______,__XX____,
  _____XX_,________,XXXXXXXX,XXXX____,
  ____XX__,________,XX______,__XX____,
  ___X____,________,XX______,__XX____,
  __X_____,________,X_______,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontSTART_5F00[132] = { /* code 5F00 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,__X_____,
  ________,________,________,_XXX____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,___XX___,
  ________,__XX____,____XX__,__XXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,__X_____,____XX__,________,
  ________,_XX_____,____XX__,________,
  ________,_X______,____XX__,________,
  ________,XX______,____XX__,________,
  ________,X_______,____XX__,________,
  _______X,________,____XX__,________,
  ______X_,________,____XX__,________,
  _____X__,________,____XX__,________,
  ____X___,________,____XX__,________,
  __XX____,________,____X___,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSTART_CharInfo[2] = {
   {  32,  32,  4, acGUI_FontSTART_59CB } /* code 59CB */
  ,{  32,  32,  4, acGUI_FontSTART_5F00 } /* code 5F00 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSTART_Prop2 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontSTART_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSTART_Prop1 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontSTART_CharInfo[  0] /* address of first character */
  ,&GUI_FontSTART_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSTART = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSTART_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

