/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"
#include "EJE_SWRB_TEST_SteerMotorTestDLG.h"
#include "swrbTestDriver.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static char *aSteerMotorDlgButtonInitText[][1] = {
    {"RETURN"}, 
    {"LIdle"}, 
    {"LFront"}, 
    {"LSide"}, 
    {"MIdle"}, 
    {"MUp"}, 
    {"MDown"}, 
    {"RIdle"}, 
    {"RFront"}, 
    {"RSide"}, 
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "winSteerMotor", ID_STEERMOTOR_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnReturn", ID_STEERMOTOR_BUTTON_RETURN, 0, 0, 60, 60, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnLIdle", ID_STEERMOTOR_BUTTON_LIDLE, 100, 40, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnLFront", ID_STEERMOTOR_BUTTON_LFRONT, 100, 190, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnLSide", ID_STEERMOTOR_BUTTON_LSIDE, 100, 340, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnMIdle", ID_STEERMOTOR_BUTTON_MIDLE, 340, 40, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnMUp", ID_STEERMOTOR_BUTTON_MUP, 340, 190, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnMDown", ID_STEERMOTOR_BUTTON_MDOWN, 340, 340, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRIdle", ID_STEERMOTOR_BUTTON_RIDLE, 580, 40, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRFront", ID_STEERMOTOR_BUTTON_RFRONT, 580, 190, 120, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRSide", ID_STEERMOTOR_BUTTON_RSIDE, 580, 340, 120, 100, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
    
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    
    for(Id=ID_STEERMOTOR_BUTTON_RETURN;Id<ID_STEERMOTOR_BUTTON_BOUND;Id++){
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        BUTTON_SetText(hItem, aSteerMotorDlgButtonInitText[Id-ID_STEERMOTOR_BUTTON_RETURN][0]);
        BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
        BUTTON_SetSkinClassic(hItem);
        WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    }
    
    WM_HideWin(pMsg->hWin);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_STEERMOTOR_BUTTON_LIDLE: // Notifications sent by 'btnLIdle'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_CollisionCtrlLeftSteerMotorPosMove(STEER_MOTOR_IDLE_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_LFRONT: // Notifications sent by 'btnLFront'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
          SweepRobot_CollisionCtrlLeftSteerMotorPosMove(STEER_MOTOR_FRONT_POS);
          break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_LSIDE: // Notifications sent by 'btnLSide'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_CollisionCtrlLeftSteerMotorPosMove(STEER_MOTOR_SIDE_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_RIDLE: // Notifications sent by 'btnRIdle'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_CollisionCtrlRightSteerMotorPosMove(STEER_MOTOR_IDLE_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_RFRONT: // Notifications sent by 'btnRFront'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_CollisionCtrlRightSteerMotorPosMove(STEER_MOTOR_FRONT_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_RSIDE: // Notifications sent by 'btnRSide'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_CollisionCtrlRightSteerMotorPosMove(STEER_MOTOR_SIDE_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_MIDLE: // Notifications sent by 'btnMIdle'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_WheelFloatCtrlSteerMotorPosMove(STEER_MOTOR_IDLE_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_MUP: // Notifications sent by 'btnMUp'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_WheelFloatCtrlSteerMotorPosMove(STEER_MOTOR_UP_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_MDOWN: // Notifications sent by 'btnMDown'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_WheelFloatCtrlSteerMotorPosMove(STEER_MOTOR_DOWN_POS);
        break;
      }
      break;
    case ID_STEERMOTOR_BUTTON_RETURN: // Notifications sent by 'btnReturn'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        WM_HideWin(hWin_SWRB_STEERMOTOR);
        WM_ShowWin(hWin_SWRB_START);
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
WM_HWIN hWin_SWRB_STEERMOTOR;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatewinSteerMotorDLG
*/
WM_HWIN CreatewinSteerMotorDLG(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/*************************** End of file ****************************/
