/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"
#include "sweeprobot_testing.h"
#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define SWRB_MANUL_LISTVIEW_ROW_NUM   15


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char *aListview_RowWheel[][10] = {
// name,left,frontLeft,middle,frontRight,right,bottomLeft,bottomFLeft,bottomFRight,bottomRight
    {"WHEEL","0","","","","0"},
    {"BRUSH","0","","0","","0"},
    {"FAN","","","0","",""},
    {"IFRD","0","0","","0","0","0","0","0","0"},
    {"COLLISION","0","0","","0","0"},
    {"WHL_FLOAT","0","","","","0"},
    {"ASH_TRAY","0","0"},
    {"UNIWHEEL","0"},
    {"KEY","0"},
    {"IRDA","0","0","","0","0","0"},
    {"BUZZER","","","0"},
    {"RGB_LED","","0","0","0"},
    {"CHARGE","0","0","0"},
    {"INT_VREF","0"},
    {"SNUM","0","0","0","0"},
};

//static u8 aListview_RowFlag[SWRB_MANUL_LISTVIEW_ROW_NUM] = { 0 };

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "winSWRBManulTest", ID_MANUL_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnStart", ID_MANUL_BUTTON_START, 700, 0, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnSet", ID_MANUL_BUTTON_SET, 700, 120, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnReset", ID_MANUL_BUTTON_RESET, 700, 240, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnExit", ID_MANUL_BUTTON_EXIT, 700, 360, 100, 120, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "lstviewSWRBTest", ID_MANUL_LISTVIEW_MAIN, 25, 80, 650, 335, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "textTitle", ID_MANUL_TEXT_TITLE, 25, 20, 650, 60, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "editDate", ID_MANUL_EDIT_DATE, 490, 427, 185, 40, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "btnIndicate", ID_MANUL_BUTTON_INDICATE, 25, 425, 40, 40, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetFocussable(hItem, DISABLE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
}

static void Listview_Init(WM_HWIN hItem)
{
    u8 i;

    LISTVIEW_AddColumn(hItem, 110, "Name", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 45, "Left", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 55, "FrontL", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_AddColumn(hItem, 60, "Middle", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetItemBkColor(hItem, 0, 0, LISTVIEW_CI_UNSEL, 0x00DFCFB3);
    LISTVIEW_AddColumn(hItem, 55, "FrontR", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 45, "Right", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 70, "BottomL", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 70, "BottonFL", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hItem, 70, "BottomFR", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetItemBkColor(hItem, 0, 0, LISTVIEW_CI_UNSEL, 0x00FFFFFF);
    LISTVIEW_AddColumn(hItem, 70, "BottomR", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_SetAutoScrollH(hItem, ENABLE);
    LISTVIEW_SetAutoScrollV(hItem, ENABLE);
    LISTVIEW_SetHeaderHeight(hItem, 30);
    for(i=0;i<SWRB_MANUL_LISTVIEW_ROW_NUM;i++){
        LISTVIEW_AddRow(hItem, aListview_RowWheel[i]);
    }
    LISTVIEW_SetRowHeight(hItem, 20);
    LISTVIEW_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
};

//static void Listview_SelChangedProc(WM_HWIN hWin, int id)
//{
//    int rowNum;
//    WM_HWIN hItem;

//    hItem = WM_GetDialogItem(hWin, id);

//    rowNum = LISTVIEW_GetSel(hItem);
//    LISTVIEW_DisableRow(hItem, rowNum);
//    aListview_RowFlag[rowNum] = DISABLE;
//}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'lstviewSWRBTest'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_LISTVIEW_MAIN);
    Listview_Init(hItem);
    //
    // Initialization of 'textTitle'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_TEXT_TITLE);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, 0x00CB8872);
    TEXT_SetText(hItem, "SWRB Manul Test");
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'editDate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_EDIT_DATE);
    EDIT_SetFont(hItem, GUI_FONT_20_ASCII);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_BLUE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    //
    // Initialization of 'btnStart'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_BUTTON_START);
    Button_Init(hItem);
    BUTTON_DispStartCHNStr(pMsg->hWin, ID_MANUL_BUTTON_START, 18, 43);
    //
    // Initialization of 'btnSet'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_BUTTON_SET);
    Button_Init(hItem);
    BUTTON_DispSetCHNStr(pMsg->hWin, ID_MANUL_BUTTON_SET, 18, 43);
    //
    // Initialization of 'btnReset'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_BUTTON_RESET);
    Button_Init(hItem);
    BUTTON_DispResetCHNStr(pMsg->hWin, ID_MANUL_BUTTON_RESET, 18, 43);
    //
    // Initialization of 'btnExit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_BUTTON_EXIT);
    Button_Init(hItem);
    BUTTON_DispExitCHNStr(pMsg->hWin, ID_MANUL_BUTTON_EXIT, 18, 43);
    //
    // Initialization of 'btnIndicate'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUL_BUTTON_INDICATE);
    Button_Init(hItem);
    BUTTON_SetText(hItem, "");

    WM_HideWin(pMsg->hWin);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MANUL_BUTTON_START: // Notifications sent by 'btnStart'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManulStartProc();
        break;
      }
      break;
    case ID_MANUL_BUTTON_SET: // Notifications sent by 'btnSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManulSetProc();
        break;
      }
      break;
    case ID_MANUL_BUTTON_RESET: // Notifications sent by 'btnReset'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManulResetProc();
        break;
      }
      break;
    case ID_MANUL_BUTTON_EXIT: // Notifications sent by 'btnExit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManulExitProc();
        break;
      }
      break;
    case ID_MANUL_LISTVIEW_MAIN: // Notifications sent by 'lstviewSWRBTest'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        break;
      }
      break;
    case ID_MANUL_EDIT_DATE: // Notifications sent by 'editDate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        break;
      }
      break;
    case ID_MANUL_BUTTON_INDICATE: // Notifications sent by 'btnIndicate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
WM_HWIN hWin_SWRB_MANUL;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateManulTestDLG
*/
WM_HWIN CreateManulTestDLG(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/*************************** End of file ****************************/
