/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"
#include "EJE_SWRB_TEST_STEPMOTORTESTDLG.h"
#include "sweeprobot_testing.h"

#include "swrbTestStepMotorDriver.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "winStepMotorTest", ID_STEPMOTOR_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRun", ID_STEPMOTOR_BUTTON_RUN, 650, 0, 150, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnStop", ID_STEPMOTOR_BUTTON_STOP, 650, 160, 150, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnForward", ID_STEPMOTOR_BUTTON_FORWARD, 50, 70, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnBackward", ID_STEPMOTOR_BUTTON_BACKWARD, 50, 230, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnEnable", ID_STEPMOTOR_BUTTON_ENABLE, 390, 70, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnDisable", ID_STEPMOTOR_BUTTON_DISABLE, 388, 230, 150, 150, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnExit", ID_STEPMOTOR_BUTTON_EXIT, 650, 320, 150, 160, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void Button_RunProc(void)
{
//    SweepRobotTest_StepMotorModeSet(STEP_MOTOR_MODE_RUN);
//    SweepRobotTest_StepMotorMoveSteps(1, 10);
    OSTaskResume(SWRB_STEPMOTOR_TASK_PRIO);
}

static void Button_StopProc(void)
{
    SweepRobotTest_StepMotorModeSet(STEP_MOTOR_MODE_HARD_STOP);
}

static void Button_ForwardProc(void)
{
    SweepRobotTest_StepMotorDirSet(STEP_MOTOR_DIR_FORWARD);
}

static void Button_BackwardProc(void)
{
    SweepRobotTest_StepMotorDirSet(STEP_MOTOR_DIR_BACKWARD);
}

static void Button_EnableProc(void)
{
    SweepRobotTest_StepMotorEnStateSet(ENABLE);
}

static void Button_DisableProc(void)
{
    SweepRobotTest_StepMotorEnStateSet(DISABLE);
}

static void Button_ExitProc(void)
{
    gSwrbTestSelectFlag = SWRB_TEST_SELECT_NONE;
    
    WM_HideWin(hWin_SWRB_STEPMOTOR);
    WM_ShowWin(hWin_SWRB_START);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'winStepMotorTest'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00E0D3C5);
    //
    // Initialization of 'btnRun'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_RUN);
    BUTTON_SetText(hItem, "RUN");
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    //
    // Initialization of 'btnStop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_STOP);
    BUTTON_SetText(hItem, "STOP");
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
  
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_FORWARD);
    BUTTON_SetText(hItem, "FORWARD");
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_BACKWARD);
    BUTTON_SetText(hItem, "BACKWARD");
    BUTTON_SetFont(hItem, GUI_FONT_32_ASCII);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_ENABLE);
    BUTTON_SetText(hItem, "ENABLE");
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_DISABLE);
    BUTTON_SetText(hItem, "DISABLE");
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_STEPMOTOR_BUTTON_EXIT);
    BUTTON_SetText(hItem, "EXIT");
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
  
    WM_HideWin(pMsg->hWin);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
        case ID_STEPMOTOR_BUTTON_RUN: // Notifications sent by 'btnRun'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_RunProc();
                    break;
            }
            break;
        case ID_STEPMOTOR_BUTTON_STOP: // Notifications sent by 'btnStop'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_StopProc();
                    break;
            }
        break;
        case ID_STEPMOTOR_BUTTON_FORWARD: // Notifications sent by 'btnForward'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_ForwardProc();
                    break;
            }
            break;
        case ID_STEPMOTOR_BUTTON_BACKWARD: // Notifications sent by 'btnBackward'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_BackwardProc();
                    break;
            }
            break;
            
        case ID_STEPMOTOR_BUTTON_ENABLE: // Notifications sent by 'btnEnable'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_EnableProc();
                    break;
            }
            break;
        case ID_STEPMOTOR_BUTTON_DISABLE: // Notifications sent by 'btnDisable'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_DisableProc();
                    break;
            }
            break;
        case ID_STEPMOTOR_BUTTON_EXIT: // Notifications sent by 'btnExit'
            switch(NCode) {
                case WM_NOTIFICATION_CLICKED:
                    break;
                case WM_NOTIFICATION_RELEASED:
                    Button_ExitProc();
                    break;
            }
            break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/
WM_HWIN hWin_SWRB_STEPMOTOR;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatewinStepMotor
*/
WM_HWIN CreatewinStepMotor(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/*************************** End of file ****************************/
