/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"

#include "sweeprobot_testing.h"
#include "rtc.h"
#include <stdio.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

extern GUI_CONST_STORAGE GUI_BITMAP _bmConfirmCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmCheckCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmResetCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmCancelCHN;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static int  lastLwIndex[6];
static RTC_DateTypeDef rtcDate;

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//    { FRAMEWIN_CreateIndirect, "SettingDLG", ID_SNSET_FRAMEWIN, 0, 0, 800, 480, 0, 0x0, 0 },
    { WINDOW_CreateIndirect, "TEST SETTING", ID_SNSET_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Set Serial Number", ID_SNSET_TEXT_0, 20, 10, 680, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Confirm", ID_SNSET_BUTTON_CONFIRM, 700, 0, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Check", ID_SNSET_BUTTON_CHECK, 700, 120, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Reset", ID_SNSET_BUTTON_RESET, 700, 240, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Cancel", ID_SNSET_BUTTON_CANCEL, 700, 360, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SNSet", ID_SNSET_BUTTON_SNSET, 0, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "TestSel", ID_SNSET_BUTTON_TESTSELECT, 100, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv2", ID_SNSET_BUTTON_RESERVE2, 200, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv3", ID_SNSET_BUTTON_RESERVE3, 300, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv4", ID_SNSET_BUTTON_RESERVE4, 400, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv5", ID_SNSET_BUTTON_RESERVE5, 500, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "TimeSet", ID_SNSET_BUTTON_TIMESET, 600, 420, 100, 60, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwYear", ID_SNSET_LISTWHEEL_YEAR, 20, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwMonth", ID_SNSET_LISTWHEEL_MONTH, 130, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwDay", ID_SNSET_LISTWHEEL_DATE, 240, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN1", ID_SNSET_LISTWHEEL_SN1, 350, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN2", ID_SNSET_LISTWHEEL_SN2, 460, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN3", ID_SNSET_LISTWHEEL_SN3, 570, 60, 110, 230, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "editComb", ID_SNSET_EDIT_COMB_SET, 20, 340, 660, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editYear", ID_SNSET_EDIT_YEAR, 20, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editMonth", ID_SNSET_EDIT_MONTH, 130, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editDay", ID_SNSET_EDIT_DAY, 240, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN1", ID_SNSET_EDIT_SN1, 350, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN2", ID_SNSET_EDIT_SN2, 460, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN3", ID_SNSET_EDIT_SN3, 570, 300, 110, 40, 0 ,0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void ListWheel_ResetToLastPos(WM_HWIN hWin);
static void ListWheel_ResetToZero(WM_HWIN hWin);
static void ListWheel_TestDataFilePathGet(WM_HWIN hWin, char *dest_str);


static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetFocussable(hItem, DISABLE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
}

static void Button_ConfirmProc(WM_HWIN hWin)
{
    char *str;
    
    gSwrbTestSelectFlag = SWRB_TEST_SELECT_NONE;
    gSwrbTestMode = SWRB_TEST_MODE_IDLE;

    ListWheel_TestDataFilePathGet(hWin,str);

    WM_HideWin(hWin);
    WM_ShowWin(hWin_SWRB_START);
    WM_BringToTop(hWin_SWRB_START);
}

static void Button_CheckProc(WM_HWIN hWin)
{
    char *str;

    ListWheel_TestDataFilePathGet(hWin, str);
}

static void Button_ResetProc(WM_HWIN hWin)
{
    ListWheel_ResetToZero(hWin);
}

static void Button_CancelProc(WM_HWIN hWin)
{
    gSwrbTestSelectFlag = SWRB_TEST_SELECT_NONE;
    gSwrbTestMode = SWRB_TEST_MODE_IDLE;
    
    ListWheel_ResetToLastPos(hWin);
    WM_HideWin(hWin);
    WM_ShowWin(hWin_SWRB_START);
}

//static void ListWheel_SnapLineDraw(GUI_COLOR color)
//{
//    uint8_t prevPenSize;
//    GUI_COLOR prevColor;

//    prevPenSize = GUI_GetPenSize();
//    GUI_SetPenSize(10);
//    prevColor = GUI_GetColor();
//    GUI_SetColor(color);
//    GUI_DrawLine(20, 160, 570, 190);
//    GUI_SetPenSize(prevPenSize);
//    GUI_SetColor(prevColor);
//}

static void ListWheel_Init(WM_HWIN hItem)
{
    LISTWHEEL_SetFont(hItem, GUI_FONT_32_ASCII);
    LISTWHEEL_SetDeceleration(hItem, 10);
    LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTWHEEL_SetSnapPosition(hItem, 115);
    LISTWHEEL_SetBkColor(hItem, LISTWHEEL_CI_SEL, GUI_LIGHTRED);
    LISTWHEEL_SetBkColor(hItem, LISTWHEEL_CI_UNSEL, GUI_BLACK);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, GUI_WHITE);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, GUI_GRAY);
}

static void ListWheel_SelChangeProc(WM_HWIN hWin, int lwId, int editId)
{
    int  lwItemIndex;
    char *lwBuf;
    WM_HWIN hItem;

    hItem = WM_GetDialogItem(hWin, lwId);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    LISTWHEEL_SetSel(hItem, lwItemIndex);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    hItem = WM_GetDialogItem(hWin, editId);
    EDIT_SetText(hItem, lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void ListWheel_GetText(WM_HWIN hWin,int listwheelId, char *str)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *lwBuf;

    hItem = WM_GetDialogItem(hWin, listwheelId);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    *lwBuf = 0;
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
//    mymemcpy(str,lwBuf, sizeof(*lwBuf));
    sprintf(str, "%s", lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void ListWheel_ResetToLastPos(WM_HWIN hWin)
{
    WM_HWIN hItem;
    int i;
    u8 j;

    for(i=ID_SNSET_LISTWHEEL_YEAR,j=0;i<=ID_SNSET_LISTWHEEL_SN3;i++,j++){
        hItem = WM_GetDialogItem(hWin, i);
        LISTWHEEL_SetPos(hItem, lastLwIndex[j]);
    }
}

static void ListWheel_ResetToZero(WM_HWIN hWin)
{
    WM_HWIN hItem;
    int i;

    for(i=ID_SNSET_LISTWHEEL_0;i<=ID_SNSET_LISTWHEEL_5;i++){
        hItem = WM_GetDialogItem(hWin, i);
        LISTWHEEL_MoveToPos(hItem, 0);
    }
}

static void SerialNum_Comb(WM_HWIN hWin, int id, char *dest_SNumStr)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *lwBuf;

    hItem = WM_GetDialogItem(hWin, id);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    dest_SNumStr = strcat(dest_SNumStr, lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void ListWheel_TestDataFilePathGet(WM_HWIN hWin, char *dest_str)
{
    WM_HWIN hItem;
    FRESULT flErr;
    char    *lwBuf;
    char *swrbTestDataFilePath;

    flErr = flErr;

    swrbTestDataFilePath = mymalloc(SRAMIN, sizeof(char)*40);
    *swrbTestDataFilePath = 0;

    lwBuf = "0:/";
    swrbTestDataFilePath = strcat(swrbTestDataFilePath, lwBuf);

    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_YEAR, swrbTestDataFilePath);
    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_MONTH, swrbTestDataFilePath);
    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_DATE, swrbTestDataFilePath);

    flErr = f_mkdir(swrbTestDataFilePath);

    *swrbTestDataFilePath = 0;

    lwBuf = "0:/";
    swrbTestDataFilePath = strcat(swrbTestDataFilePath, lwBuf);

    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_YEAR, swrbTestDataFilePath);
    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_MONTH, swrbTestDataFilePath);
    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_DATE, swrbTestDataFilePath);

    lwBuf = "/";
    swrbTestDataFilePath = strcat(swrbTestDataFilePath, lwBuf);

    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_SN1, swrbTestDataFilePath);
    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_SN2, swrbTestDataFilePath);
    SerialNum_Comb(hWin, ID_SNSET_LISTWHEEL_SN3, swrbTestDataFilePath);

    lwBuf = ".txt";
    swrbTestDataFilePath = strcat(swrbTestDataFilePath, lwBuf);

    hItem = WM_GetDialogItem(hWin, ID_SNSET_EDIT_COMB_SET);
    EDIT_SetText(hItem, swrbTestDataFilePath);

    hItem = WM_GetDialogItem(hWin_SWRB_PCBTEST, ID_PCBTEST_EDIT_SN);
    EDIT_SetText(hItem, swrbTestDataFilePath);

    sprintf(dest_str, "%s", swrbTestDataFilePath);

    myfree(SRAMIN, swrbTestDataFilePath);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    int     i;

    switch (pMsg->MsgId) {
        case WM_INIT_DIALOG:
            //
            // Initialization of 'SettingDLG'
            //
            hItem = pMsg->hWin;
            FRAMEWIN_SetTextColor(hItem, 0x00000000);
            //
            // Initialization of 'TEXT'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_TEXT_0);
            TEXT_SetFont(hItem, &GUI_Font32_ASCII);
            TEXT_SetTextColor(hItem, GUI_WHITE);
            //
            // Initialization of 'button'
            //
            for(i=ID_SNSET_BUTTON_CONFIRM;i<=ID_SNSET_BUTTON_RESERVE5;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                Button_Init(hItem);
                if(i%2){
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTGRAY);
                }else{

                }
            }
            BUTTON_DispConfirmCHNStr(pMsg->hWin, ID_SNSET_BUTTON_CONFIRM, 18, 43);
            BUTTON_DispCheckCHNStr(pMsg->hWin, ID_SNSET_BUTTON_CHECK, 18, 43);
            BUTTON_DispResetCHNStr(pMsg->hWin, ID_SNSET_BUTTON_RESET, 18, 43);
            BUTTON_DispCancelCHNStr(pMsg->hWin, ID_SNSET_BUTTON_CANCEL, 18, 43);
            BUTTON_DispSerialNumCHNStr(pMsg->hWin, ID_SNSET_BUTTON_SNSET, 14, 18);
            BUTTON_DispTimeCHNStr(pMsg->hWin, ID_SNSET_BUTTON_TIMESET, 26, 18);
            //
            // Initialization of 'lwYear'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_YEAR);
            ListWheel_Init(hItem);
            ListWheel_AddNumString(hItem, 2015, 2025);
            //
            // Initialization of 'lwMonth'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_MONTH);
            ListWheel_Init(hItem);
            ListWheel_AddNumString(hItem, 1, 12);
            //
            // Initialization of 'lwDay'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_DATE);
            ListWheel_Init(hItem);
            ListWheel_AddNumString(hItem, 1, 31);
            //
            // Initialization of 'lwSN1,2,3'
            //
            for(i=ID_SNSET_LISTWHEEL_SN1;i<=ID_SNSET_LISTWHEEL_SN3;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                ListWheel_Init(hItem);
                ListWheel_AddNumString(hItem, 0, 9);
            }
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_SN3);
            LISTWHEEL_SetPos(hItem,1);
            //
            // Initialization of 'edit'
            //
            for(i=ID_SNSET_EDIT_COMB_PREVIOUS;i<=ID_SNSET_EDIT_SN3;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
                EDIT_SetTextMode(hItem);
                EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_EDIT_COMB_PREVIOUS);
            EDIT_SetMaxLen(hItem, 50);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_EDIT_COMB_SET);
            EDIT_SetMaxLen(hItem, 50);
            //Hide SNSetting Window when create
            WM_HideWin(pMsg->hWin);
            break;
        case WM_PAINT:
//            ListWheel_SnapLineDraw(GUI_RED);
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
                case ID_SNSET_BUTTON_CONFIRM: // Notifications sent by 'Confirm'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_ConfirmProc(pMsg->hWin);
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_CHECK: // Notifications sent by 'Check'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_CheckProc(pMsg->hWin);
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_RESET: // Notifications sent by 'Reset'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_ResetProc(pMsg->hWin);
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_CANCEL: // Notifications sent by 'Cancel'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_CancelProc(pMsg->hWin);
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_SNSET: // Notifications sent by 'SnSET'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_TIMESET: // Notifications sent by 'TimeSET'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            hItem = WM_GetDialogItem(hWin_SWRB_TIMESETTING, ID_TIMESET_BUTTON_TIMESET);
                            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);
                            BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_BLACK);
                            BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
                            gSwrbTestSetState = SWRB_TEST_SET_STATE_TIME;
                            WM_HideWin(pMsg->hWin);
                            WM_ShowWin(hWin_SWRB_TIMESETTING);
                            break;
                    }
                    break;
                  case ID_SNSET_BUTTON_TESTSELECT: // Notifications sent by 'Test Sel'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            hItem = WM_GetDialogItem(hWin_SWRB_TIMESETTING, ID_TESTSEL_BUTTON_TESTSELSET);
                            BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);
                            BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_BLACK);
                            BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
                            gSwrbTestSetState = SWRB_TEST_SET_STATE_TESTSEL;
                            WM_HideWin(pMsg->hWin);
                            WM_ShowWin(hWin_SWRB_TESTSEL);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_YEAR: // Notifications sent by 'lwYear'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_YEAR, ID_SNSET_EDIT_YEAR);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_MONTH: // Notifications sent by 'lwMonth'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_MONTH, ID_SNSET_EDIT_MONTH);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_DATE: // Notifications sent by 'lwDay'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_DATE, ID_SNSET_EDIT_DAY);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_SN1: // Notifications sent by 'lwSN1'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_SN1, ID_SNSET_EDIT_SN1);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_SN2: // Notifications sent by 'lwSN2'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_SN2, ID_SNSET_EDIT_SN2);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_SN3: // Notifications sent by 'lwSN3'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_SN3, ID_SNSET_EDIT_SN3);
                            break;
                    }
                    break;
                }
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_SNSETTING;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

/*********************************************************************
*
*       CreateSNSettingDLG
*/
WM_HWIN CreateSNSettingDLG(void) {
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_SWRB_PCBTEST, 0, 0);
    return hWin;
}


void SWRB_ListWheelLastItemPosGet(WM_HWIN hWin)
{
    WM_HWIN hItem;
    int i;
    u8 j;

    for(i=ID_SNSET_LISTWHEEL_YEAR,j=0;i<=ID_SNSET_LISTWHEEL_SN3;i++,j++){
        hItem = WM_GetDialogItem(hWin, i);
        lastLwIndex[j] = LISTWHEEL_GetPos(hItem);
    }
}

void SWRB_ListWheelRTCDateUpdate(WM_HWIN hWin, int idYear, int idMonth, int idDay)
{
    WM_HWIN hItem;
    int     lwItemIndex;

    RTC_GetDate(RTC_Format_BIN, &rtcDate);

    /*ListWheel Date Update */
    lwItemIndex = rtcDate.RTC_Year-15;
    hItem = WM_GetDialogItem(hWin, idYear);
    LISTWHEEL_SetPos(hItem, lwItemIndex);
    LISTWHEEL_SetSel(hItem, lwItemIndex);

    lwItemIndex = rtcDate.RTC_Month-1;
    hItem = WM_GetDialogItem(hWin, idMonth);
    LISTWHEEL_SetPos(hItem, lwItemIndex);
    LISTWHEEL_SetSel(hItem, lwItemIndex);

    lwItemIndex = rtcDate.RTC_Date-1;
    hItem = WM_GetDialogItem(hWin, idDay);
    LISTWHEEL_SetPos(hItem, lwItemIndex);
    LISTWHEEL_SetSel(hItem, lwItemIndex);
}

void SWRB_ListWheelSNInc(WM_HWIN hWin)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *strSN1,*strSN2,*strSN3;
    char *str;

    strSN3 = mymalloc(SRAMIN, sizeof(char)*3);
    strSN2 = mymalloc(SRAMIN, sizeof(char)*3);
    strSN1 = mymalloc(SRAMIN, sizeof(char)*3);

    ListWheel_GetText(hWin, ID_SNSET_LISTWHEEL_SN3, strSN3);
    if(*strSN3 != '9'){
        hItem = WM_GetDialogItem(hWin, ID_SNSET_LISTWHEEL_SN3);
        lwItemIndex = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetPos(hItem, lwItemIndex+1);
        LISTWHEEL_SetSel(hItem, lwItemIndex+1);
    }else{
        hItem = WM_GetDialogItem(hWin, ID_SNSET_LISTWHEEL_SN3);
        LISTWHEEL_SetPos(hItem, 0);
        LISTWHEEL_SetSel(hItem, 0);

        ListWheel_GetText(hWin, ID_SNSET_LISTWHEEL_SN2, strSN2);
        if(*strSN2 != '9'){
            hItem = WM_GetDialogItem(hWin, ID_SNSET_LISTWHEEL_SN2);
            lwItemIndex = LISTWHEEL_GetPos(hItem);
            LISTWHEEL_SetPos(hItem, lwItemIndex+1);
            LISTWHEEL_SetSel(hItem, lwItemIndex+1);
        }else{
            hItem = WM_GetDialogItem(hWin, ID_SNSET_LISTWHEEL_SN2);
            LISTWHEEL_SetPos(hItem, 0);
            LISTWHEEL_SetSel(hItem, 0);

            ListWheel_GetText(hWin, ID_SNSET_LISTWHEEL_SN1, strSN1);
            if(*strSN1 != '9'){
                hItem = WM_GetDialogItem(hWin, ID_SNSET_LISTWHEEL_SN1);
                lwItemIndex = LISTWHEEL_GetPos(hItem);
                LISTWHEEL_SetPos(hItem, lwItemIndex+1);
                LISTWHEEL_SetSel(hItem, lwItemIndex+1);
            }else{
                str = "SerialNumber is larger than 999, return to 0\r\n";
                SWRB_TestDataFileWriteString(str);
                MultiEdit_Add_Text(hWin_SWRB_PCBTEST, ID_PCBTEST_MULTIEDIT_MAIN, str);
                hItem = WM_GetDialogItem(hWin, ID_SNSET_LISTWHEEL_SN1);
                LISTWHEEL_SetPos(hItem, 0);
                LISTWHEEL_SetSel(hItem, 0);
            }
        }
    }

    myfree(SRAMIN, strSN1);
    myfree(SRAMIN, strSN2);
    myfree(SRAMIN, strSN3);
}

FRESULT SWRB_TestDataFileOpen(u8 fileOpenMode)
{
    FRESULT flErr;
    char *pathStr;

    pathStr = mymalloc(SRAMIN, sizeof(char)*40);
    *pathStr = 0;

    ListWheel_TestDataFilePathGet(hWin_SWRB_SNSETTING, pathStr);
    flErr = f_open(file, pathStr, fileOpenMode);
    myfree(SRAMIN, pathStr);
    f_lseek(file, file->fsize);

    return flErr;
}

void SWRB_TestDataSaveToFile(void dataSaveProc(void))
{
    SWRB_TestDataFileOpen(FA_WRITE|FA_OPEN_ALWAYS);
    dataSaveProc();
    f_close(file);
}

void SWRB_TestDataFileWriteSN(void)
{
    char *swrbTestSerialNum;
    char *cBuf;

    SWRB_TestDataFileOpen(FA_WRITE|FA_OPEN_ALWAYS);

    swrbTestSerialNum = mymalloc(SRAMIN, sizeof(char)*50);
    mymemset(swrbTestSerialNum, 0, sizeof(char)*50);

    *swrbTestSerialNum = 0;

    cBuf = "\nSerialNumber:";

    swrbTestSerialNum = strcat(swrbTestSerialNum, cBuf);

    SerialNum_Comb(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_YEAR, swrbTestSerialNum);
    SerialNum_Comb(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_MONTH, swrbTestSerialNum);
    SerialNum_Comb(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_DATE, swrbTestSerialNum);
    SerialNum_Comb(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_SN1, swrbTestSerialNum);
    SerialNum_Comb(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_SN2, swrbTestSerialNum);
    SerialNum_Comb(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_SN3, swrbTestSerialNum);

    f_printf(file, "%s\r\n", swrbTestSerialNum);

    f_close(file);
    
    MultiEdit_Add_Text(hWin_SWRB_PCBTEST, ID_PCBTEST_MULTIEDIT_MAIN, swrbTestSerialNum);

    myfree(SRAMIN, swrbTestSerialNum);
}

void SWRB_TestDUTWriteSN(void)
{
    char *str;
    int tempSN;

    printf("SNW->ERS\r\n");
    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    str = mymalloc(SRAMIN, sizeof(char)*10);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_YEAR, str);
    printf("SNW->YEAR=%s\r\n", str);
    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_MONTH, str);
    printf("SNW->MNTH=%s\r\n", str);
    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_DATE, str);
    printf("SNW->DATE=%s\r\n", str);
    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_SN1, str);
    tempSN = 0;
    tempSN += 100*(*str-'0');

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_SN2, str);
    tempSN += 10*(*str-'0');

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSETTING, ID_SNSET_LISTWHEEL_SN3, str);
    tempSN += *str-'0';

    printf("SNW->SN=%d\r\n", tempSN);
    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    myfree(SRAMIN, str);
}

/*************************** End of file ****************************/
