/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"

#include "sweeprobot_testing.h"
#include "rtc.h"
#include <stdio.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

extern GUI_CONST_STORAGE GUI_BITMAP _bmConfirmCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmCheckCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmResetCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmCancelCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmTestselCHN;

extern GUI_CONST_STORAGE GUI_BITMAP _bmSerialNumCHN;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static int  lastLwIndex[6];
static RTC_DateTypeDef rtcDate;

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "TEST SETTING", ID_SNSET_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "Set Serial Number", ID_SNSET_TEXT_TITLE, 20, 10, 680, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SerialNum", ID_SNSET_BUTTON_TITLE, 20, 0, 680, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Confirm", ID_SNSET_BUTTON_CONFIRM, 700, 0, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Check", ID_SNSET_BUTTON_CHECK, 700, 120, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Reset", ID_SNSET_BUTTON_RESET, 700, 240, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Cancel", ID_SNSET_BUTTON_CANCEL, 700, 360, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SNSet", ID_SNSET_BUTTON_SNSET, 0, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "TestSel", ID_SNSET_BUTTON_TESTSELECT, 100, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv2", ID_SNSET_BUTTON_RESERVE2, 200, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv3", ID_SNSET_BUTTON_RESERVE3, 300, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv4", ID_SNSET_BUTTON_RESERVE4, 400, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Rsrv5", ID_SNSET_BUTTON_RESERVE5, 500, 420, 100, 60, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "TimeSet", ID_SNSET_BUTTON_TIMESET, 600, 420, 100, 60, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwYear", ID_SNSET_LISTWHEEL_YEAR, 20, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwMonth", ID_SNSET_LISTWHEEL_MONTH, 130, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwDay", ID_SNSET_LISTWHEEL_DATE, 240, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN1", ID_SNSET_LISTWHEEL_SN1, 350, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN2", ID_SNSET_LISTWHEEL_SN2, 460, 60, 110, 230, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "lwSN3", ID_SNSET_LISTWHEEL_SN3, 570, 60, 110, 230, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "editComb", ID_SNSET_EDIT_COMB_SET, 20, 340, 660, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editYear", ID_SNSET_EDIT_YEAR, 20, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editMonth", ID_SNSET_EDIT_MONTH, 130, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editDay", ID_SNSET_EDIT_DAY, 240, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN1", ID_SNSET_EDIT_SN1, 350, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN2", ID_SNSET_EDIT_SN2, 460, 300, 110, 40, 0 ,0x0, 0 },
    { EDIT_CreateIndirect, "editSN3", ID_SNSET_EDIT_SN3, 570, 300, 110, 40, 0 ,0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void ListWheel_ResetToLastPos(void);
static void ListWheel_ResetToZero(void);

static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetFocussable(hItem, DISABLE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_3D);
}

static void Button_ConfirmProc(void)
{
    gSwrbDialogSelectFlag = SWRB_DIALOG_SELECT_NONE;
    gSwrbTestMode = SWRB_TEST_MODE_IDLE;

    SWRB_TestDataFilePathDisp(hWin_SWRB_PCBTEST, ID_PCBTEST_EDIT_SN);

    WM_HideWin(hWin_SWRB_SNSET);
    WM_ShowWin(hWin_SWRB_START);
    WM_BringToTop(hWin_SWRB_START);
}

static void Button_CheckProc(void)
{
    SWRB_TestDataFilePathDisp(hWin_SWRB_SNSET, ID_SNSET_EDIT_COMB_SET);
}

static void Button_ResetProc(void)
{
    ListWheel_ResetToZero();
}

static void Button_CancelProc()
{
    gSwrbDialogSelectFlag = SWRB_DIALOG_SELECT_NONE;
    gSwrbTestMode = SWRB_TEST_MODE_IDLE;

    ListWheel_ResetToLastPos();
    WM_HideWin(hWin_SWRB_SNSET);
    WM_ShowWin(hWin_SWRB_START);
}

static void ListWheel_Init(WM_HWIN hItem)
{
    LISTWHEEL_SetFont(hItem, GUI_FONT_32B_ASCII);
    LISTWHEEL_SetDeceleration(hItem, 10);
    LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTWHEEL_SetSnapPosition(hItem, 115);
//    LISTWHEEL_SetBkColor(hItem, LISTWHEEL_CI_SEL, GUI_LIGHTRED);
//    LISTWHEEL_SetBkColor(hItem, LISTWHEEL_CI_UNSEL, GUI_BLACK);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, GUI_RED);
    LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, GUI_LIGHTGRAY);
}

static void ListWheel_SelChangeProc(WM_HWIN hWin, int lwId, int editId)
{
    int  lwItemIndex;
    char *lwBuf;
    WM_HWIN hItem;

    hItem = WM_GetDialogItem(hWin, lwId);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    LISTWHEEL_SetSel(hItem, lwItemIndex);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    hItem = WM_GetDialogItem(hWin, editId);
    EDIT_SetText(hItem, lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void ListWheel_GetText(WM_HWIN hWin,int listwheelId, char *str)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *lwBuf;

    hItem = WM_GetDialogItem(hWin, listwheelId);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    *lwBuf = 0;
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    sprintf(str, "%s", lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void ListWheel_ResetToLastPos(void)
{
    WM_HWIN hItem;
    int i;
    u8 j;

    for(i=ID_SNSET_LISTWHEEL_YEAR,j=0;i<=ID_SNSET_LISTWHEEL_SN3;i++,j++){
        hItem = WM_GetDialogItem(hWin_SWRB_SNSET, i);
        LISTWHEEL_SetPos(hItem, lastLwIndex[j]);
    }
}

static void ListWheel_ResetToZero(void)
{
    WM_HWIN hItem;
    int i;

    for(i=ID_SNSET_LISTWHEEL_0;i<=ID_SNSET_LISTWHEEL_5;i++){
        hItem = WM_GetDialogItem(hWin_SWRB_SNSET, i);
        LISTWHEEL_MoveToPos(hItem, 0);
    }
}

static void ListWheel_TextGet(WM_HWIN hWin, int id, char *dest_str)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *lwBuf;

    hItem = WM_GetDialogItem(hWin, id);
    lwItemIndex = LISTWHEEL_GetPos(hItem);
    lwBuf = mymalloc(SRAMIN, sizeof(char)*10);
    LISTWHEEL_GetItemText(hItem, lwItemIndex, lwBuf, 10);
    sprintf((char*)dest_str, "%s", lwBuf);
    myfree(SRAMIN, lwBuf);
}

static void SweepRobotTest_TestDataFileFolderPathGet(char *dest_str)
{
    char *strSNYear,*strSNMonth, *strSNDate;

    strSNYear = mymalloc(SRAMIN, sizeof(char)*10);
    *strSNYear = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_YEAR, strSNYear);

    strSNMonth = mymalloc(SRAMIN, sizeof(char)*10);
    *strSNMonth = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_MONTH, strSNMonth);

    strSNDate = mymalloc(SRAMIN, sizeof(char)*10);
    *strSNDate = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_DATE, strSNDate);

    if(gSwrbTestSDCardInsertState){
        sprintf(dest_str, "0:/%s%02d%02d", strSNYear, atoi(strSNMonth), atoi(strSNDate));
    }else if(gSwrbTestUDiskInsertState){
        sprintf(dest_str, "2:/%s%02d%02d", strSNYear, atoi(strSNMonth), atoi(strSNDate));
    }

    myfree(SRAMIN, (void*)strSNYear);
    myfree(SRAMIN, (void*)strSNMonth);
    myfree(SRAMIN, (void*)strSNDate);
}

static FRESULT SweepRobotTest_TestDataFileFolderMkdir(void)
{
    FRESULT flErr;
    char *strFolderPath;
    int cnt;

    strFolderPath = mymalloc(SRAMIN, sizeof(char)*20);
    *strFolderPath = 0;

    cnt = 0;

    if(gSwrbTestSDCardInsertState){
        do{
            SweepRobotTest_TestDataFileFolderPathGet(strFolderPath);
            cnt++;
        }while((*(strFolderPath) != '0' && *(strFolderPath+1) != ':') && cnt<10);
    }else if (gSwrbTestUDiskInsertState){
        do{
            SweepRobotTest_TestDataFileFolderPathGet(strFolderPath);
            cnt++;
        }while((*(strFolderPath) != '2' && *(strFolderPath+1) != ':') && cnt<10);
    }

    if(cnt < 10){
        flErr = f_mkdir(strFolderPath);
        return flErr;
    }

    myfree(SRAMIN, strFolderPath);

    return flErr;
}

static void SweepRobotTest_TestDataFileNameGet(char *dest_str)
{
    char *strSN1, *strSN2, *strSN3;

    strSN1 = mymalloc(SRAMIN, sizeof(char)*3);
    *strSN1 = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN1, strSN1);

    strSN2 = mymalloc(SRAMIN, sizeof(char)*3);
    *strSN2 = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN2, strSN2);

    strSN3 = mymalloc(SRAMIN, sizeof(char)*3);
    *strSN3 = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN3, strSN3);

    sprintf(dest_str, "%s%s%s.txt", strSN1, strSN2, strSN3);

    myfree(SRAMIN, (void*)strSN1);
    myfree(SRAMIN, (void*)strSN2);
    myfree(SRAMIN, (void*)strSN3);
}

static void SweepRobotTest_TestDataFilePathGet(char *dest_str)
{
    char *strTestDataFileFolderPath;
    char *strTestDataFileNamePath;

    strTestDataFileFolderPath = mymalloc(SRAMIN, sizeof(char)*50);
    *strTestDataFileFolderPath = 0;
    SweepRobotTest_TestDataFileFolderPathGet(strTestDataFileFolderPath);

    strTestDataFileNamePath = mymalloc(SRAMIN, sizeof(char)*50);
    *strTestDataFileNamePath = 0;
    SweepRobotTest_TestDataFileNameGet(strTestDataFileNamePath);

    sprintf(dest_str, "%s/%s", strTestDataFileFolderPath, strTestDataFileNamePath);

    myfree(SRAMIN, strTestDataFileFolderPath);
    myfree(SRAMIN, strTestDataFileNamePath);
}

static void ListWheel_TestDataFileSerialNumberGen(char *dest_str)
{
    char *strSNYear,*strSNMonth, *strSNDate;
    char *strSN1, *strSN2, *strSN3;

    strSNYear = mymalloc(SRAMIN, sizeof(char)*6);
    *strSNYear = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_YEAR, strSNYear);

    strSNMonth = mymalloc(SRAMIN, sizeof(char)*4);
    *strSNMonth = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_MONTH, strSNMonth);

    strSNDate = mymalloc(SRAMIN, sizeof(char)*4);
    *strSNDate = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_DATE, strSNDate);

    strSN1 = mymalloc(SRAMIN, sizeof(char)*3);
    *strSN1 = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN1, strSN1);

    strSN2 = mymalloc(SRAMIN, sizeof(char)*3);
    *strSN2 = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN2, strSN2);

    strSN3 = mymalloc(SRAMIN, sizeof(char)*3);
    *strSN3 = 0;
    ListWheel_TextGet(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN3, strSN3);

    sprintf(dest_str, "SerialNumber: %s%02d%02d%s%s%s", strSNYear, atoi(strSNMonth), atoi(strSNDate), strSN1, strSN2, strSN3);

    myfree(SRAMIN, (void*)strSNYear);
    myfree(SRAMIN, (void*)strSNMonth);
    myfree(SRAMIN, (void*)strSNDate);
    myfree(SRAMIN, (void*)strSN1);
    myfree(SRAMIN, (void*)strSN2);
    myfree(SRAMIN, (void*)strSN3);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    int     i;

    switch (pMsg->MsgId) {
        case WM_INIT_DIALOG:

            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_TEXT_TITLE);
            TEXT_SetFont(hItem, &GUI_Font32_ASCII);

            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_BUTTON_TITLE);
            BUTTON_SetSkinClassic(hItem);
            WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
            BUTTON_SetText(hItem, "");
            BUTTON_Set_Bitmap_Ex(pMsg->hWin, ID_SNSET_BUTTON_TITLE, &_bmSerialNumCHN, 0, 13);
            Button_Set_BkColor(pMsg->hWin, ID_SNSET_BUTTON_TITLE, GUI_WHITE);
            //
            // Initialization of 'button'
            //
            for(i=ID_SNSET_BUTTON_CONFIRM;i<=ID_SNSET_BUTTON_RESERVE5;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                Button_Init(hItem);
                if(i%2){
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_LIGHTGRAY);
                }else{

                }
            }
            BUTTON_DispConfirmCHNStr(pMsg->hWin, ID_SNSET_BUTTON_CONFIRM, 18, 43);
            BUTTON_DispCheckCHNStr(pMsg->hWin, ID_SNSET_BUTTON_CHECK, 18, 43);
            BUTTON_DispResetCHNStr(pMsg->hWin, ID_SNSET_BUTTON_RESET, 18, 43);
            BUTTON_DispCancelCHNStr(pMsg->hWin, ID_SNSET_BUTTON_CANCEL, 18, 43);
            BUTTON_DispSerialNumCHNStr(pMsg->hWin, ID_SNSET_BUTTON_SNSET, 14, 18);
            BUTTON_DispTimeCHNStr(pMsg->hWin, ID_SNSET_BUTTON_TIMESET, 26, 18);
            BUTTON_DispTestSelCHNStr(pMsg->hWin, ID_SNSET_BUTTON_TESTSELECT, 14, 18);
            //
            // Initialization of 'lwYear'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_YEAR);
            ListWheel_Init(hItem);
            ListWheel_AddNumString(hItem, 2015, 2025);
            //
            // Initialization of 'lwMonth'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_MONTH);
            ListWheel_Init(hItem);
            ListWheel_AddNumString(hItem, 1, 12);
            //
            // Initialization of 'lwDay'
            //
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_DATE);
            ListWheel_Init(hItem);
            ListWheel_AddNumString(hItem, 1, 31);
            //
            // Initialization of 'lwSN1,2,3'
            //
            for(i=ID_SNSET_LISTWHEEL_SN1;i<=ID_SNSET_LISTWHEEL_SN3;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                ListWheel_Init(hItem);
                ListWheel_AddNumString(hItem, 0, 9);
            }
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_LISTWHEEL_SN3);
            LISTWHEEL_SetPos(hItem,1);
            //
            // Initialization of 'edit'
            //
            for(i=ID_SNSET_EDIT_COMB_PREVIOUS;i<=ID_SNSET_EDIT_SN3;i++){
                hItem = WM_GetDialogItem(pMsg->hWin, i);
                EDIT_SetFont(hItem, GUI_FONT_24_ASCII);
                EDIT_SetTextMode(hItem);
                EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
            }
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_EDIT_COMB_PREVIOUS);
            EDIT_SetMaxLen(hItem, 50);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SNSET_EDIT_COMB_SET);
            EDIT_SetMaxLen(hItem, 50);
            //Hide SNSetting Window when create
            WM_HideWin(pMsg->hWin);
            break;
        case WM_PAINT:
            break;
        case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {
                case ID_SNSET_BUTTON_CONFIRM: // Notifications sent by 'Confirm'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_ConfirmProc();
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_CHECK: // Notifications sent by 'Check'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_CheckProc();
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_RESET: // Notifications sent by 'Reset'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_ResetProc();
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_CANCEL: // Notifications sent by 'Cancel'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_CancelProc();
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_SNSET: // Notifications sent by 'SnSET'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                    }
                    break;
                case ID_SNSET_BUTTON_TIMESET: // Notifications sent by 'TimeSET'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_Set_BkColor(hWin_SWRB_TIMESET, ID_TIMESET_BUTTON_TIMESET, GUI_LIGHTRED);
                            gSwrbTestSetSelectFlag = SWRB_TEST_SET_SELECT_TIME;
                            WM_HideWin(pMsg->hWin);
                            WM_ShowWin(hWin_SWRB_TIMESET);
                            break;
                    }
                    break;
                  case ID_SNSET_BUTTON_TESTSELECT: // Notifications sent by 'Test Sel'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            Button_Set_BkColor(hWin_SWRB_TESTSEL, ID_TESTSEL_BUTTON_TESTSEL, GUI_LIGHTRED);
                            gSwrbTestSetSelectFlag = SWRB_TEST_SET_SELECT_TESTSEL;
                            WM_HideWin(pMsg->hWin);
                            WM_ShowWin(hWin_SWRB_TESTSEL);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_YEAR: // Notifications sent by 'lwYear'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_YEAR, ID_SNSET_EDIT_YEAR);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_MONTH: // Notifications sent by 'lwMonth'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_MONTH, ID_SNSET_EDIT_MONTH);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_DATE: // Notifications sent by 'lwDay'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_DATE, ID_SNSET_EDIT_DAY);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_SN1: // Notifications sent by 'lwSN1'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_SN1, ID_SNSET_EDIT_SN1);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_SN2: // Notifications sent by 'lwSN2'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_SN2, ID_SNSET_EDIT_SN2);
                            break;
                    }
                    break;
                case ID_SNSET_LISTWHEEL_SN3: // Notifications sent by 'lwSN3'
                    switch(NCode) {
                        case WM_NOTIFICATION_CLICKED:
                            break;
                        case WM_NOTIFICATION_RELEASED:
                            break;
                        case WM_NOTIFICATION_SEL_CHANGED:
                            ListWheel_SelChangeProc(pMsg->hWin, ID_SNSET_LISTWHEEL_SN3, ID_SNSET_EDIT_SN3);
                            break;
                    }
                    break;
                }
        default:
            WM_DefaultProc(pMsg);
            break;
    }
}

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_SNSET;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

/*********************************************************************
*
*       CreateSNSettingDLG
*/
WM_HWIN CreateSNSettingDLG(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWin_SWRB_PCBTEST, 0, 0);
    return hWin;
}


void SWRB_ListWheelLastItemPosGet(void)
{
    WM_HWIN hItem;
    int i;
    u8 j;

    for(i=ID_SNSET_LISTWHEEL_YEAR,j=0;i<=ID_SNSET_LISTWHEEL_SN3;i++,j++){
        hItem = WM_GetDialogItem(hWin_SWRB_SNSET, i);
        lastLwIndex[j] = LISTWHEEL_GetPos(hItem);
    }
}

void SWRB_ListWheelRTCDateUpdate(WM_HWIN hWin, int idYear, int idMonth, int idDay)
{
    WM_HWIN hItem;
    int     lwItemIndex;

    RTC_GetDate(RTC_Format_BIN, &rtcDate);

    /*ListWheel Date Update */
    lwItemIndex = rtcDate.RTC_Year-15;
    hItem = WM_GetDialogItem(hWin, idYear);
    LISTWHEEL_SetPos(hItem, lwItemIndex);
    LISTWHEEL_SetSel(hItem, lwItemIndex);

    lwItemIndex = rtcDate.RTC_Month-1;
    hItem = WM_GetDialogItem(hWin, idMonth);
    LISTWHEEL_SetPos(hItem, lwItemIndex);
    LISTWHEEL_SetSel(hItem, lwItemIndex);

    lwItemIndex = rtcDate.RTC_Date-1;
    hItem = WM_GetDialogItem(hWin, idDay);
    LISTWHEEL_SetPos(hItem, lwItemIndex);
    LISTWHEEL_SetSel(hItem, lwItemIndex);
}

void SWRB_TestCurSNInc(void)
{
    WM_HWIN hItem;
    int     lwItemIndex;
    char    *strSN1,*strSN2,*strSN3;
    char *str;

    strSN3 = mymalloc(SRAMIN, sizeof(char)*3);
    strSN2 = mymalloc(SRAMIN, sizeof(char)*3);
    strSN1 = mymalloc(SRAMIN, sizeof(char)*3);

    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN3, strSN3);
    if(*strSN3 != '9'){
        hItem = WM_GetDialogItem(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN3);
        lwItemIndex = LISTWHEEL_GetPos(hItem);
        LISTWHEEL_SetPos(hItem, lwItemIndex+1);
        LISTWHEEL_SetSel(hItem, lwItemIndex+1);
    }else{
        hItem = WM_GetDialogItem(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN3);
        LISTWHEEL_SetPos(hItem, 0);
        LISTWHEEL_SetSel(hItem, 0);

        ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN2, strSN2);
        if(*strSN2 != '9'){
            hItem = WM_GetDialogItem(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN2);
            lwItemIndex = LISTWHEEL_GetPos(hItem);
            LISTWHEEL_SetPos(hItem, lwItemIndex+1);
            LISTWHEEL_SetSel(hItem, lwItemIndex+1);
        }else{
            hItem = WM_GetDialogItem(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN2);
            LISTWHEEL_SetPos(hItem, 0);
            LISTWHEEL_SetSel(hItem, 0);

            ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN1, strSN1);
            if(*strSN1 != '9'){
                hItem = WM_GetDialogItem(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN1);
                lwItemIndex = LISTWHEEL_GetPos(hItem);
                LISTWHEEL_SetPos(hItem, lwItemIndex+1);
                LISTWHEEL_SetSel(hItem, lwItemIndex+1);
            }else{
                str = "SerialNumber is larger than 999, return to 0\r\n";
                SWRB_TestDataFileWriteString(str);
                MultiEdit_Add_Text(hWin_SWRB_PCBTEST, ID_PCBTEST_MULTIEDIT_MAIN, str);
                hItem = WM_GetDialogItem(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN1);
                LISTWHEEL_SetPos(hItem, 0);
                LISTWHEEL_SetSel(hItem, 0);
            }
        }
    }

    myfree(SRAMIN, strSN1);
    myfree(SRAMIN, strSN2);
    myfree(SRAMIN, strSN3);
}

/* TODO: Add Test Data File Create function */
FRESULT SWRB_TestDataFileCreate(void)
{
    FRESULT flErr;
    char *strFilePath;

    strFilePath = mymalloc(SRAMIN, sizeof(char)*50);
    mymemset(strFilePath, 0, sizeof(char)*50);

    SweepRobotTest_TestDataFileFolderMkdir();
    SweepRobotTest_TestDataFilePathGet(strFilePath);

    return flErr;
}

FRESULT SWRB_TestDataFileOpen(u8 fileOpenMode)
{
    FRESULT flErr;
    int cnt;
    char *strFilePath;

    if(gSwrbTestSDCardInsertState || gSwrbTestUDiskInsertState){
        strFilePath = mymalloc(SRAMIN, sizeof(char)*40);
        *strFilePath = 0;

        cnt = 0;
        do{
            SweepRobotTest_TestDataFilePathGet(strFilePath);
            flErr = f_open(file, strFilePath, fileOpenMode);
            switch(flErr){
                case FR_NO_PATH:
                    SweepRobotTest_TestDataFileFolderMkdir();
                    break;
                case FR_INVALID_NAME:
                    SweepRobotTest_TestDataFilePathGet(strFilePath);
                    flErr = f_open(file, strFilePath, fileOpenMode | FA_OPEN_ALWAYS);
                    break;
                case FR_NO_FILE:
                    SweepRobotTest_TestDataFilePathGet(strFilePath);
                    flErr = f_open(file, strFilePath, fileOpenMode | FA_OPEN_ALWAYS);
                    break;
                case FR_DISK_ERR:
                    break;
                default:break;
            }
            cnt++;
        }while(flErr!=FR_OK && cnt<10);

        myfree(SRAMIN, strFilePath);

        cnt = 0;
        do{
            flErr = f_lseek(file, file->fsize);
            cnt++;
        }while(flErr!=FR_OK && cnt<10);
    }else{
        flErr = FR_DISK_ERR;
    }

    return flErr;
}

void SWRB_TestDataSaveToFile(void dataSaveProc(void))
{
    if(gSwrbTestSDCardInsertState || gSwrbTestUDiskInsertState){
        SWRB_TestDataFileOpen(FA_WRITE);    /*|FA_OPEN_ALWAYS*/
        dataSaveProc();
        f_close(file);
    }
}

void SWRB_TestDataFileWriteSN(void)
{
    char *swrbTestSerialNum;

    swrbTestSerialNum = mymalloc(SRAMIN, sizeof(char)*50);
    *swrbTestSerialNum = 0;

    ListWheel_TestDataFileSerialNumberGen(swrbTestSerialNum);

    MultiEdit_Add_Text(hWin_SWRB_PCBTEST, ID_PCBTEST_MULTIEDIT_MAIN, swrbTestSerialNum);

    if(gSwrbTestSDCardInsertState || gSwrbTestUDiskInsertState){
        SWRB_TestDataFileOpen(FA_WRITE);    /*|FA_OPEN_ALWAYS*/
        f_printf(file, "%s\r\n", swrbTestSerialNum);
        f_close(file);
    }

    myfree(SRAMIN, swrbTestSerialNum);
}

void SWRB_TestDUTWriteSN(void)
{
    char *str;
    int tempSN;

    printf("SNW->ERS\r\n");
//    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);
    GUI_Delay(SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    str = mymalloc(SRAMIN, sizeof(char)*10);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_YEAR, str);
    printf("SNW->YEAR=%s\r\n", str);
//    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);
    GUI_Delay(SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_MONTH, str);
    printf("SNW->MNTH=%s\r\n", str);
//    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);
    GUI_Delay(SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_DATE, str);
    printf("SNW->DATE=%s\r\n", str);
//    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);
    GUI_Delay(SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN1, str);
    tempSN = 0;
    tempSN += 100*(*str-'0');

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN2, str);
    tempSN += 10*(*str-'0');

    *str = 0;
    ListWheel_GetText(hWin_SWRB_SNSET, ID_SNSET_LISTWHEEL_SN3, str);
    tempSN += *str-'0';

    printf("SNW->SN=%d\r\n", tempSN);
//    OSTimeDlyHMSM(0,0,0,SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);
    GUI_Delay(SWRB_TEST_DUT_SN_WRITE_WAIT_TIME);

    myfree(SRAMIN, str);
}

void SWRB_TestDataFilePathDisp(WM_HWIN hWin, int id)
{
    WM_HWIN hItem;
    char *str;

    str = mymalloc(SRAMIN, sizeof(char)*50);
    *str = 0;

    SweepRobotTest_TestDataFilePathGet(str);

    hItem = WM_GetDialogItem(hWin, id);
    EDIT_SetText(hItem, str);

    myfree(SRAMIN, str);
}

void SWRB_TestCurSNDisp(WM_HWIN hWin, int idEdit)
{
    WM_HWIN hItem;
    char *strSerialNum;

    strSerialNum = mymalloc(SRAMIN, sizeof(char)*50);
    mymemset(strSerialNum, 0, sizeof(char)*50);

    ListWheel_TestDataFileSerialNumberGen(strSerialNum);

    hItem = WM_GetDialogItem(hWin, idEdit);
    EDIT_SetText(hItem, strSerialNum);

    myfree(SRAMIN, strSerialNum);
}

/*************************** End of file ****************************/
