/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"
#include "sweeprobot_testing.h"
#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define SWRB_MANUL_LISTVIEW_ROW_NUM   17

/* characters for listview header */
extern GUI_CONST_STORAGE GUI_BITMAP _bmTestNameCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmLeftCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmFrontLeftCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmMiddleCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmFrontRightCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmRightCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmBottomLeftCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmBottomFrontLeftCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmBottomFrontRightCHN;
extern GUI_CONST_STORAGE GUI_BITMAP _bmBottomRightCHN;

/* characters for listview item */
extern GUI_CONST_STORAGE GUI_BITMAP _bmWheelCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmBrushCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmFanCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmIFRDCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmFrontIFRDCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmCollisionCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmWheelFloatCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmAshTrayCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmUniWheelCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmIRDACHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmChargeCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmBuzzerCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmRGBLEDCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmKeyCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmPwrStationCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmIntVrefCHN_18;
extern GUI_CONST_STORAGE GUI_BITMAP _bmSerialNumCHN_18;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char *aButton_InitText[][1] = {
    {"WHEEL"},
    {"BRUSH"},
    {"FAN"},
    {"IFRD"},
    {"BUZZER"},
    {"RGB"},
    {"RELAY"},
};

//static const char *aListview_RowInitText[][10] = {
///* item,left,frontLeft,middle,frontRight,right,bottomLeft,bottomFLeft,bottomFRight,bottomRight */
//    {"WHEEL","0","","","","0"},
//    {"BRUSH","0","","0","","0"},
//    {"FAN","","","0","",""},
//    {"IFRD","0","0","","0","0","0","0","0","0"},
//    {"FRT IFRD","0","0","0","0","","0","0","0","0"},
//    {"COLLISION","0","0","","0","0"},
//    {"WHL_FLOAT","0","","","","0"},
//    {"ASH_TRAY","0","0"},
//    {"UNIWHEEL","0"},
//    {"IRDA","0","0","","0","0","0"},
//    {"CHARGE","0","0","0"},
//    {"BUZZER","OFF"},
//    {"RGB_LED","R","G","B"},
//    {"KEY","0"},
//    {"POWER","LL","LS","M","RS","RL","LB","RB","24V"},
//    {"INT_VREF","0"},
//    {"SNUM","0","0","0","0"},
//};

static const char *aListview_RowInitText[][10] = {
/* item,left,frontLeft,middle,frontRight,right,bottomLeft,bottomFLeft,bottomFRight,bottomRight */
    {"","0","","","","0"},
    {"","0","","0","","0"},
    {"","","","0","",""},
    {"","0","0","","0","0","0","0","0","0"},
    {"","0","0","0","0","","0","0","0","0"},
    {"","0","0","","0","0"},
    {"","0","","","","0"},
    {"","0","0"},
    {"","0"},
    {"","0","0","","0","0","0"},
    {"","0","0","0"},
    {"","OFF"},
    {"","R","G","B"},
    {"","0"},
    {"","LL","LS","M","RS","RL","LB","RB","24V"},
    {"","0"},
    {"","0","0","0","0"},
};


//static u8 aListview_RowFlag[SWRB_MANUL_LISTVIEW_ROW_NUM] = { 0 };

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "winSWRBManualTest", ID_MANUAL_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
    { LISTVIEW_CreateIndirect, "lstviewSWRBTest", ID_MANUAL_LISTVIEW_MAIN, 20, 10, 660, 375, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "textTitle", ID_MANUAL_TEXT_TITLE, 20, 10, 655, 60, 0, 0x64, 0 },
    { EDIT_CreateIndirect, "editDate", ID_MANUAL_EDIT_DATE, 510, 435, 170, 30, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "btnStart", ID_MANUAL_BUTTON_START, 700, 0, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnSet", ID_MANUAL_BUTTON_SET, 700, 120, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnReset", ID_MANUAL_BUTTON_RESET, 700, 240, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnExit", ID_MANUAL_BUTTON_EXIT, 700, 360, 100, 120, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnIndicate", ID_MANUAL_BUTTON_INDICATE, 510, 400, 30, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnWheel", ID_MANUAL_BUTTON_WHEEL, 20, 400, 60, 65, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnBrush", ID_MANUAL_BUTTON_BRUSH, 90, 400, 60, 65, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnFan", ID_MANUAL_BUTTON_FAN, 160, 400, 60, 65, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnIFRD", ID_MANUAL_BUTTON_IFRD, 230, 400, 60, 65, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnBuzzer", ID_MANUAL_BUTTON_BUZZER, 300, 400, 60, 65, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnRGB", ID_MANUAL_BUTTON_RGB_LED, 370, 400, 60, 65, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnRelay", ID_MANUAL_BUTTON_RELAY, 440, 400, 60, 65, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "editVolt", ID_MANUAL_EDIT_VOLT, 550, 400, 45, 30, 0, 0x64, 0 },
    { PROGBAR_CreateIndirect, "prgbVolt", ID_MANUAL_PROGBAR_VOLT, 620, 400, 55, 30, 0, 0x0, 0 },
    { PROGBAR_CreateIndirect, "prgbProg", ID_MANUAL_PROGBAR_PROG, 20, 385, 660, 10, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "textVolt", ID_MANUAL_TEXT_VOLT, 600, 400, 20, 30, 0, 0x64, 0 },
};

#ifdef USE_MANUL_TEST_STATE_INDICATE
static const GUI_WIDGET_CREATE_INFO _aManualTestStateIndicateDialogCreate[] = {
    { WINDOW_CreateIndirect, "winManualTestState", ID_MANUAL_WINDOW_TEST_STATE_INDICATE, 0, 0, 500, 360, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "btnManualTestStateIndicate", ID_MANUAL_BUTTON_TEST_STATE_INDICATE, 100, 100, 200, 80, 0, 0x0, 0 },
};
#endif

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetSkinClassic(hItem);
    BUTTON_SetFocussable(hItem, DISABLE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
}

static void Listview_Init(WM_HWIN hItem)
{
    u8 i;
    HEADER_Handle hHeader;

    LISTVIEW_SetRowHeight(hItem, 20);
    LISTVIEW_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
    LISTVIEW_SetGridVis(hItem, 1);
    LISTVIEW_SetItemBkColor(hItem, 0, 0, LISTVIEW_CI_UNSEL, 0x00DFCFB3);
    LISTVIEW_SetItemBkColor(hItem, 0, 0, LISTVIEW_CI_UNSEL, 0x00FFFFFF);
    LISTVIEW_SetAutoScrollH(hItem, ENABLE);
    LISTVIEW_SetAutoScrollV(hItem, ENABLE);
    LISTVIEW_SetHeaderHeight(hItem, 30);

    LISTVIEW_AddColumn(hItem, 110, "", GUI_TA_HCENTER | GUI_TA_VCENTER);    //Item
    LISTVIEW_AddColumn(hItem, 45, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //Left
    LISTVIEW_AddColumn(hItem, 55, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //FrontLeft
    LISTVIEW_AddColumn(hItem, 60, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //Middle
    LISTVIEW_AddColumn(hItem, 55, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //FrontRight
    LISTVIEW_AddColumn(hItem, 45, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //Right
    LISTVIEW_AddColumn(hItem, 70, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //BottomLeft
    LISTVIEW_AddColumn(hItem, 70, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //BottomFrontLeft
    LISTVIEW_AddColumn(hItem, 70, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //BottomFrontRight
    LISTVIEW_AddColumn(hItem, 70, "", GUI_TA_HCENTER | GUI_TA_VCENTER);     //BottomRight
    for(i=0;i<SWRB_MANUL_LISTVIEW_ROW_NUM;i++){
        LISTVIEW_AddRow(hItem, aListview_RowInitText[i]);
    }

    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_WHEEL, 19, 0, &_bmWheelCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_BRUSH, 7, 0, &_bmBrushCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_FAN, 31, 0, &_bmFanCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_IFRD, 7, 0, &_bmIFRDCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_FRONT_IFRD, 19, 0, &_bmFrontIFRDCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_COLLISION, 31, 0, &_bmCollisionCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_WHEEL_FLOAT, 19, 0, &_bmWheelFloatCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_ASH_TRAY, 31, 0, &_bmAshTrayCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_UNIWHEEL, 19, 0, &_bmUniWheelCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_IRDA, 7, 0, &_bmIRDACHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_CHARGE, 31, 0, &_bmChargeCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_BUZZER, 19, 0, &_bmBuzzerCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_RGB_LED, 19, 0, &_bmRGBLEDCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_KEY, 31, 0, &_bmKeyCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_POWER_STATION, 19, 0, &_bmPwrStationCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_INT_VREF, 7, 0, &_bmIntVrefCHN_18);
    LISTVIEW_SetItemBitmap(hItem, SWRB_MANUAL_TEST_LISTVIEW_COLUMN_ITEM, SWRB_MANUAL_TEST_LISTVIEW_ROW_SNUM, 19, 0, &_bmSerialNumCHN_18);

    hHeader = LISTVIEW_GetHeader(hItem);
    HEADER_SetFont(hHeader, GUI_FONT_COMIC18B_ASCII);
    HEADER_SetBitmapEx(hHeader, 0, &_bmTestNameCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 1, &_bmLeftCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 2, &_bmFrontLeftCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 3, &_bmMiddleCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 4, &_bmFrontRightCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 5, &_bmRightCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 6, &_bmBottomLeftCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 7, &_bmBottomFrontLeftCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 8, &_bmBottomFrontRightCHN, 0, 0);
    HEADER_SetBitmapEx(hHeader, 9, &_bmBottomRightCHN, 0, 0);
};

static void SWRB_MANUL_PAINT_Proc(void)
{
    GUI_SetColor(GUI_GRAY);
    GUI_DrawRect(669, 410, 675, 420);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_LISTVIEW_MAIN);
    Listview_Init(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_TEXT_TITLE);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, 0x00CB8872);
    TEXT_SetText(hItem, "SWRB Manual Test");
    TEXT_SetFont(hItem, GUI_FONT_32B_ASCII);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_EDIT_DATE);
    EDIT_SetFont(hItem, GUI_FONT_20_ASCII);
    EDIT_SetText(hItem, "");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, GUI_BLUE);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_EDIT_VOLT);
    EDIT_SetFont(hItem, GUI_FONT_20_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    EDIT_SetMaxLen(hItem, 5);
    EDIT_SetFloatMode(hItem, 0.0, 0, 20, 2, GUI_EDIT_NORMAL|GUI_EDIT_SUPPRESS_LEADING_ZEROES);
    EDIT_SetFloatValue(hItem, 0);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_TEXT_VOLT);
    TEXT_SetFont(hItem, GUI_FONT_20_ASCII);
    TEXT_SetText(hItem, "V");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_BUTTON_START);
    Button_Init(hItem);
    BUTTON_DispStartCHNStr(pMsg->hWin, ID_MANUAL_BUTTON_START, 18, 43);
    Button_Set_BkColor(pMsg->hWin, ID_MANUAL_BUTTON_START, GUI_LIGHTBLUE);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_BUTTON_SET);
    Button_Init(hItem);
    if(gSwrbTestManualSubMode == SWRB_TEST_MANUL_SUB_MODE_AUTO)
        BUTTON_DispAutoModeCHNStr(pMsg->hWin, ID_MANUAL_BUTTON_SET, 18, 43);
    else{
        BUTTON_DispManualModeCHNStr(pMsg->hWin, ID_MANUAL_BUTTON_SET, 18, 43);
    }
    Button_Set_BkColor(pMsg->hWin, ID_MANUAL_BUTTON_SET, GUI_LIGHTGREEN);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_BUTTON_RESET);
    Button_Init(hItem);
    BUTTON_DispResetCHNStr(pMsg->hWin, ID_MANUAL_BUTTON_RESET, 18, 43);
    Button_Set_BkColor(pMsg->hWin, ID_MANUAL_BUTTON_RESET, GUI_LIGHTRED);
    WM_DisableWindow(hItem);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_BUTTON_EXIT);
    Button_Init(hItem);
    BUTTON_DispExitCHNStr(pMsg->hWin, ID_MANUAL_BUTTON_EXIT, 18, 43);
    Button_Set_BkColor(pMsg->hWin, ID_MANUAL_BUTTON_EXIT, GUI_LIGHTGREEN);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_MANUAL_BUTTON_INDICATE);
    Button_Init(hItem);
    BUTTON_SetText(hItem, "");

    for(Id=ID_MANUAL_BUTTON_WHEEL;Id<ID_MANUAL_BUTTON_BOUND;Id++){
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        Button_Init(hItem);
        BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
        BUTTON_SetText(hItem, aButton_InitText[Id-ID_MANUAL_BUTTON_WHEEL][0]);
        WM_DisableWindow(hItem);
    }

    WM_HideWin(pMsg->hWin);
    break;
  case WM_PAINT:
    SWRB_MANUL_PAINT_Proc();
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_MANUAL_BUTTON_START: // Notifications sent by 'btnStart'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualStartBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_SET: // Notifications sent by 'btnSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualSetBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_RESET: // Notifications sent by 'btnReset'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualResetBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_EXIT: // Notifications sent by 'btnExit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualExitBtnProc();
        break;
      }
      break;
    case ID_MANUAL_LISTVIEW_MAIN: // Notifications sent by 'lstviewSWRBTest'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        break;
      }
      break;
    case ID_MANUAL_EDIT_DATE: // Notifications sent by 'editDate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        break;
      }
      break;
    case ID_MANUAL_BUTTON_INDICATE: // Notifications sent by 'btnIndicate'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_MANUAL_BUTTON_WHEEL: // Notifications sent by 'btnWheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualWheelBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_BRUSH: // Notifications sent by 'btnBrush'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualBrushBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_FAN: // Notifications sent by 'btnFan'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualFanBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_IFRD: // Notifications sent by 'btnIFRD'
        switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            break;
          case WM_NOTIFICATION_RELEASED:
            SweepRobot_ManualIFRDBtnProc();
            break;
        }
        break;
    case ID_MANUAL_BUTTON_BUZZER: // Notifications sent by 'btnBuzzer'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualBuzzerBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_RGB_LED: // Notifications sent by 'btnRgbLed'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualRGBLEDBtnProc();
        break;
      }
      break;
    case ID_MANUAL_BUTTON_RELAY: // Notifications sent by 'btnRelay'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        SweepRobot_ManualRELAYBtnProc();
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
WM_HWIN hWin_SWRB_MANUAL;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateManualTestDLG
*/
WM_HWIN CreateManualTestDLG(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/*************************** End of file ****************************/
