/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "EJE_SWRB_TEST_DLG_Conf.h"

#include "swrbTestDriver.h"
#include "swrbTestStepMotorDriver.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define SWRB_RELAY_NUM      8

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

enum RELAY_CTRL_CHAN{
    RELAY_CTRL_COLLISION_CHAN_L,
    RELAY_CTRL_COLLISION_CHAN_FL,
    RELAY_CTRL_COLLISION_CHAN_R,
    RELAY_CTRL_COLLISION_CHAN_FR,
    RELAY_CTRL_STEP_MOTOR_24V_CHAN,
    RELAY_CTRL_CHARGE_24V_CHAN,
    RELAY_CTRL_STEER_MOTOR_5V_CHAN,
    RELAY_CTRL_IRDA_BOARD_24V_CHAN,
    RELAY_CTRL_CHAN_BOUND,
};

static u8 RelayStateFlag[SWRB_RELAY_NUM] = { 0 };

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "winRelay", ID_RELAYCTRL_WINDOW_MAIN, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnExit", ID_RELAYCTRL_BUTTON_EXIT, 700, 360, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnStart", ID_RELAYCTRL_BUTTON_START, 700, 0, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnSet", ID_RELAYCTRL_BUTTON_SET, 700, 120, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnStop", ID_RELAYCTRL_BUTTON_STOP, 700, 240, 100, 120, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay1", ID_RELAYCTRL_BUTTON_R1, 50, 50, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay2", ID_RELAYCTRL_BUTTON_R2, 200, 50, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay3", ID_RELAYCTRL_BUTTON_R3, 350, 50, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay4", ID_RELAYCTRL_BUTTON_R4, 500, 50, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay5", ID_RELAYCTRL_BUTTON_R5, 50, 300, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay6", ID_RELAYCTRL_BUTTON_R6, 200, 300, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay7", ID_RELAYCTRL_BUTTON_R7, 350, 300, 100, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "btnRelay8", ID_RELAYCTRL_BUTTON_R8, 500, 300, 100, 100, 0, 0x0, 0 },
  
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

void Button_Init(WM_HWIN hItem)
{
    BUTTON_SetSkinClassic(hItem);
    WIDGET_SetEffect(hItem, &WIDGET_Effect_Simple);
}

void Button_StepMotor24VRelayCtrlClickProc(void)
{
    if(RelayStateFlag[RELAY_CTRL_STEP_MOTOR_24V_CHAN]){
        SweepRobotTest_StepMotorPwrOn();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R1, GUI_LIGHTBLUE);
        RelayStateFlag[RELAY_CTRL_STEP_MOTOR_24V_CHAN] = 0;
    }else{
        SweepRobotTest_StepMotorPwrOff();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R1, GUI_LIGHTGRAY);
        RelayStateFlag[RELAY_CTRL_STEP_MOTOR_24V_CHAN] = 1;
    }
}

void Button_Charge24VRelayCtrlClickProc(void)
{
    if(RelayStateFlag[RELAY_CTRL_CHARGE_24V_CHAN]){
        SweepRobot_Charge24VOn();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R2, GUI_LIGHTBLUE);
        RelayStateFlag[RELAY_CTRL_CHARGE_24V_CHAN] = 0;
    }else{
        SweepRobot_Charge24VOff();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R2, GUI_LIGHTGRAY);
        RelayStateFlag[RELAY_CTRL_CHARGE_24V_CHAN] = 1;
    }
}

void Button_SteerMotor5VRelayCtrlClickProc(void)
{
    if(RelayStateFlag[RELAY_CTRL_STEER_MOTOR_5V_CHAN]){
        SweepRobotTest_SteerMotor5VCtrlOn();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R3, GUI_LIGHTBLUE);
        RelayStateFlag[RELAY_CTRL_STEER_MOTOR_5V_CHAN] = 0;
    }else{
        SweepRobotTest_SteerMotor5VCtrlOff();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R3, GUI_LIGHTGRAY);
        RelayStateFlag[RELAY_CTRL_STEER_MOTOR_5V_CHAN] = 1;
    }
}

void Button_IrDABoard24VRelayCtrlClickProc(void)
{
    if(RelayStateFlag[RELAY_CTRL_IRDA_BOARD_24V_CHAN]){
        SweepRobot_IrDATestTxRelayOn();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R4, GUI_LIGHTBLUE);
        RelayStateFlag[RELAY_CTRL_IRDA_BOARD_24V_CHAN] = 0;
    }else{
        SweepRobot_IrDATestTxRelayOff();
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R4, GUI_LIGHTGRAY);
        RelayStateFlag[RELAY_CTRL_IRDA_BOARD_24V_CHAN] = 1;
    }
}

void Button_CollisionRelayCtrlClickProc(enum RELAY_CTRL_CHAN chan)
{
    if(RelayStateFlag[chan]){
        SweepRobot_CollisionRelayCtrlOn((enum COLLISION_CHAN)chan);
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R5+chan, GUI_LIGHTBLUE);
        RelayStateFlag[chan] = 0;
    }else{
        SweepRobot_CollisionRelayCtrlOff((enum COLLISION_CHAN)chan);
        Button_Set_BkColor(hWin_SWRB_RELAY, ID_RELAYCTRL_BUTTON_R5+chan, GUI_LIGHTGRAY);
        RelayStateFlag[chan] = 1;
    }
}

void Button_R5Proc(void)
{
    Button_CollisionRelayCtrlClickProc(RELAY_CTRL_COLLISION_CHAN_L);
}

void Button_R6Proc(void)
{
    Button_CollisionRelayCtrlClickProc(RELAY_CTRL_COLLISION_CHAN_FL);
}

void Button_R7Proc(void)
{
    Button_CollisionRelayCtrlClickProc(RELAY_CTRL_COLLISION_CHAN_R);
}

void Button_R8Proc(void)
{
    Button_CollisionRelayCtrlClickProc(RELAY_CTRL_COLLISION_CHAN_FR);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    for(Id=ID_RELAYCTRL_BUTTON_R1;Id<=ID_RELAYCTRL_BUTTON_BOUND;Id++){
        hItem = WM_GetDialogItem(pMsg->hWin, Id);
        Button_Init(hItem);
    }
  
    //
    // Initialization of 'btnExit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_EXIT);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetText(hItem, "Exit");
    //
    // Initialization of 'btnStart'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_START);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetText(hItem, "Start");
    //
    // Initialization of 'btnSet'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_SET);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetText(hItem, "Set");
    //
    // Initialization of 'btnStop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_STOP);
    BUTTON_SetFont(hItem, GUI_FONT_24_ASCII);
    BUTTON_SetText(hItem, "Stop");
    //
    // Initialization of 'btnRelay1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R1);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "STEP MOTOR 24V");
    //
    // Initialization of 'btnRelay2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R2);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "CHARGE 24V");
    //
    // Initialization of 'btnRelay3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R3);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "STEER MOTOR 5V");
    //
    // Initialization of 'btnRelay4'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R4);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "IRDA 24V");
    //
    // Initialization of 'btnRelay5'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R5);
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    BUTTON_SetText(hItem, "Relay 5");
    //
    // Initialization of 'btnRelay6'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R6);
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    BUTTON_SetText(hItem, "Relay 6");
    //
    // Initialization of 'btnRelay7'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R7);
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    BUTTON_SetText(hItem, "Relay 7");
    //
    // Initialization of 'btnRelay8'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RELAYCTRL_BUTTON_R8);
    BUTTON_SetFont(hItem, GUI_FONT_20_ASCII);
    BUTTON_SetText(hItem, "Relay 8");
    
    WM_HideWin(pMsg->hWin);

    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_RELAYCTRL_BUTTON_EXIT: // Notifications sent by 'btnExit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        WM_HideWin(pMsg->hWin);
        WM_ShowWin(hWin_SWRB_START);
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_START: // Notifications sent by 'btnStart'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_SET: // Notifications sent by 'btnSet'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_STOP: // Notifications sent by 'btnStop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R1: // Notifications sent by 'btnRelay1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        Button_StepMotor24VRelayCtrlClickProc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R2: // Notifications sent by 'btnRelay2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        Button_Charge24VRelayCtrlClickProc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R3: // Notifications sent by 'btnRelay3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        Button_SteerMotor5VRelayCtrlClickProc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R4: // Notifications sent by 'btnRelay4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        Button_IrDABoard24VRelayCtrlClickProc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R5: // Notifications sent by 'btnRelay5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
          Button_R5Proc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R6: // Notifications sent by 'btnRelay6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
          Button_R6Proc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R7: // Notifications sent by 'btnRelay7'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
          Button_R7Proc();
        break;
      }
      break;
    case ID_RELAYCTRL_BUTTON_R8: // Notifications sent by 'btnRelay8'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
          Button_R8Proc();
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/

WM_HWIN hWin_SWRB_RELAY;

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreatewinRelay
*/
WM_HWIN CreatewinRelayDLG(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

/*************************** End of file ****************************/
