/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: eje_CHNFont_Songti24_txt.c                            *
* Font:        ËÎÌו                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x5E8F (24207)                                *
* Character enabled:   0x5217 (21015)                                *
* Character enabled:   0x53F7 (21495)                                *
* Character enabled:   0x65F6 (26102)                                *
* Character enabled:   0x95F4 (38388)                                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonteje_CHNFont_Songti24_txt;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fonteje_CHNFont_Songti24_txt_5217[ 72] = { /* code 5217 */
  ________,________,________,
  ________,________,________,
  ________,________,____XX__,
  ________,____XX__,____X___,
  ___XXXXX,XXXXXXX_,____X___,
  _______X,________,____X___,
  _______X,_______X,X___X___,
  ______XX,_______X,X___X___,
  ______X_,___XX__X,X___X___,
  _____XXX,XXXXX__X,X___X___,
  _____X__,___X___X,X___X___,
  ____XXX_,__XX___X,X___X___,
  ____X_XX,__XX___X,X___X___,
  ___X___X,__X____X,X___X___,
  __X____X,_XX____X,X___X___,
  _______X,_X_____X,X___X___,
  ________,XX_____X,X___X___,
  ________,X______X,X___X___,
  _______X,_______X,____X___,
  ______X_,________,____X___,
  _____X__,________,____X___,
  ___XX___,________,XXXXX___,
  __X_____,________,___X____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonteje_CHNFont_Songti24_txt_53F7[ 72] = { /* code 53F7 */
  ________,________,________,
  ________,________,________,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______X_,________,_X______,
  ______XX,XXXXXXXX,XX______,
  ______X_,________,________,
  ________,________,____XX__,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,XX______,________,
  ________,X_______,________,
  _______X,X_______,_XX_____,
  _______X,_XXXXXXX,XXX_____,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,XX______,
  ________,________,XX______,
  ________,___XXXXX,X_______,
  ________,_____XXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonteje_CHNFont_Songti24_txt_5E8F[ 72] = { /* code 5E8F */
  ________,________,________,
  ________,___X____,________,
  ________,____XX__,________,
  ________,_____X__,____X___,
  ____X___,_____X__,___XXX__,
  ____XXXX,XXXXX_XX,XXX_____,
  ____X___,________,________,
  ____X__X,XXXXXXXX,XXXX____,
  ____X___,________,_XX_____,
  ____X___,___X___X,X_______,
  ____X___,____XXX_,________,
  ____X___,_____XX_,________,
  ____X___,______X_,____XX__,
  ____X_XX,XXXXXXXX,XXXXXXX_,
  ____X___,_____XX_,___X____,
  ___XX___,_____XX_,________,
  ___X____,_____XX_,________,
  ___X____,_____XX_,________,
  ___X____,_____XX_,________,
  __X_____,_____XX_,________,
  __X_____,_____XX_,________,
  _X______,__XXXX__,________,
  _X______,____XX__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonteje_CHNFont_Songti24_txt_65F6[ 72] = { /* code 65F6 */
  ________,________,________,
  ________,________,________,
  ________,________,_XX_____,
  ________,________,_X______,
  __X____X,X_______,_X______,
  __XXXXXX,X_______,_X______,
  __X____X,X_______,_X______,
  __X____X,XXXXXXXX,XXXXXX__,
  __X____X,X_______,_X______,
  __X____X,X_______,_X______,
  __X____X,X_______,_X______,
  __XXXXXX,X__X____,_X______,
  __X____X,X___X___,_X______,
  __X____X,X___XX__,_X______,
  __X____X,X___XX__,_X______,
  __X____X,X_______,_X______,
  __X____X,X_______,_X______,
  __X____X,X_______,_X______,
  __XXXXXX,X_______,_X______,
  __X____X,________,_X______,
  __X_____,________,_X______,
  ________,______XX,XX______,
  ________,________,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fonteje_CHNFont_Songti24_txt_95F4[ 72] = { /* code 95F4 */
  ________,________,________,
  ________,________,________,
  _____X__,________,________,
  ______X_,________,____X___,
  ______XX,__XXXXXX,XXXXX___,
  ___XX_X_,________,____X___,
  ___X____,________,____X___,
  ___X____,X_______,____X___,
  ___X____,XXXXXXXX,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,XXXXXXX_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____X_,____X___,
  ___X____,X_____XX,____X___,
  ___X____,X_____XX,____X___,
  ___X____,XXXXXXXX,____X___,
  ___X____,X_____X_,____X___,
  ___X____,________,____X___,
  ___X____,________,____X___,
  ___X____,________,_XXXX___,
  ___X____,________,__XX____,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fonteje_CHNFont_Songti24_txt_CharInfo[5] = {
   {  24,  24,  3, acGUI_Fonteje_CHNFont_Songti24_txt_5217 } /* code 5217 */
  ,{  24,  24,  3, acGUI_Fonteje_CHNFont_Songti24_txt_53F7 } /* code 53F7 */
  ,{  24,  24,  3, acGUI_Fonteje_CHNFont_Songti24_txt_5E8F } /* code 5E8F */
  ,{  24,  24,  3, acGUI_Fonteje_CHNFont_Songti24_txt_65F6 } /* code 65F6 */
  ,{  24,  24,  3, acGUI_Fonteje_CHNFont_Songti24_txt_95F4 } /* code 95F4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonteje_CHNFont_Songti24_txt_Prop5 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonteje_CHNFont_Songti24_txt_Prop4 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_CharInfo[  3] /* address of first character */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonteje_CHNFont_Songti24_txt_Prop3 = {
   0x5E8F /* first character */
  ,0x5E8F /* last character  */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_CharInfo[  2] /* address of first character */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonteje_CHNFont_Songti24_txt_Prop2 = {
   0x53F7 /* first character */
  ,0x53F7 /* last character  */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_CharInfo[  1] /* address of first character */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonteje_CHNFont_Songti24_txt_Prop1 = {
   0x5217 /* first character */
  ,0x5217 /* last character  */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_CharInfo[  0] /* address of first character */
  ,&GUI_Fonteje_CHNFont_Songti24_txt_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fonteje_CHNFont_Songti24_txt = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonteje_CHNFont_Songti24_txt_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

